//! New TypeScript project generation pipeline using TsExpr IR.
//!
//! Replaces `typescript.rs`'s `generate_ts` with a pipeline that routes
//! function bodies through `lower_to_ts → transforms → emit_ts`.
//!
//! ## Pipeline
//!
//! ```text
//! Solution
//!   → build GenCtx (shared with Rust backend)
//!   → for each module:
//!       types.ts     — interfaces for struct-shaped constructs
//!       interfaces.ts — interfaces for trait-shaped constructs (ports)
//!       services.ts  — functions lowered through TsExpr IR
//!   → index.ts, package.json, tsconfig.json
//!   → import tracking on each file
//! ```
//!
//! During transition (Sessions 5-10), this coexists with `typescript.rs`.
//! Call `generate_ts_ir` for the new pipeline.

use veil_ir::ast::*;
use veil_ir::layer::{LayerRegistry, Shape};

use crate::expr::{build_ctx_from_solution, GenCtx};
use crate::rust::build_name_to_shape;
use crate::typescript::{type_to_ts, TsFile, TsProject};

use super::emit::emit_ts;
use super::lower::to_camel_case;
use super::transforms::detect_async;

// ─── Public Entry Point ──────────────────────────────────────────────────────

/// Generate a TypeScript project using the new TsExpr IR pipeline.
///
/// This produces the same file structure as the old `generate_ts` but routes
/// function bodies through `lower_to_ts → emit_ts` instead of `expr_to_ts`.
pub fn generate_ts_ir(solution: &Solution, registry: &LayerRegistry) -> TsProject {
    let name_to_shape = build_name_to_shape(solution, registry);
    let ctx = build_ctx_from_solution(solution, name_to_shape, registry);
    let sol_name = to_camel_case(&solution.name);

    // Collect module constructs
    let modules: Vec<&Construct> = solution
        .items
        .iter()
        .filter_map(|i| match i {
            TopLevelItem::Construct(c) if c.shape == Shape::Mod => Some(c),
            _ => None,
        })
        .collect();

    let mut files = Vec::new();

    // Generate types.ts — interfaces for struct-shaped constructs
    files.push(gen_types_ir(&modules));

    // Generate interfaces.ts — interfaces for trait-shaped constructs
    files.push(gen_interfaces_ir(&modules, solution));

    // Generate services.ts — functions lowered through TsExpr IR
    files.push(gen_services_ir(&modules, solution, &ctx));

    // Generate index.ts (re-exports)
    files.push(gen_index_ir(&sol_name));

    // Generate package.json
    files.push(gen_package_json_ir(&sol_name));

    // Generate tsconfig.json
    files.push(gen_tsconfig_ir());

    // Layer-driven templates (if any)
    let template_output = crate::template::execute_templates(solution, registry, "typescript");
    for tf in template_output.files {
        files.push(TsFile {
            path: tf.path,
            content: tf.content,
        });
    }

    TsProject { files }
}

// ─── Types Generation ────────────────────────────────────────────────────────

/// Generate `src/types.ts` — interfaces for all struct-shaped constructs.
fn gen_types_ir(modules: &[&Construct]) -> TsFile {
    let mut out = String::from("// Generated by VEIL — do not edit\n\n");

    for module in modules {
        let structs = collect_shape(module, Shape::Struct);
        let enums = collect_shape(module, Shape::Enum);

        for s in &structs {
            if s.layer_provided {
                continue;
            }
            if matches!(s.keyword.as_str(), "deps" | "compose" | "endpoint") {
                continue;
            }
            let generics = generic_params_ts(&s.type_params);
            out.push_str(&format!("export interface {}{} {{\n", s.name, generics));

            let fields: Vec<&Field> = if !s.blocks.is_empty() {
                s.blocks
                    .iter()
                    .filter(|b| b.shape != Shape::Enum)
                    .flat_map(|b| b.fields.iter())
                    .collect()
            } else {
                s.fields.iter().collect()
            };

            for f in &fields {
                let ts_type = field_type_ts(f);
                out.push_str(&format!("  {}: {};\n", to_camel_case(&f.name), ts_type));
            }
            out.push_str("}\n\n");
        }

        for e in &enums {
            if e.layer_provided {
                continue;
            }
            if e.variants.is_empty() && e.rich_variants.is_empty() {
                continue;
            }
            let generics = generic_params_ts(&e.type_params);

            if !e.rich_variants.is_empty() {
                // Discriminated union for variants with data
                out.push_str(&format!("export type {}{} =\n", e.name, generics));
                let variants: Vec<String> = e
                    .rich_variants
                    .iter()
                    .map(|v| match v {
                        EnumVariant::Unit(name) => format!("  | {{ type: \"{}\" }}", name),
                        EnumVariant::Tuple(name, types) => {
                            let fields = types
                                .iter()
                                .enumerate()
                                .map(|(i, t)| format!("field{}: {}", i, type_to_ts(t)))
                                .collect::<Vec<_>>()
                                .join("; ");
                            format!("  | {{ type: \"{}\"; {} }}", name, fields)
                        }
                        EnumVariant::Struct(name, fields) => {
                            let fs = fields
                                .iter()
                                .map(|f| {
                                    format!(
                                        "{}: {}",
                                        to_camel_case(&f.name),
                                        type_to_ts(&f.type_expr)
                                    )
                                })
                                .collect::<Vec<_>>()
                                .join("; ");
                            format!("  | {{ type: \"{}\"; {} }}", name, fs)
                        }
                    })
                    .collect();
                out.push_str(&variants.join("\n"));
                out.push_str(";\n\n");
            } else {
                // Simple string union for unit-only enums
                out.push_str(&format!("export type {}{} =\n", e.name, generics));
                let variants: Vec<String> =
                    e.variants.iter().map(|v| format!("  | \"{}\"", v)).collect();
                out.push_str(&variants.join("\n"));
                out.push_str(";\n\n");
            }
        }
    }

    TsFile {
        path: "src/types.ts".to_string(),
        content: out,
    }
}

// ─── Interfaces Generation ───────────────────────────────────────────────────

/// Generate `src/interfaces.ts` — interfaces for all trait-shaped constructs (ports).
fn gen_interfaces_ir(modules: &[&Construct], solution: &Solution) -> TsFile {
    let mut out = String::from("// Generated by VEIL — do not edit\n\n");
    out.push_str("import type * as T from './types';\n\n");
    let type_names = collect_type_names_set(modules);

    let mut all_traits: Vec<&Construct> = Vec::new();
    for module in modules {
        all_traits.extend(
            collect_shape(module, Shape::Trait)
                .into_iter()
                .filter(|t| !t.layer_provided),
        );
    }
    // Also include top-level traits not nested in modules
    for item in &solution.items {
        if let TopLevelItem::Construct(c) = item {
            if c.shape == Shape::Trait && !c.layer_provided {
                all_traits.push(c);
            }
        }
    }

    for t in &all_traits {
        let generics = generic_params_ts(&t.type_params);
        out.push_str(&format!("export interface {}{} {{\n", t.name, generics));
        for method in &t.methods {
            let params = method
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        to_camel_case(&p.name),
                        type_to_ts_qualified(&p.type_expr, &type_names)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let ret = match &method.return_type {
                Some(ty) => {
                    let inner = type_to_ts_qualified(ty, &type_names);
                    if inner.starts_with("Promise<") {
                        inner
                    } else {
                        format!("Promise<{}>", inner)
                    }
                }
                None => "Promise<void>".to_string(),
            };
            let method_name = to_camel_case(method.name.trim_end_matches(['!', '?']));
            out.push_str(&format!("  {}({}): {};\n", method_name, params, ret));
        }
        out.push_str("}\n\n");
    }

    TsFile {
        path: "src/interfaces.ts".to_string(),
        content: out,
    }
}

// ─── Services Generation (IR-based) ─────────────────────────────────────────

/// Generate `src/services.ts` — functions lowered through the TsExpr IR pipeline.
fn gen_services_ir(modules: &[&Construct], solution: &Solution, ctx: &GenCtx) -> TsFile {
    let mut out = String::from("// Generated by VEIL — do not edit\n\n");
    out.push_str("import type * as T from './types';\n");
    out.push_str("import type * as I from './interfaces';\n\n");
    let type_names = collect_type_names_set(modules);

    for module in modules {
        let fns = collect_shape(module, Shape::Fn);
        for f in &fns {
            if f.layer_provided {
                continue;
            }
            out.push_str(&gen_function_ir(f, ctx, &type_names));
        }
    }

    // Also generate top-level flows
    for item in &solution.items {
        if let TopLevelItem::Flow(flow) = item {
            out.push_str(&gen_flow_ir(flow, ctx));
        }
    }

    TsFile {
        path: "src/services.ts".to_string(),
        content: out,
    }
}

/// Generate a single function through the TsExpr IR pipeline.
fn gen_function_ir(
    f: &Construct,
    ctx: &GenCtx,
    type_names: &std::collections::HashSet<String>,
) -> String {
    let fn_name = to_camel_case(&f.name);
    let params = f
        .inputs
        .iter()
        .map(|p| {
            format!(
                "{}: {}",
                to_camel_case(&p.name),
                type_to_ts_qualified(&p.type_expr, type_names)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    // Collect all body expressions from steps and lower through TsExpr IR
    let mut ts_body = Vec::new();
    for step in &f.steps {
        if let FlowStep::Step(s) = step {
            for expr in &s.body {
                ts_body.push(super::lower::lower_to_ts(expr, ctx));
            }
        }
    }

    // Determine if async based on the IR tree
    let is_async = detect_async(&ts_body);

    // Determine return type
    let ret = f
        .return_type
        .as_ref()
        .map(|t| {
            let inner = type_to_ts_qualified(t, type_names);
            if inner.starts_with("Promise<") {
                inner
            } else if is_async {
                format!("Promise<{}>", inner)
            } else {
                inner
            }
        })
        .unwrap_or_else(|| {
            if is_async {
                "Promise<void>".to_string()
            } else {
                "void".to_string()
            }
        });

    // Emit the body
    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    out.push_str(&format!(
        "export {}function {}({}): {} {{\n",
        async_kw, fn_name, params, ret
    ));

    // Emit step comments and bodies
    let mut expr_idx = 0;
    for step in &f.steps {
        if let FlowStep::Step(s) = step {
            out.push_str(&format!("  // Step: {}\n", s.name));
            for _ in &s.body {
                if expr_idx < ts_body.len() {
                    let emitted = emit_ts(&ts_body[expr_idx]);
                    out.push_str(&format!("  {};\n", emitted));
                    expr_idx += 1;
                }
            }
        }
    }

    // If no steps, emit body directly
    if f.steps.is_empty() && !ts_body.is_empty() {
        for expr in &ts_body {
            let emitted = emit_ts(expr);
            out.push_str(&format!("  {};\n", emitted));
        }
    }

    out.push_str("}\n\n");
    out
}

/// Generate a flow function through the TsExpr IR pipeline.
fn gen_flow_ir(flow: &Flow, ctx: &GenCtx) -> String {
    let fn_name = to_camel_case(&flow.name);
    let params = flow
        .inputs
        .iter()
        .map(|p| format!("{}: {}", to_camel_case(&p.name), type_to_ts(&p.type_expr)))
        .collect::<Vec<_>>()
        .join(", ");

    // Lower step bodies through TsExpr IR
    let mut ts_body = Vec::new();
    for step in &flow.steps {
        if let FlowStep::Step(s) = step {
            for expr in &s.body {
                ts_body.push(super::lower::lower_to_ts(expr, ctx));
            }
        }
    }

    // Determine if async
    let is_async = detect_async(&ts_body);

    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    let ret = if is_async {
        "Promise<void>"
    } else {
        "void"
    };
    out.push_str(&format!(
        "export {}function {}({}): {} {{\n",
        async_kw, fn_name, params, ret
    ));

    let mut expr_idx = 0;
    for step in &flow.steps {
        if let FlowStep::Step(s) = step {
            out.push_str(&format!("  // Step: {}\n", s.name));
            for _ in &s.body {
                if expr_idx < ts_body.len() {
                    let emitted = emit_ts(&ts_body[expr_idx]);
                    out.push_str(&format!("  {};\n", emitted));
                    expr_idx += 1;
                }
            }
        }
    }

    out.push_str("}\n\n");
    out
}

// ─── Index + Config Files ────────────────────────────────────────────────────

fn gen_index_ir(sol_name: &str) -> TsFile {
    let content = format!(
        "// Generated by VEIL — do not edit\n\
         // Package: {}\n\n\
         export * from './types';\n\
         export * from './interfaces';\n\
         export * from './services';\n",
        sol_name
    );
    TsFile {
        path: "src/index.ts".to_string(),
        content,
    }
}

fn gen_package_json_ir(sol_name: &str) -> TsFile {
    let content = format!(
        r#"{{
  "name": "{}",
  "version": "0.1.0",
  "type": "module",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {{
    "build": "tsc",
    "dev": "tsc --watch"
  }},
  "devDependencies": {{
    "typescript": "^5.4.0"
  }}
}}
"#,
        to_kebab(sol_name)
    );
    TsFile {
        path: "package.json".to_string(),
        content,
    }
}

fn gen_tsconfig_ir() -> TsFile {
    let content = r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "rootDir": "src",
    "declaration": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"]
}
"#
    .to_string();
    TsFile {
        path: "tsconfig.json".to_string(),
        content,
    }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Collect constructs of a given shape from a module tree.
fn collect_shape(module: &Construct, shape: Shape) -> Vec<&Construct> {
    let mut result = Vec::new();
    fn walk<'a>(c: &'a Construct, shape: Shape, result: &mut Vec<&'a Construct>) {
        for child in &c.children {
            if child.shape == shape {
                result.push(child);
            }
            if child.shape == Shape::Group || child.shape == Shape::Mod {
                walk(child, shape, result);
            }
        }
    }
    walk(module, shape, &mut result);
    result
}

/// Collect type names (structs + enums) for qualified import generation.
fn collect_type_names_set(modules: &[&Construct]) -> std::collections::HashSet<String> {
    let mut types = std::collections::HashSet::new();
    for module in modules {
        for s in collect_shape(module, Shape::Struct) {
            if !s.layer_provided {
                types.insert(s.name.clone());
            }
        }
        for e in collect_shape(module, Shape::Enum) {
            if !e.layer_provided {
                types.insert(e.name.clone());
            }
        }
    }
    types
}

/// Qualify a named type as `T.Book` when it is a generated export.
fn type_to_ts_qualified(ty: &TypeExpr, type_names: &std::collections::HashSet<String>) -> String {
    match ty {
        TypeExpr::Named(name) => {
            if type_names.contains(name) {
                format!("T.{}", name)
            } else {
                type_to_ts(ty)
            }
        }
        TypeExpr::Optional(inner) => {
            format!("{} | null", type_to_ts_qualified(inner, type_names))
        }
        TypeExpr::List(inner) => {
            format!("{}[]", type_to_ts_qualified(inner, type_names))
        }
        TypeExpr::Result(Some(inner)) => {
            format!("Promise<{}>", type_to_ts_qualified(inner, type_names))
        }
        TypeExpr::Result(None) => "Promise<void>".to_string(),
        _ => type_to_ts(ty),
    }
}

/// Format generic type parameters for TypeScript: `<T, U>` or empty string.
fn generic_params_ts(params: &[String]) -> String {
    if params.is_empty() {
        String::new()
    } else {
        format!("<{}>", params.join(", "))
    }
}

/// Field type as TS string, using explicit type or inferring from name.
fn field_type_ts(field: &Field) -> String {
    match &field.type_expr {
        TypeExpr::Named(n) if n.is_empty() => infer_field_type_ts(&field.name),
        ty => type_to_ts(ty),
    }
}

/// Infer a TypeScript type from field name conventions.
fn infer_field_type_ts(name: &str) -> String {
    if name.starts_with("is_") || name.starts_with("has_") {
        "boolean".to_string()
    } else if name.ends_with("_at") || name.ends_with("_date") {
        "Date".to_string()
    } else if name == "id" || name.ends_with("_id") {
        "string".to_string()
    } else if name.ends_with("_count") || name == "count" || name == "amount" || name == "total" {
        "number".to_string()
    } else {
        "string".to_string()
    }
}

/// Convert PascalCase/snake_case to kebab-case for package names.
fn to_kebab(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('-');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else if c == '_' {
            result.push('-');
        } else {
            result.push(c);
        }
    }
    result
}
