//! Svelte 5 component generation using structured IRs.
//!
//! Ports `gen_svelte_file` from `typescript.rs` to use the new TsExpr/HtmlExpr/CssExpr
//! intermediate representations. The three sections of a `.svelte` file are:
//!
//! 1. `<script lang="ts">` → TsExpr nodes → `emit_ts()`
//! 2. Template → HtmlExpr nodes → `emit_html()`
//! 3. `<style>` → CssExpr nodes → `emit_css()`
//!
//! Each section has its own mini-parser (for template/style raw blocks) or
//! structural lowering (for script blocks using VEIL IR fields).

use veil_ir::ast::{Construct, Expr, TypeExpr};
use veil_ir::layer::LayerRegistry;
use veil_ir::ReactivityPolicy;

use crate::css::{CssDeclaration, CssExpr};
use crate::css::emit::emit_css_nodes;
use crate::html::{HtmlAttr, HtmlAttrValue, HtmlExpr};
use crate::typescript::{expr_to_ts, field_type_ts, type_to_ts};

// Future: when script section moves fully to TsExpr IR, these will be used.
// use crate::html::emit::emit_html_nodes;
// use crate::ts::emit::emit_ts;
// use crate::ts::expr::TsExpr;

// ─── Public API ──────────────────────────────────────────────────────────────

/// Generated Svelte component file (path + content).
pub struct SvelteFile {
    pub path: String,
    pub content: String,
}

/// Generate a complete `.svelte` file from a Component construct using the
/// structured IR pipeline (TsExpr → emit_ts, HtmlExpr → emit_html, CssExpr → emit_css).
///
/// Default output path: `src/lib/components/{name}.svelte`.
/// Use [`gen_svelte_component_at`] for SvelteKit routing paths.
pub fn gen_svelte_component(comp: &Construct, registry: &LayerRegistry) -> SvelteFile {
    let path = format!("src/lib/components/{}.svelte", comp.name);
    gen_svelte_component_at(comp, registry, &path)
}

/// Generate a `.svelte` file at a specific output path.
///
/// Used by the SvelteKit integration to place pages at
/// `src/routes/{route}/+page.svelte` and layouts at `+layout.svelte`.
pub fn gen_svelte_component_at(comp: &Construct, registry: &LayerRegistry, path: &str) -> SvelteFile {
    let script = generate_script_section(comp, registry);
    let template = generate_template_section(comp);
    let style = generate_style_section(comp);

    let content = format!(
        "<script lang=\"ts\">\n{}</script>\n\n{}\n\n<style>\n{}\n</style>\n",
        script, template, style,
    );

    SvelteFile { path: path.to_string(), content }
}

/// Generate a Svelte 5 rune-based store file (`.svelte.ts`).
///
/// Stores use `$state()` runes exported from a `.svelte.ts` module rather than
/// the old `writable()`/`readable()` API. Output path: `src/lib/stores/{name}.svelte.ts`.
pub fn gen_svelte_store(comp: &Construct, _registry: &LayerRegistry) -> SvelteFile {
    gen_svelte_store_at(comp, _registry, &format!("src/lib/stores/{}.svelte.ts", to_snake(&comp.name)))
}

/// Generate a Svelte 5 rune-based store file at a specific output path.
pub fn gen_svelte_store_at(comp: &Construct, _registry: &LayerRegistry, path: &str) -> SvelteFile {
    let mut out = String::new();
    out.push_str(&format!("// {} — Svelte 5 rune-based store (generated by VEIL)\n\n", comp.name));

    // State fields → exported $state runes
    let state_block = comp.blocks.iter().find(|b| b.keyword == "state");
    if let Some(state) = state_block {
        for field in &state.fields {
            let ty = field_type_ts(field);
            let default = if let Some(expr) = &field.default_expr {
                expr_to_ts(expr, 0)
            } else {
                default_value_for_ts(&ty).to_string()
            };
            out.push_str(&format!("export let {} = $state<{}>({});\n", field.name, ty, default));
        }
        out.push('\n');
    }

    // Methods → exported functions
    for f in &comp.fns {
        if f.name == "template" || f.name == "style" || f.name == "script" {
            continue;
        }
        let params = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, type_to_ts(&p.type_expr)))
            .collect::<Vec<_>>()
            .join(", ");
        let is_async = f
            .return_type
            .as_ref()
            .map(|t| matches!(t, TypeExpr::Result(_)))
            .unwrap_or(false);
        let async_kw = if is_async { "async " } else { "" };
        let ret = match &f.return_type {
            Some(TypeExpr::Result(Some(inner))) => format!(": Promise<{}>", type_to_ts(inner)),
            Some(TypeExpr::Result(None)) => ": Promise<void>".into(),
            Some(ty) => format!(": {}", type_to_ts(ty)),
            None => String::new(),
        };
        out.push_str(&format!("export {}function {}({}){} {{\n", async_kw, f.name, params, ret));
        for expr in &f.body {
            out.push_str(&format!("  {};\n", expr_to_ts(expr, 1)));
        }
        out.push_str("}\n\n");
    }

    SvelteFile { path: path.to_string(), content: out }
}

// ─── SvelteKit Path Resolution ───────────────────────────────────────────────

/// Determine the SvelteKit output path for a UI construct based on its subkind
/// and route annotation.
///
/// - Page → `src/routes/{route}/+page.svelte`
/// - Layout → `src/routes/{route}/+layout.svelte`
/// - Component → `src/lib/components/{Name}.svelte`
/// - Store → `src/lib/stores/{name}.svelte.ts`
pub fn sveltekit_output_path(comp: &Construct, registry: &LayerRegistry) -> String {
    let subkind = comp.subkind.to_lowercase();
    match subkind.as_str() {
        "page" => {
            let route = registry
                .ui_route_path(comp)
                .unwrap_or_else(|| format!("/{}", comp.name.to_lowercase()));
            let segment = route.trim().trim_matches('/');
            if segment.is_empty() {
                "src/routes/+page.svelte".to_string()
            } else {
                format!("src/routes/{}/+page.svelte", segment)
            }
        }
        "layout" => {
            let route = registry
                .ui_route_path(comp)
                .unwrap_or_default();
            let segment = route.trim().trim_matches('/');
            if segment.is_empty() {
                "src/routes/+layout.svelte".to_string()
            } else {
                format!("src/routes/{}/+layout.svelte", segment)
            }
        }
        "store" => {
            format!("src/lib/stores/{}.svelte.ts", to_snake(&comp.name))
        }
        _ => {
            // Default: component
            format!("src/lib/components/{}.svelte", comp.name)
        }
    }
}

/// Convert PascalCase to snake_case for store filenames.
fn to_snake(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

// ─── Script Section ──────────────────────────────────────────────────────────

/// Generate the `<script lang="ts">` section content.
///
/// Translates props, state, derived, effects, and methods from the VEIL construct
/// into TsExpr nodes, then emits them as TypeScript text with proper indentation.
fn generate_script_section(comp: &Construct, registry: &LayerRegistry) -> String {
    let mut lines: Vec<String> = Vec::new();
    let pol = &registry.reactivity_policy;

    // Header comment
    lines.push("  // Generated by VEIL".to_string());

    // Detect component references in template for imports
    let template_content = get_raw_block(comp, "template");
    let imports = detect_component_imports(&template_content, &comp.name);
    if !imports.is_empty() {
        lines.push(String::new());
        for imp in &imports {
            lines.push(format!("  import {} from './{}.svelte';", imp, imp));
        }
    }

    // Props block → interface + destructure via $props()
    let props_block = comp.blocks.iter().find(|b| b.keyword == "props");
    if let Some(props) = props_block {
        lines.push(String::new());
        lines.push("  interface Props {".to_string());
        for field in &props.fields {
            let ty = field_type_ts(field);
            let optional = field.default_expr.is_some()
                || ty.contains("null")
                || ty.starts_with("Snippet");
            if optional {
                lines.push(format!("    {}?: {};", field.name, ty));
            } else {
                lines.push(format!("    {}: {};", field.name, ty));
            }
        }
        lines.push("  }".to_string());

        let bindings = build_props_bindings(&props.fields, pol);
        let props_call = if pol.props_call.is_empty() {
            "undefined as any /* no reactivity_policy.props_call */".to_string()
        } else {
            pol.props_call.clone()
        };
        lines.push(format!("  let {{ {} }}: Props = {};", bindings, props_call));
    }

    // State block → $state() runes
    let state_block = comp.blocks.iter().find(|b| b.keyword == "state");
    if let Some(state) = state_block {
        lines.push(String::new());
        for field in &state.fields {
            let ty = field_type_ts(field);
            let default = if let Some(expr) = &field.default_expr {
                expr_to_ts(expr, 1)
            } else {
                default_value_for_ts(&ty).to_string()
            };
            if pol.state_line.is_empty() {
                lines.push(format!("  let {}: {} = {};", field.name, ty, default));
            } else {
                let line = ReactivityPolicy::fill(
                    &pol.state_line,
                    &[
                        ("name", field.name.as_str()),
                        ("type", ty.as_str()),
                        ("default", default.as_str()),
                    ],
                );
                let line = line.trim_end().to_string();
                let line = if line.ends_with(';') { line } else { format!("{};", line) };
                lines.push(format!("  {}", line));
            }
        }
    }

    // Derived block → $derived() runes
    let derived_block = comp.blocks.iter().find(|b| b.keyword == "derived");
    if let Some(derived) = derived_block {
        lines.push(String::new());
        for field in &derived.fields {
            let ty = field_type_ts(field);
            if let Some(expr) = &field.default_expr {
                let expr_str = expr_to_ts(expr, 1);
                if pol.derived_line.is_empty() {
                    lines.push(format!("  let {}: {} = {};", field.name, ty, expr_str));
                } else {
                    let line = ReactivityPolicy::fill(
                        &pol.derived_line,
                        &[("name", field.name.as_str()), ("expr", expr_str.as_str())],
                    );
                    let line = line.trim_end().to_string();
                    let line = if line.ends_with(';') { line } else { format!("{};", line) };
                    lines.push(format!("  {}", line));
                }
            } else if pol.derived_line.is_empty() {
                lines.push(format!("  let {}: {} = undefined as any;", field.name, ty));
            } else {
                let line = ReactivityPolicy::fill(
                    &pol.derived_line,
                    &[("name", field.name.as_str()), ("expr", "undefined as any")],
                );
                let line = line.trim_end().to_string();
                let line = if line.ends_with(';') { line } else { format!("{};", line) };
                lines.push(format!("  {}", line));
            }
        }
    }

    // Effects → $effect() runes
    if !comp.effects.is_empty() {
        lines.push(String::new());
        for eff in &comp.effects {
            let async_body = effect_body_needs_await(&eff.body);
            let mut body = String::new();
            if async_body {
                for expr in &eff.body {
                    body.push_str(&format!("      {};\n", expr_to_ts_async(expr, 3)));
                }
            } else {
                for expr in &eff.body {
                    body.push_str(&format!("    {};\n", expr_to_ts(expr, 2)));
                }
            }
            if !eff.cleanup.is_empty() {
                body.push_str("    return () => {\n");
                for expr in &eff.cleanup {
                    body.push_str(&format!("      {};\n", expr_to_ts(expr, 3)));
                }
                body.push_str("    };\n");
            }
            let body = body.trim_end_matches('\n').to_string();

            let template = if async_body { &pol.effect_async } else { &pol.effect_sync };
            if template.is_empty() {
                lines.push(format!(
                    "  // effect {} (no reactivity_policy.effect_*):",
                    eff.name
                ));
                for line in body.lines() {
                    lines.push(format!("  {}", line));
                }
            } else {
                let filled = ReactivityPolicy::fill(
                    template,
                    &[("name", eff.name.as_str()), ("body", body.as_str())],
                );
                for line in filled.lines() {
                    lines.push(format!("  {}", line));
                }
            }
        }
    }

    // Methods → function declarations
    let method_fns: Vec<_> = comp
        .fns
        .iter()
        .filter(|f| f.name != "template" && f.name != "style" && f.name != "script")
        .collect();
    if !method_fns.is_empty() {
        lines.push(String::new());
        for f in &method_fns {
            let params = f
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, type_to_ts(&p.type_expr)))
                .collect::<Vec<_>>()
                .join(", ");
            let is_async = f
                .return_type
                .as_ref()
                .map(|t| matches!(t, TypeExpr::Result(_)))
                .unwrap_or(false)
                || effect_body_needs_await(&f.body);
            let async_kw = if is_async { "async " } else { "" };
            lines.push(format!("  {}function {}({}) {{", async_kw, f.name, params));
            for expr in &f.body {
                let line = if is_async {
                    expr_to_ts_async(expr, 2)
                } else {
                    expr_to_ts(expr, 2)
                };
                lines.push(format!("    {};", line));
            }
            lines.push("  }".to_string());
        }
    }

    // Raw script escape hatch
    let client_script = get_raw_block(comp, "script");
    if !client_script.is_empty() {
        lines.push(String::new());
        lines.push("  // raw script block (escape hatch — prefer VEIL fn/effect)".to_string());
        for line in client_script.lines() {
            let t = line.trim();
            if t.is_empty() {
                lines.push(String::new());
            } else {
                lines.push(format!("  {}", t));
            }
        }
    }

    let mut out = lines.join("\n");
    out.push('\n');
    out
}

// ─── Template Section ────────────────────────────────────────────────────────

/// Generate the template section by parsing Svelte template syntax into HtmlExpr nodes.
///
/// Handles common patterns:
/// - HTML elements with attributes
/// - `{expression}` interpolations
/// - `{#if cond}...{:else}...{/if}` conditionals
/// - `{#each items as item}...{/each}` loops
/// - `{@render snippet(args)}` render calls
/// - `{@html expr}` raw HTML injection
///
/// Complex or unrecognized patterns pass through as `HtmlExpr::RawHtml`.
fn generate_template_section(comp: &Construct) -> String {
    let template_content = get_raw_block(comp, "template");

    if template_content.is_empty() {
        // Fallback: check fns named "template" (old pattern)
        let content = get_fn_string_body(comp, "template");
        if content.is_empty() {
            return format!(
                "<!-- veil: empty template shell for {} — add `template` raw block when needed -->\n<div class=\"veil-shell\"></div>",
                comp.name
            );
        }
        return dedent_block(&content);
    }

    dedent_block(&template_content)
}

/// Parse Svelte template text into HtmlExpr nodes.
///
/// This is a best-effort mini-parser. It handles the 80% case for
/// well-structured Svelte templates. Complex nesting or unusual patterns
/// fall through as raw text.
pub fn parse_template_to_html_exprs(input: &str) -> Vec<HtmlExpr> {
    let input = input.trim();
    if input.is_empty() {
        return vec![];
    }

    let mut nodes = Vec::new();
    let chars: Vec<char> = input.chars().collect();
    let mut pos = 0;

    while pos < chars.len() {
        // Skip whitespace between top-level nodes
        if chars[pos].is_whitespace() {
            pos += 1;
            continue;
        }

        if pos < chars.len() && chars[pos] == '{' {
            // Svelte block or interpolation
            if let Some((node, end)) = try_parse_svelte_block(&chars, pos) {
                nodes.push(node);
                pos = end;
                continue;
            }
        }

        if pos < chars.len() && chars[pos] == '<' {
            // HTML comment
            if starts_with_at(&chars, pos, "<!--") {
                if let Some(end) = find_str(&chars, pos, "-->") {
                    let text: String = chars[pos + 4..end].iter().collect();
                    nodes.push(HtmlExpr::Comment(text.trim().to_string()));
                    pos = end + 3;
                    continue;
                }
            }
            // HTML element
            if let Some((node, end)) = try_parse_element(&chars, pos) {
                nodes.push(node);
                pos = end;
                continue;
            }
        }

        // Text content — collect until next `<` or `{`
        let start = pos;
        while pos < chars.len() && chars[pos] != '<' && chars[pos] != '{' {
            pos += 1;
        }
        let text: String = chars[start..pos].iter().collect();
        let text = text.trim();
        if !text.is_empty() {
            nodes.push(HtmlExpr::Text(text.to_string()));
        }
    }

    nodes
}

/// Try to parse a Svelte block (`{#if}`, `{#each}`, `{@render}`, `{@html}`, or interpolation).
fn try_parse_svelte_block(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    if pos >= chars.len() || chars[pos] != '{' {
        return None;
    }

    let after_brace = pos + 1;
    if after_brace >= chars.len() {
        return None;
    }

    // {#if condition}...{:else}...{/if}
    if starts_with_at(chars, after_brace, "#if ") {
        return parse_if_block(chars, pos);
    }

    // {#each iterable as binding}...{/each}
    if starts_with_at(chars, after_brace, "#each ") {
        return parse_each_block(chars, pos);
    }

    // {#snippet name(params)}...{/snippet}
    if starts_with_at(chars, after_brace, "#snippet ") {
        return parse_snippet_block(chars, pos);
    }

    // {@render name(args)}
    if starts_with_at(chars, after_brace, "@render ") {
        return parse_render_call(chars, pos);
    }

    // {@html expr}
    if starts_with_at(chars, after_brace, "@html ") {
        return parse_raw_html(chars, pos);
    }

    // Plain interpolation: {expression}
    if let Some(end) = find_matching_brace(chars, pos) {
        let expr: String = chars[pos + 1..end].iter().collect();
        return Some((HtmlExpr::Interpolation(expr.trim().to_string()), end + 1));
    }

    None
}

fn parse_if_block(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    // Find the closing }
    let cond_start = pos + 4; // after "{#if "
    let block_open_end = find_char(chars, pos, '}')?;
    let condition: String = chars[cond_start..block_open_end].iter().collect();

    // Find matching {/if}
    let body_start = block_open_end + 1;
    let (then_content, else_content, end_pos) = split_if_else(chars, body_start)?;

    let then_children = parse_inline_content(&then_content);
    let else_children = if else_content.is_empty() {
        None
    } else {
        Some(parse_inline_content(&else_content))
    };

    Some((
        HtmlExpr::Conditional {
            condition: condition.trim().to_string(),
            then_children,
            else_children,
        },
        end_pos,
    ))
}

fn parse_each_block(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    // {#each iterable as binding (key)}
    let block_open_end = find_char(chars, pos, '}')?;
    let header: String = chars[pos + 1..block_open_end].iter().collect();
    // Parse: "#each items as item (item.id)"
    let header = header.trim_start_matches("#each ").trim();

    let (iterable, rest) = header.split_once(" as ")?;
    let (binding, key) = if let Some((b, k)) = rest.split_once('(') {
        (b.trim(), Some(k.trim_end_matches(')').trim().to_string()))
    } else {
        (rest.trim(), None)
    };

    // Find body until {/each}
    let body_start = block_open_end + 1;
    let end_tag = "{/each}";
    let end_pos = find_block_end(chars, body_start, end_tag)?;
    let body_content: String = chars[body_start..end_pos].iter().collect();

    let children = parse_inline_content(&body_content);

    Some((
        HtmlExpr::Loop {
            binding: binding.to_string(),
            iterable: iterable.trim().to_string(),
            key,
            children,
        },
        end_pos + end_tag.len(),
    ))
}

fn parse_snippet_block(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    let block_open_end = find_char(chars, pos, '}')?;
    let header: String = chars[pos + 1..block_open_end].iter().collect();
    // Parse: "#snippet name(params)"
    let header = header.trim_start_matches("#snippet ").trim();

    let (name, params_str) = if let Some((n, p)) = header.split_once('(') {
        (n.trim(), p.trim_end_matches(')'))
    } else {
        (header, "")
    };

    let params: Vec<String> = if params_str.is_empty() {
        vec![]
    } else {
        params_str.split(',').map(|s| s.trim().to_string()).collect()
    };

    let body_start = block_open_end + 1;
    let end_tag = "{/snippet}";
    let end_pos = find_block_end(chars, body_start, end_tag)?;
    let body_content: String = chars[body_start..end_pos].iter().collect();

    let children = parse_inline_content(&body_content);

    Some((
        HtmlExpr::Snippet {
            name: name.to_string(),
            params,
            children,
        },
        end_pos + end_tag.len(),
    ))
}

fn parse_render_call(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    let end = find_char(chars, pos, '}')?;
    let inner: String = chars[pos + 1..end].iter().collect();
    // "@render name(args)"
    let inner = inner.trim_start_matches("@render ").trim();

    let (name, args_str) = if let Some((n, a)) = inner.split_once('(') {
        (n.trim(), a.trim_end_matches(')'))
    } else {
        (inner, "")
    };

    let args: Vec<String> = if args_str.is_empty() {
        vec![]
    } else {
        args_str.split(',').map(|s| s.trim().to_string()).collect()
    };

    Some((
        HtmlExpr::RenderCall {
            name: name.to_string(),
            args,
        },
        end + 1,
    ))
}

fn parse_raw_html(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    let end = find_matching_brace(chars, pos)?;
    let inner: String = chars[pos + 1..end].iter().collect();
    let expr = inner.trim_start_matches("@html ").trim().to_string();
    Some((HtmlExpr::RawHtml(expr), end + 1))
}

/// Try to parse an HTML element starting at `<`.
fn try_parse_element(chars: &[char], pos: usize) -> Option<(HtmlExpr, usize)> {
    if pos >= chars.len() || chars[pos] != '<' {
        return None;
    }

    // Skip `<`
    let mut i = pos + 1;

    // Closing tag — not an element start
    if i < chars.len() && chars[i] == '/' {
        return None;
    }

    // Read tag name
    let tag_start = i;
    while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '-' || chars[i] == '_' || chars[i] == ':') {
        i += 1;
    }
    if i == tag_start {
        return None;
    }
    let tag: String = chars[tag_start..i].iter().collect();

    // Check if it's a component (PascalCase)
    let is_component = tag.chars().next().map_or(false, |c| c.is_uppercase());

    // Parse attributes
    let mut attrs = Vec::new();
    loop {
        // Skip whitespace
        while i < chars.len() && chars[i].is_whitespace() {
            i += 1;
        }
        if i >= chars.len() {
            return None;
        }

        // Self-closing /> or closing >
        if chars[i] == '/' && i + 1 < chars.len() && chars[i + 1] == '>' {
            i += 2;
            if is_component {
                let props = attrs_to_component_props(&attrs);
                return Some((
                    HtmlExpr::Component { name: tag, props, children: vec![] },
                    i,
                ));
            }
            return Some((
                HtmlExpr::Element { tag, attrs, children: vec![] },
                i,
            ));
        }
        if chars[i] == '>' {
            i += 1;
            break;
        }

        // Parse an attribute
        if let Some((attr, end)) = parse_attr(chars, i) {
            attrs.push(attr);
            i = end;
        } else {
            // Unrecognized — skip char
            i += 1;
        }
    }

    // Check for void elements
    if crate::html::is_void_element(&tag) {
        return Some((HtmlExpr::Element { tag, attrs, children: vec![] }, i));
    }

    // Parse children until closing tag
    let (children, end_pos) = parse_children_until_close(chars, i, &tag);

    if is_component {
        let props = attrs_to_component_props(&attrs);
        Some((HtmlExpr::Component { name: tag, props, children }, end_pos))
    } else {
        Some((HtmlExpr::Element { tag, attrs, children }, end_pos))
    }
}

/// Parse children of an element until we find `</tag>`.
fn parse_children_until_close(chars: &[char], start: usize, tag: &str) -> (Vec<HtmlExpr>, usize) {
    let mut children = Vec::new();
    let mut pos = start;
    let close_tag = format!("</{}>", tag);

    while pos < chars.len() {
        // Check for closing tag
        if starts_with_at(chars, pos, &close_tag) {
            return (children, pos + close_tag.len());
        }

        // Svelte block or interpolation
        if chars[pos] == '{' {
            if let Some((node, end)) = try_parse_svelte_block(chars, pos) {
                children.push(node);
                pos = end;
                continue;
            }
        }

        // Nested element
        if chars[pos] == '<' && pos + 1 < chars.len() && chars[pos + 1] != '/' {
            if let Some((node, end)) = try_parse_element(chars, pos) {
                children.push(node);
                pos = end;
                continue;
            }
        }

        // Text content
        let text_start = pos;
        while pos < chars.len()
            && chars[pos] != '<'
            && chars[pos] != '{'
            && !starts_with_at(chars, pos, &close_tag)
        {
            pos += 1;
        }
        if pos > text_start {
            let text: String = chars[text_start..pos].iter().collect();
            let text = text.trim();
            if !text.is_empty() {
                children.push(HtmlExpr::Text(text.to_string()));
            }
        }
    }

    // If we never found the close tag, return what we have
    (children, pos)
}

/// Parse a single HTML attribute (handles static, dynamic, bind:, on:, spread).
fn parse_attr(chars: &[char], pos: usize) -> Option<(HtmlAttr, usize)> {
    let mut i = pos;

    // Spread: {...expr}
    if i < chars.len() && chars[i] == '{' && i + 3 < chars.len() && chars[i + 1] == '.' && chars[i + 2] == '.' && chars[i + 3] == '.' {
        let end = find_matching_brace(chars, i)?;
        let expr: String = chars[i + 4..end].iter().collect();
        return Some((
            HtmlAttr {
                name: String::new(),
                value: HtmlAttrValue::Spread(expr.trim().to_string()),
            },
            end + 1,
        ));
    }

    // Shorthand: {name} (same as name={name})
    if i < chars.len() && chars[i] == '{' {
        let end = find_matching_brace(chars, i)?;
        let expr: String = chars[i + 1..end].iter().collect();
        let expr = expr.trim().to_string();
        return Some((
            HtmlAttr {
                name: expr.clone(),
                value: HtmlAttrValue::Dynamic(expr),
            },
            end + 1,
        ));
    }

    // Read attribute name
    let name_start = i;
    while i < chars.len()
        && (chars[i].is_alphanumeric() || chars[i] == '-' || chars[i] == '_' || chars[i] == ':' || chars[i] == '.')
    {
        i += 1;
    }
    if i == name_start {
        return None;
    }
    let name: String = chars[name_start..i].iter().collect();

    // Boolean attribute (no value)
    if i >= chars.len() || chars[i] != '=' {
        // Handle bind:value shorthand (no =)
        if name.starts_with("bind:") {
            let prop = name.strip_prefix("bind:").unwrap().to_string();
            return Some((
                HtmlAttr { name: String::new(), value: HtmlAttrValue::Bind(prop) },
                i,
            ));
        }
        return Some((
            HtmlAttr { name, value: HtmlAttrValue::Boolean },
            i,
        ));
    }

    // Skip '='
    i += 1;

    // Handle different value forms
    if i >= chars.len() {
        return Some((HtmlAttr { name, value: HtmlAttrValue::Boolean }, i));
    }

    // Dynamic value: name={expr}
    if chars[i] == '{' {
        let end = find_matching_brace(chars, i)?;
        let expr: String = chars[i + 1..end].iter().collect();

        // Check for on:event or bind:prop
        if name.starts_with("on:") {
            let event = name.strip_prefix("on:").unwrap_or(&name);
            return Some((
                HtmlAttr {
                    name: String::new(),
                    value: HtmlAttrValue::Event(event.to_string(), expr.trim().to_string()),
                },
                end + 1,
            ));
        }
        if name.starts_with("bind:") {
            let prop = name.strip_prefix("bind:").unwrap().to_string();
            return Some((
                HtmlAttr { name: String::new(), value: HtmlAttrValue::Bind(prop) },
                end + 1,
            ));
        }

        return Some((
            HtmlAttr {
                name,
                value: HtmlAttrValue::Dynamic(expr.trim().to_string()),
            },
            end + 1,
        ));
    }

    // Static value: name="value" or name='value'
    if chars[i] == '"' || chars[i] == '\'' {
        let quote = chars[i];
        i += 1;
        let val_start = i;
        while i < chars.len() && chars[i] != quote {
            i += 1;
        }
        let val: String = chars[val_start..i].iter().collect();
        if i < chars.len() {
            i += 1; // skip closing quote
        }

        // Handle on:event with static values
        if name.starts_with("on:") {
            let event = name.strip_prefix("on:").unwrap_or(&name);
            return Some((
                HtmlAttr {
                    name: String::new(),
                    value: HtmlAttrValue::Event(event.to_string(), val),
                },
                i,
            ));
        }

        return Some((
            HtmlAttr { name, value: HtmlAttrValue::Static(val) },
            i,
        ));
    }

    // Bare value (unusual but possible)
    let val_start = i;
    while i < chars.len() && !chars[i].is_whitespace() && chars[i] != '>' && chars[i] != '/' {
        i += 1;
    }
    let val: String = chars[val_start..i].iter().collect();
    Some((
        HtmlAttr { name, value: HtmlAttrValue::Static(val) },
        i,
    ))
}

// ─── Style Section ───────────────────────────────────────────────────────────

/// Generate the `<style>` section by parsing CSS into CssExpr nodes.
///
/// Handles common patterns:
/// - Simple rules: `.card { padding: 1rem; }`
/// - Custom properties: `--color: #fff;`
/// - Media queries: `@media (...) { ... }`
/// - @keyframes
///
/// Complex or unrecognized patterns pass through as `CssExpr::Raw`.
fn generate_style_section(comp: &Construct) -> String {
    let style_content = get_raw_block(comp, "style");

    let content = if style_content.is_empty() {
        // Fallback: check fns named "style" (old pattern)
        get_fn_string_body(comp, "style")
    } else {
        style_content
    };

    if content.is_empty() {
        return "  /* TODO: Add component styles */\n".to_string();
    }

    let nodes = parse_css_to_exprs(&content);
    if nodes.is_empty() {
        return format!("  {}\n", content.trim());
    }

    let emitted = emit_css_nodes(&nodes, 1);
    format!("{}\n", emitted)
}

/// Parse CSS text into CssExpr nodes.
///
/// Best-effort mini-parser. Handles:
/// - Standard rules: `selector { declarations }`
/// - @media queries
/// - @keyframes
/// - @import
/// - Custom properties at :root level
///
/// Unrecognized patterns become `CssExpr::Raw`.
pub fn parse_css_to_exprs(input: &str) -> Vec<CssExpr> {
    let input = input.trim();
    if input.is_empty() {
        return vec![];
    }

    let mut nodes = Vec::new();
    let mut pos = 0;
    let chars: Vec<char> = input.chars().collect();

    while pos < chars.len() {
        // Skip whitespace
        while pos < chars.len() && chars[pos].is_whitespace() {
            pos += 1;
        }
        if pos >= chars.len() {
            break;
        }

        // @import
        if starts_with_at(&chars, pos, "@import") {
            if let Some(end) = find_char(&chars, pos, ';') {
                let line: String = chars[pos..end + 1].iter().collect();
                let path = line
                    .trim_start_matches("@import")
                    .trim()
                    .trim_matches(|c| c == '"' || c == '\'' || c == ';')
                    .trim()
                    .to_string();
                nodes.push(CssExpr::Import(path));
                pos = end + 1;
                continue;
            }
        }

        // @media
        if starts_with_at(&chars, pos, "@media") {
            if let Some((node, end)) = parse_media_query(&chars, pos) {
                nodes.push(node);
                pos = end;
                continue;
            }
        }

        // @keyframes
        if starts_with_at(&chars, pos, "@keyframes") {
            if let Some((node, end)) = parse_keyframes(&chars, pos) {
                nodes.push(node);
                pos = end;
                continue;
            }
        }

        // Regular rule: selector { declarations }
        if let Some((node, end)) = parse_css_rule(&chars, pos) {
            nodes.push(node);
            pos = end;
            continue;
        }

        // Fallback: collect line as raw
        let line_start = pos;
        while pos < chars.len() && chars[pos] != '\n' {
            pos += 1;
        }
        let line: String = chars[line_start..pos].iter().collect();
        let line = line.trim();
        if !line.is_empty() {
            nodes.push(CssExpr::Raw(line.to_string()));
        }
        if pos < chars.len() {
            pos += 1;
        }
    }

    nodes
}

fn parse_css_rule(chars: &[char], pos: usize) -> Option<(CssExpr, usize)> {
    // Find the opening brace
    let brace_pos = find_char(chars, pos, '{')?;

    // Selector is everything before the brace
    let selector: String = chars[pos..brace_pos].iter().collect();
    let selector = selector.trim().to_string();
    if selector.is_empty() {
        return None;
    }

    // Find matching closing brace
    let close_pos = find_matching_css_brace(chars, brace_pos)?;
    let body: String = chars[brace_pos + 1..close_pos].iter().collect();

    // Check if body contains nested rules (has { in it)
    if body.contains('{') {
        // Nested rules — parse as Nest
        let children = parse_css_to_exprs(&body);
        return Some((
            CssExpr::Nest { parent: selector, children },
            close_pos + 1,
        ));
    }

    // Parse declarations
    let declarations = parse_declarations(&body);

    Some((
        CssExpr::Rule { selector, declarations },
        close_pos + 1,
    ))
}

fn parse_media_query(chars: &[char], pos: usize) -> Option<(CssExpr, usize)> {
    let brace_pos = find_char(chars, pos, '{')?;
    let header: String = chars[pos..brace_pos].iter().collect();
    let condition = header
        .trim_start_matches("@media")
        .trim()
        .to_string();

    let close_pos = find_matching_css_brace(chars, brace_pos)?;
    let body: String = chars[brace_pos + 1..close_pos].iter().collect();

    let rules = parse_css_to_exprs(&body);

    Some((
        CssExpr::MediaQuery { condition, rules },
        close_pos + 1,
    ))
}

fn parse_keyframes(chars: &[char], pos: usize) -> Option<(CssExpr, usize)> {
    let brace_pos = find_char(chars, pos, '{')?;
    let header: String = chars[pos..brace_pos].iter().collect();
    let name = header
        .trim_start_matches("@keyframes")
        .trim()
        .to_string();

    let close_pos = find_matching_css_brace(chars, brace_pos)?;
    let body: String = chars[brace_pos + 1..close_pos].iter().collect();

    // Parse keyframe steps (e.g. "from { ... }" "to { ... }" "50% { ... }")
    let step_rules = parse_css_to_exprs(&body);
    let steps: Vec<(String, Vec<CssDeclaration>)> = step_rules
        .into_iter()
        .filter_map(|rule| {
            if let CssExpr::Rule { selector, declarations } = rule {
                Some((selector, declarations))
            } else {
                None
            }
        })
        .collect();

    Some((
        CssExpr::Keyframes { name, steps },
        close_pos + 1,
    ))
}

fn parse_declarations(body: &str) -> Vec<CssDeclaration> {
    let mut declarations = Vec::new();
    for part in body.split(';') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Some((prop, val)) = part.split_once(':') {
            declarations.push(CssDeclaration {
                property: prop.trim().to_string(),
                value: val.trim().to_string(),
            });
        }
    }
    declarations
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Get a named raw_block from a construct.
fn get_raw_block(comp: &Construct, name: &str) -> String {
    comp.raw_blocks
        .iter()
        .find(|(n, _)| n == name)
        .map(|(_, content)| content.clone())
        .unwrap_or_default()
}

/// Fallback: get string body from a fn named `name` (old pattern).
fn get_fn_string_body(comp: &Construct, name: &str) -> String {
    comp.fns
        .iter()
        .find(|f| f.name == name)
        .and_then(|f| {
            f.body.first().and_then(|expr| match expr {
                Expr::StringLit(s) => Some(s.clone()),
                Expr::Return(inner) => {
                    if let Expr::StringLit(s) = inner.as_ref() {
                        Some(s.clone())
                    } else {
                        None
                    }
                }
                _ => None,
            })
        })
        .unwrap_or_default()
}

/// Detect PascalCase component references in template text for auto-imports.
fn detect_component_imports(template: &str, self_name: &str) -> Vec<String> {
    let mut imports = Vec::new();
    let chars: Vec<char> = template.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '<' && i + 1 < chars.len() && chars[i + 1].is_uppercase() {
            i += 1;
            let mut comp_name = String::new();
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') {
                comp_name.push(chars[i]);
                i += 1;
            }
            if !comp_name.is_empty() && comp_name != self_name && !imports.contains(&comp_name) {
                imports.push(comp_name);
            }
        } else {
            i += 1;
        }
    }
    imports
}

/// Build props destructuring bindings string from fields and reactivity policy.
fn build_props_bindings(fields: &[veil_ir::ast::Field], pol: &ReactivityPolicy) -> String {
    fields
        .iter()
        .map(|field| {
            let is_bind = field
                .annotations
                .iter()
                .any(|a| a.name == "bind" || a.name == "bindable");

            if let Some(expr) = &field.default_expr {
                if is_bind && !pol.bindable.is_empty() {
                    let def = expr_to_ts(expr, 1);
                    let bind_expr = if def == "undefined" || def.is_empty() {
                        pol.bindable.clone()
                    } else {
                        ReactivityPolicy::fill(
                            &pol.bindable_default,
                            &[("default", def.as_str())],
                        )
                    };
                    format!("{} = {}", field.name, bind_expr)
                } else {
                    format!("{} = {}", field.name, expr_to_ts(expr, 1))
                }
            } else if is_bind && !pol.bindable.is_empty() {
                format!("{} = {}", field.name, pol.bindable)
            } else {
                field.name.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Get a default value for a TypeScript type.
fn default_value_for_ts(ty: &str) -> &str {
    match ty {
        "boolean" => "false",
        "number" => "0",
        "string" => "''",
        _ if ty.ends_with("[]") => "[]",
        _ if ty.ends_with("| null") => "null",
        _ => "undefined as any",
    }
}

/// Check if an effect body contains async operations.
fn effect_body_needs_await(body: &[Expr]) -> bool {
    body.iter().any(|expr| expr_needs_await(expr))
}

fn expr_needs_await(expr: &Expr) -> bool {
    match expr {
        Expr::Await(_) | Expr::Try(_) => true,
        Expr::Call(_) => false, // Can't know without context
        Expr::Assign(_, rhs, _) | Expr::MutAssign(_, rhs, _) => expr_needs_await(rhs),
        Expr::IfExpr(data) => {
            data.then_body.iter().any(|e| expr_needs_await(e))
                || data.else_body.as_ref().map_or(false, |b| b.iter().any(|e| expr_needs_await(e)))
        }
        Expr::Return(inner) => expr_needs_await(inner),
        _ => false,
    }
}

/// Emit an expression as async TypeScript (wraps await where needed).
fn expr_to_ts_async(expr: &Expr, indent: usize) -> String {
    // Delegate to the existing async emission path
    crate::typescript::expr_to_ts_async(expr, indent)
}

/// Convert component HtmlAttrs to prop tuples for HtmlExpr::Component.
fn attrs_to_component_props(attrs: &[HtmlAttr]) -> Vec<(String, String)> {
    attrs
        .iter()
        .filter_map(|attr| match &attr.value {
            HtmlAttrValue::Static(val) => Some((attr.name.clone(), format!("\"{}\"", val))),
            HtmlAttrValue::Dynamic(expr) => Some((attr.name.clone(), expr.clone())),
            HtmlAttrValue::Bind(prop) => Some((format!("bind:{}", prop), prop.clone())),
            HtmlAttrValue::Event(event, handler) => {
                Some((format!("on:{}", event), handler.clone()))
            }
            HtmlAttrValue::Spread(expr) => Some(("...".to_string(), expr.clone())),
            HtmlAttrValue::Boolean => Some((attr.name.clone(), "true".to_string())),
        })
        .collect()
}

/// Remove common leading indentation from a multi-line string block.
fn dedent_block(s: &str) -> String {
    let lines: Vec<&str> = s.lines().collect();
    if lines.is_empty() {
        return String::new();
    }
    let min_indent = lines
        .iter()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);
    lines
        .iter()
        .map(|l| {
            if l.len() > min_indent {
                &l[min_indent..]
            } else {
                l.trim()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

// ─── Parsing Utilities ───────────────────────────────────────────────────────

/// Check if chars at `pos` starts with a given string.
fn starts_with_at(chars: &[char], pos: usize, s: &str) -> bool {
    let s_chars: Vec<char> = s.chars().collect();
    if pos + s_chars.len() > chars.len() {
        return false;
    }
    for (i, c) in s_chars.iter().enumerate() {
        if chars[pos + i] != *c {
            return false;
        }
    }
    true
}

/// Find a character starting from `pos`.
fn find_char(chars: &[char], start: usize, ch: char) -> Option<usize> {
    for i in start..chars.len() {
        if chars[i] == ch {
            return Some(i);
        }
    }
    None
}

/// Find a substring starting from `pos`.
fn find_str(chars: &[char], start: usize, s: &str) -> Option<usize> {
    let s_chars: Vec<char> = s.chars().collect();
    if s_chars.is_empty() {
        return Some(start);
    }
    for i in start..chars.len() {
        if starts_with_at(chars, i, s) {
            return Some(i);
        }
    }
    None
}

/// Find matching closing brace `}` for an opening brace at `pos`, respecting nesting.
fn find_matching_brace(chars: &[char], pos: usize) -> Option<usize> {
    if pos >= chars.len() || chars[pos] != '{' {
        return None;
    }
    let mut depth = 0;
    for i in pos..chars.len() {
        match chars[i] {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// Find matching closing brace for CSS (handles nested rules).
fn find_matching_css_brace(chars: &[char], pos: usize) -> Option<usize> {
    find_matching_brace(chars, pos)
}

/// Find a block end tag (e.g. `{/each}`, `{/if}`).
fn find_block_end(chars: &[char], start: usize, end_tag: &str) -> Option<usize> {
    // We need to respect nesting of the same block type
    let open_prefix = if end_tag.starts_with("{/") {
        let keyword = end_tag.trim_start_matches("{/").trim_end_matches('}');
        format!("{{#{}", keyword)
    } else {
        return find_str(chars, start, end_tag);
    };

    let mut depth = 1;
    let mut pos = start;
    while pos < chars.len() {
        if starts_with_at(chars, pos, &open_prefix) {
            depth += 1;
            pos += open_prefix.len();
        } else if starts_with_at(chars, pos, end_tag) {
            depth -= 1;
            if depth == 0 {
                return Some(pos);
            }
            pos += end_tag.len();
        } else {
            pos += 1;
        }
    }
    None
}

/// Split an if block body into then/else parts, finding `{:else}` and `{/if}`.
fn split_if_else(chars: &[char], start: usize) -> Option<(String, String, usize)> {
    let mut depth = 1;
    let mut pos = start;
    let mut else_pos = None;

    while pos < chars.len() {
        if starts_with_at(chars, pos, "{#if") {
            depth += 1;
            pos += 4;
        } else if starts_with_at(chars, pos, "{/if}") {
            depth -= 1;
            if depth == 0 {
                let end_pos = pos + 5;
                let then_end = else_pos.unwrap_or(pos);
                let then_content: String = chars[start..then_end].iter().collect();
                let else_content = if let Some(ep) = else_pos {
                    let else_start = ep + 7; // after "{:else}"
                    chars[else_start..pos].iter().collect::<String>()
                } else {
                    String::new()
                };
                return Some((then_content, else_content, end_pos));
            }
            pos += 5;
        } else if starts_with_at(chars, pos, "{:else}") && depth == 1 {
            else_pos = Some(pos);
            pos += 7;
        } else if starts_with_at(chars, pos, "{:else if ") && depth == 1 {
            // Treat {:else if ...} as the else branch start
            else_pos = Some(pos);
            pos += 1;
        } else {
            pos += 1;
        }
    }

    None
}

/// Parse inline content (text mixed with interpolations and elements) into HtmlExpr nodes.
fn parse_inline_content(input: &str) -> Vec<HtmlExpr> {
    parse_template_to_html_exprs(input)
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests;
