//! Dedicated executor provisioning — the *dedicated* half of the execution
//! topology.
//!
//! When a project chooses `mode = "dedicated"` in `veil.toml [execution]`, its
//! deploy provisions a project-scoped ECS service `veil-<slug>-executor` on the
//! shared `veil-cluster`, running the SAME `veil-runtime` image in the SAME
//! `VEIL_ROLE=execution-host` run-mode — but scoped to host ONLY this project's
//! artifact(s) and with its own autoscaling policy from `[execution.dedicated]`.
//!
//! There is **no forked executor codebase**. The scoped executor is the shared
//! engine with three differences, expressed purely as terraform inputs:
//!   1. **which artifacts it hosts** — `VEIL_EXEC_ARTIFACT_SCOPE=<slug>` tells
//!      the run-mode to serve only this project's artifact set;
//!   2. **service identity** — `name_prefix = "veil-<slug>-exec"` /
//!      `service = veil-<slug>-executor`;
//!   3. **scaling policy** — cpu/memory/min/max/target from the project sizing.
//!
//! This module emits the terraform for that service by rendering a template with
//! the project's [`DedicatedSizing`]. The output is written under the host's OWN
//! infra tree (NOT a customer project) and planned/applied by the deploy
//! pipeline's terraform step. `terraform apply` is gated on human confirmation
//! (medium-high risk: a new ECS service, IAM, ALB).

use crate::execution_topology::{dedicated_service_name, DedicatedSizing};

/// Inputs to render a dedicated executor terraform config.
#[derive(Debug, Clone)]
pub struct DedicatedExecutorPlan {
    /// Project slug — names `veil-<slug>-executor` and scopes the artifact set.
    pub slug: String,
    /// Sizing + scaling from `[execution.dedicated]`.
    pub sizing: DedicatedSizing,
}

impl DedicatedExecutorPlan {
    pub fn new(slug: impl Into<String>, sizing: DedicatedSizing) -> Self {
        Self {
            slug: slug.into(),
            sizing,
        }
    }

    /// The ECS service name (`veil-<slug>-executor`).
    pub fn service_name(&self) -> String {
        dedicated_service_name(&self.slug)
    }

    /// The terraform `name_prefix` for the scoped service's resources. Keeps
    /// IAM/log/target-group names distinct from the shared host + ProductHost.
    /// (`veil-<slug>-exec`; the module appends `-<env>` and per-resource suffixes.)
    pub fn name_prefix(&self) -> String {
        format!("veil-{}-exec", self.slug)
    }

    /// The terraform state key for this dedicated executor (under the host infra
    /// tree, one key per project slug).
    pub fn state_key(&self) -> String {
        format!("dlx-core/veil-dedicated-executors/{}", self.slug)
    }

    /// Render the full terraform config (`main.tf`) for this dedicated executor.
    ///
    /// The config mirrors `locations/services/veil-execution-host/main.tf` but:
    ///   • distinct backend state key + name_prefix (per-slug),
    ///   • `VEIL_EXEC_ARTIFACT_SCOPE = <slug>` so the run-mode hosts only this
    ///     project's artifact(s),
    ///   • sizing/scaling from `[execution.dedicated]`,
    ///   • its own internal ALB hostname `<slug>.exec.veil.<zone>` so triggers
    ///     route here (the routing resolver's dedicated_base_template resolves to
    ///     this service).
    pub fn render_terraform(&self) -> String {
        let slug = &self.slug;
        let service = self.service_name();
        let name_prefix = self.name_prefix();
        let state_key = self.state_key();
        let s = &self.sizing;

        format!(
            r#"# VEIL Dedicated Executor — {service}
#
# GENERATED by veil-runtime (execution_topology). DO NOT hand-edit.
#
# A project-scoped executor: the SAME veil-runtime image in the SAME
# VEIL_ROLE=execution-host run-mode as the shared VEIL Execution Host, but
# scoped (VEIL_EXEC_ARTIFACT_SCOPE={slug}) to host ONLY this project's
# artifact(s), with its own autoscaling policy. ONE engine, two topologies —
# see mind-palace `veil-execution-host-design` (topology section).
#
# ─────────────────────────────────────────────────────────────────────────────
# AUTHOR-ONLY — DO NOT `terraform apply` WITHOUT JD CONFIRMATION.
# Medium-high risk: new ECS service on the shared veil-cluster, IAM roles, ALB.
# ─────────────────────────────────────────────────────────────────────────────

terraform {{
  required_version = ">= 1.5"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}

  backend "s3" {{
    bucket         = "dashlx-terraform-state"
    key            = "{state_key}"
    region         = "us-west-2"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    profile        = "dashlx_prod"
  }}
}}

provider "aws" {{
  region  = "us-west-2"
  profile = "dashlx_${{terraform.workspace}}"

  default_tags {{
    tags = {{
      Project     = "dlx-core"
      Service     = "{service}"
      Environment = terraform.workspace
      ManagedBy   = "terraform"
    }}
  }}
}}

variable "image_tag" {{
  description = "Docker image tag to deploy (same image as veil-runtime-ecs)"
  type        = string
  default     = "latest"
}}

variable "toolchain_fingerprint" {{
  description = <<-EOT
    Optional exact toolchain fingerprint "{{rustc_version}}/{{target_triple}}"
    this dedicated executor enforces on artifact load. A dedicated executor MAY
    pin a DIFFERENT toolchain than the shared host (that is one reason to go
    dedicated), but it must be internally consistent with ITS artifact.
  EOT
  type        = string
  default     = ""
}}

data "terraform_remote_state" "network" {{
  backend = "s3"
  config = {{
    bucket  = "dashlx-terraform-state"
    key     = "env:/${{terraform.workspace}}/us-west-2/network"
    region  = "us-west-2"
    profile = "dashlx_prod"
  }}
}}

data "terraform_remote_state" "veil_services" {{
  backend = "s3"
  config = {{
    bucket  = "dashlx-terraform-state"
    key     = "dlx-core/veil-services"
    region  = "us-west-2"
    profile = "dashlx_prod"
  }}
  workspace = terraform.workspace
}}

data "terraform_remote_state" "veil_runtime_ecs" {{
  backend = "s3"
  config = {{
    bucket  = "dashlx-terraform-state"
    key     = "dlx-core/veil-runtime-ecs"
    region  = "us-west-2"
    profile = "dashlx_prod"
  }}
  workspace = terraform.workspace
}}

data "aws_route53_zone" "this" {{
  name = terraform.workspace == "prod" ? "dashlx.com" : "dev.dashlx.com"
}}

data "aws_vpc" "this" {{
  id = data.terraform_remote_state.network.outputs.vpc_id
}}

module "veil_dedicated_executor" {{
  source = "../../../modules/veil-runtime"

  # Per-slug prefix so this executor's IAM/log/TG/SG names never collide with
  # the shared host or ProductHost.
  name_prefix = "{name_prefix}"

  # Name the ECS service EXACTLY what routing + identity advertise
  # (veil-<slug>-executor), so the real resource name == the logical name the
  # host's RoutingContext resolves (self_service / dedicated DNS host).
  service_name = "{service}"

  environment = terraform.workspace
  vpc_id      = data.terraform_remote_state.network.outputs.vpc_id
  subnet_ids  = slice(data.terraform_remote_state.network.outputs.private_subnets, 0, 3)

  # Shared veil-cluster (a dedicated executor is a different SERVICE, not a
  # different cluster — same substrate).
  create_cluster = false
  cluster_arn    = data.terraform_remote_state.veil_services.outputs.cluster_arn

  # INTERNAL ALB: a dedicated executor is still an internal control-plane
  # surface (register / invoke / fire), reachable within the VPC only.
  alb_internal      = true
  alb_ingress_cidrs = [data.aws_vpc.this.cidr_block]

  # Per-slug internal hostname so the trigger-fire routing resolver targets THIS
  # executor: dedicated_base_template resolves {{service}} → {service}.
  domain_name    = "{service}.veil.${{data.aws_route53_zone.this.name}}"
  hosted_zone_id = data.aws_route53_zone.this.zone_id

  # SAME image as the shared host/ProductHost — run-mode differs by env only.
  create_ecr         = false
  ecr_repository_url = data.terraform_remote_state.veil_runtime_ecs.outputs.ecr_repository_url
  image_tag          = var.image_tag

  # Reuse existing DashLX storage — artifacts share the S3 bucket; the trigger
  # table shares the applications single-table (TRIGGER# PK space).
  create_s3_bucket = false
  s3_bucket_name   = "veil-runtime-${{terraform.workspace}}"

  create_ddb_table = false
  ddb_table_name   = "veil-runtime-${{terraform.workspace}}"

  runtime_port = 8090

  extra_environment = merge(
    {{
      # SAME execution-host run-mode as the shared host.
      VEIL_ROLE = "execution-host"
      # SCOPE: this executor hosts ONLY project '{slug}'s artifact(s). This is
      # the one behavioural difference from the shared host — same engine.
      VEIL_EXEC_ARTIFACT_SCOPE = "{slug}"
      VEIL_FFI_MAX_CONCURRENCY = "64"
      # A dedicated executor typically hosts a small hot artifact set, so a
      # smaller resident cdylib cache than the shared host is fine.
      VEIL_FFI_CACHE_CAPACITY = "16"
      VEIL_FFI_CACHE_DIR      = "/tmp/veil-ffi-artifacts"
    }},
    var.toolchain_fingerprint != "" ? {{ VEIL_TOOLCHAIN_FINGERPRINT = var.toolchain_fingerprint }} : {{}}
  )

  # Sizing + scaling from veil.toml [execution.dedicated].
  task_cpu    = {cpu}
  task_memory = {memory}

  enable_autoscaling             = true
  autoscaling_min_capacity       = {min_tasks}
  autoscaling_max_capacity       = {max_tasks}
  autoscaling_cpu_target         = {target_cpu}
  # Memory tracking still matters for a dedicated executor (its own hot set).
  autoscaling_memory_target      = 80
  autoscaling_scale_in_cooldown  = 300
  autoscaling_scale_out_cooldown = 60

  log_retention_days = terraform.workspace == "prod" ? 30 : 7

  tags = {{
    Team    = "platform"
    Product = "veil"
    Role    = "dedicated-executor"
    Slug    = "{slug}"
  }}
}}

output "service_url" {{
  value = module.veil_dedicated_executor.service_url
}}

output "ecs_service_name" {{
  value = module.veil_dedicated_executor.ecs_service_name
}}

output "log_group" {{
  value = module.veil_dedicated_executor.log_group_name
}}
"#,
            service = service,
            slug = slug,
            name_prefix = name_prefix,
            state_key = state_key,
            cpu = s.cpu,
            memory = s.memory,
            min_tasks = s.min_tasks,
            max_tasks = s.max_tasks,
            target_cpu = s.autoscale_target_cpu,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn plan() -> DedicatedExecutorPlan {
        DedicatedExecutorPlan::new(
            "acme",
            DedicatedSizing {
                cpu: 1024,
                memory: 2048,
                min_tasks: 2,
                max_tasks: 8,
                autoscale_target_cpu: 55,
            },
        )
    }

    #[test]
    fn service_and_prefix_names_follow_convention() {
        let p = plan();
        assert_eq!(p.service_name(), "veil-acme-executor");
        assert_eq!(p.name_prefix(), "veil-acme-exec");
        assert_eq!(p.state_key(), "dlx-core/veil-dedicated-executors/acme");
    }

    #[test]
    fn terraform_scopes_artifacts_and_uses_sizing() {
        let tf = plan().render_terraform();
        // Scoped to this project's artifacts (the one behavioural difference).
        assert!(tf.contains("VEIL_EXEC_ARTIFACT_SCOPE = \"acme\""));
        // SAME run-mode / engine — no forked executor.
        assert!(tf.contains("VEIL_ROLE = \"execution-host\""));
        // SAME image source as the shared host.
        assert!(tf.contains("ecr_repository_url = data.terraform_remote_state.veil_runtime_ecs.outputs.ecr_repository_url"));
        // Sizing threaded from [execution.dedicated].
        assert!(tf.contains("task_cpu    = 1024"));
        assert!(tf.contains("task_memory = 2048"));
        assert!(tf.contains("autoscaling_min_capacity       = 2"));
        assert!(tf.contains("autoscaling_max_capacity       = 8"));
        assert!(tf.contains("autoscaling_cpu_target         = 55"));
        // Autoscaling required (a reason to go dedicated is a hot artifact).
        assert!(tf.contains("enable_autoscaling             = true"));
        // Reuses the shared cluster (different SERVICE, same substrate).
        assert!(tf.contains("create_cluster = false"));
        // Names the service veil-<slug>-executor for routing + identity.
        assert!(tf.contains("veil-acme-executor.veil."));
        assert!(tf.contains("name_prefix = \"veil-acme-exec\""));
        // The ECS service is named EXACTLY what routing/identity advertise, so
        // the real resource name equals veil-<slug>-executor (audit finding #1).
        assert!(tf.contains("service_name = \"veil-acme-executor\""));
    }

    #[test]
    fn terraform_backend_key_is_per_slug() {
        let tf = plan().render_terraform();
        assert!(tf.contains("key            = \"dlx-core/veil-dedicated-executors/acme\""));
    }

    #[test]
    fn terraform_notes_toolchain_may_diverge() {
        // A dedicated executor MAY pin a different toolchain than the shared host.
        let tf = plan().render_terraform();
        assert!(tf.contains("MAY\n    pin a DIFFERENT toolchain") || tf.contains("DIFFERENT toolchain"));
    }

    /// Emit the rendered terraform to `VEIL_EMIT_DEDICATED_TF` (a file path) for
    /// out-of-band `terraform validate`. No-op unless the env var is set, so it
    /// stays inert in normal test runs.
    #[test]
    fn emit_terraform_when_requested() {
        if let Ok(path) = std::env::var("VEIL_EMIT_DEDICATED_TF") {
            std::fs::write(&path, plan().render_terraform()).expect("write tf");
        }
    }
}
