<script lang="ts">
  // Generated by VEIL

  import PageHeader from './PageHeader.svelte';

  let status: Record<string, unknown> = $state(undefined as any);
  let loading: boolean = $state(false);
  let error: string = $state('');
  let loaded: boolean = $state(false);
  let refresh_token: number = $state(0);

   $effect(() => { // load_status
  void (async () => {
        if (loaded === false) {
          loading = true;
          error = "";
          let resp = await (async () => { const __u = new URL("/api/agent/status", typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
          status = resp;
          loading = false;
          loaded = true;
        };
  })();
    });
    $effect(() => { // reload_on_refresh
      if (refresh_token > 0) {
        loaded = false;
      };
    });
</script>

<div class="agents">
  <PageHeader title="Agents" description="Runtime agent configuration and connection status." />
  {#if loading && !status}
    <div class="panel card"><p class="loading">Loading…</p></div>
  {:else if error}
    <div class="panel card"><p class="dk-error">{error}</p></div>
  {:else if status}
    <section class="panel card">
      <div class="section-head">
        <h3 class="section-title">LLM Provider</h3>
        <button type="button" class="btn-ghost btn-sm" onclick={() => { refresh_token = refresh_token + 1; }}>Refresh</button>
      </div>
      <div class="provider-row">
        <div class="provider-badge">
          <span class="provider-dot"></span>
          <span class="provider-name">{status.provider}</span>
        </div>
        <span class="provider-mode">{status.provider_mode?.mode ?? ''}</span>
        {#if status.provider_mode?.model}
          <span class="provider-model">{status.provider_mode.model}</span>
        {/if}
      </div>
      <p class="hint">Set <code>VEIL_MODEL_PROVIDER</code> to switch: <code>acp</code>, <code>openai</code>, <code>ollama</code>.</p>
    </section>
    <section class="panel card">
      <h3 class="section-title">ACP / local agent</h3>
      <div class="tunnel-status">
        <div class="status-indicator" class:connected={status.acp_tunnel?.connected} class:disconnected={!status.acp_tunnel?.connected}>
          <span class="status-dot"></span>
          <span class="status-text">{status.acp_tunnel?.connected ? 'Connected' : 'Not connected'}</span>
        </div>
        {#if status.acp_tunnel?.connected && status.acp_tunnel?.agents?.length > 0}
          <div class="agents-list">
            {#each status.acp_tunnel.agents as agent}
              <div class="agent-entry"><span class="agent-name">{agent.agent_name}</span> <span class="agent-user">({agent.user_id})</span></div>
            {/each}
          </div>
        {/if}
      </div>
      {#if !status.acp_tunnel?.connected}
        <div class="connect-box">
          <p>Local ACP (Kiro) is the default for ProductHost:</p>
          <code class="cmd-block">VEIL_MODEL_PROVIDER=acp  VEIL_ACP_COMMAND=kiro-cli</code>
          <p class="hint">Shell agent chat uses <code>/api/agent/chat</code> on the same host. Dashboard agent dock is always available (Cmd+K).</p>
        </div>
      {/if}
    </section>
  {/if}
</div>


<style>
.agents { max-width: 52rem; animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both; }
.panel { padding: 1.25rem; display: flex; flex-direction: column; gap: 0.75rem; }
.section-head { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; }
.section-title { font-size: 0.85rem; font-weight: 700; color: var(--dk-text, #e5e5e5); margin: 0; }
.btn-sm { font-size: 0.75rem; padding: 0.25rem 0.55rem; }
.loading { color: var(--dk-text-muted, #9ca3af); font-size: 0.85rem; }
.provider-row { display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap; }
.provider-badge { display: flex; align-items: center; gap: 0.4rem; padding: 0.35rem 0.75rem; border-radius: 999px; background: color-mix(in srgb, var(--accent, #737373) 12%, transparent); border: 1px solid color-mix(in srgb, var(--accent, #737373) 35%, transparent); }
.provider-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--accent, #a3a3a3); }
.provider-name { font-weight: 600; font-size: 0.8rem; color: var(--accent, #a3a3a3); }
.provider-mode { font-size: 0.75rem; color: var(--dk-text-muted, #9ca3af); text-transform: uppercase; letter-spacing: 0.05em; }
.provider-model { font-size: 0.7rem; color: var(--dk-text-muted, #9ca3af); font-family: monospace; }
.hint { font-size: 0.75rem; color: var(--dk-text-muted, #9ca3af); margin: 0; }
.hint code { background: var(--dk-surface-3, #2e2e2e); padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.7rem; }
.tunnel-status { display: flex; flex-direction: column; gap: 0.5rem; }
.status-indicator { display: flex; align-items: center; gap: 0.5rem; }
.status-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
.connected .status-dot { background: #34d399; box-shadow: 0 0 6px rgba(52, 211, 153, 0.5); animation: pulse 2s ease infinite; }
.disconnected .status-dot { background: var(--dk-text-muted, #6b7280); }
.status-text { font-size: 0.8rem; font-weight: 600; }
.connected .status-text { color: #34d399; }
.disconnected .status-text { color: var(--dk-text-muted, #9ca3af); }
.agents-list { display: flex; flex-direction: column; gap: 0.3rem; padding-left: 1.25rem; }
.agent-entry { font-size: 0.75rem; color: var(--dk-text, #e5e5e5); }
.agent-name { font-weight: 600; }
.agent-user { color: var(--dk-text-muted, #9ca3af); }
.connect-box { margin-top: 0.5rem; padding: 0.75rem; background: var(--dk-surface-2, #242424); border-radius: var(--dk-radius-sm, 0.55rem); border: 1px solid var(--dk-border-soft, rgba(46, 46, 46, 0.65)); }
.connect-box p { margin: 0 0 0.4rem; font-size: 0.8rem; color: var(--dk-text, #e5e5e5); }
.cmd-block { display: block; padding: 0.5rem 0.75rem; background: var(--dk-surface-3, #2e2e2e); border-radius: 4px; font-size: 0.8rem; color: var(--accent, #a3a3a3); margin-bottom: 0.4rem; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }

</style>
