<script lang="ts">
  // Generated by VEIL


  interface Props {
    open: boolean;
  }
  let { open }: Props = $props();

  let panel_width: number = $state(0);
  let is_resizing: boolean = $state(false);
  let messages: Any[] = $state([]);
  let is_streaming: boolean = $state(false);
  let is_thinking: boolean = $state(false);
  let pending_seed: string = $state('');

  // raw script block (escape hatch — prefer VEIL fn/effect)
  import { MessageList, ChatInput } from '@aether-ui/core';

</script>

{#if open}
  <aside class="agent-dock" style="width: {panel_width || 420}px" class:resizing={is_resizing} role="complementary" aria-label="AI Agent">
    <div class="resize-handle" role="separator" aria-orientation="vertical" on:mousedown={startResize}></div>
    <header class="dock-header">
      <div class="header-left">
        <span class="agent-icon">◆</span>
        <span class="agent-title">Agent</span>
        <span class="agent-hint">Aether · Runtime</span>
      </div>
      <div class="header-actions">
        <button class="btn-icon" title="Clear conversation" on:click={() => messages = []}>⟲</button>
        <button class="btn-icon" title="Close (Cmd+K)" on:click={() => { open = false }}>✕</button>
      </div>
    </header>
    <div class="message-area">
      {#if messages.length === 0}
        <div class="empty-state">
          <p class="empty-title">VEIL Runtime Agent</p>
          <p class="empty-hint">Ask me to edit code, manage changes, deploy projects, or navigate — I can control the entire veil platform. <kbd>Cmd+K</kbd> to toggle.</p>
          <div class="empty-examples">
            <button class="example-chip" on:click={() => pending_seed = 'Open the relay project in the IDE'}>Open relay in IDE</button>
            <button class="example-chip" on:click={() => pending_seed = 'Show me open change requests'}>Open changes</button>
            <button class="example-chip" on:click={() => pending_seed = 'Deploy wear-test to staging'}>Deploy to staging</button>
          </div>
        </div>
      {:else}
        <div class="msg-list">
          <MessageList messages={messages} isStreaming={is_streaming} isThinking={is_thinking} />
        </div>
      {/if}
    </div>
    <div class="input-area">
      <ChatInput onSend={(msg) => console.log(msg)} onAbort={() => is_streaming = false} isStreaming={is_streaming} placeholder="Ask the agent…" initialText={pending_seed} />
    </div>
  </aside>
{/if}


<style>
.agent-dock {
  position: fixed;
  top: 0;
  right: 0;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--dk-surface, #12121a);
  border-left: 1px solid var(--dk-border-soft, rgba(42, 42, 56, 0.55));
  z-index: 1000;
  box-shadow: -8px 0 32px rgba(0, 0, 0, 0.4);
  animation: slide-in 200ms var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
}
.agent-dock.resizing { user-select: none; transition: none; }
@keyframes slide-in {
  from { transform: translateX(100%); opacity: 0; }
  to { transform: translateX(0); opacity: 1; }
}
.resize-handle {
  position: absolute; left: -3px; top: 0; bottom: 0; width: 6px;
  cursor: col-resize; z-index: 10; transition: background 140ms ease;
}
.resize-handle:hover, .agent-dock.resizing .resize-handle { background: var(--dk-brand, #148770); }
.dock-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 0.6rem 0.85rem;
  border-bottom: 1px solid var(--dk-border-soft, rgba(42, 42, 56, 0.55));
  flex-shrink: 0;
  background: var(--dk-glass, rgba(18, 18, 26, 0.72));
  backdrop-filter: blur(12px);
}
.header-left { display: flex; align-items: center; gap: 0.5rem; }
.agent-icon { color: var(--dk-brand-light, #1fa88a); font-size: 0.9rem; }
.agent-title { font-weight: 700; font-size: 0.8rem; color: var(--dk-text, #f4f5f7); }
.agent-hint { color: var(--dk-text-muted, #9ca3af); font-size: 0.65rem; }
.header-actions { display: flex; align-items: center; gap: 0.4rem; }
.btn-icon {
  background: none; border: none; color: var(--dk-text-muted, #9ca3af);
  cursor: pointer; padding: 0.25rem 0.4rem; border-radius: 4px; font-size: 0.8rem;
  transition: color 140ms ease, background 140ms ease;
}
.btn-icon:hover { color: var(--dk-text, #f4f5f7); background: rgba(255, 255, 255, 0.06); }
.message-area { flex: 1; min-height: 0; overflow-y: auto; display: flex; flex-direction: column; }
.msg-list { flex: 1; min-height: 0; display: flex; flex-direction: column; }
.empty-state { padding: 1.5rem 1.25rem; display: flex; flex-direction: column; gap: 0.75rem; }
.empty-title { font-weight: 700; font-size: 0.95rem; color: var(--dk-text, #f4f5f7); margin: 0; }
.empty-hint { color: var(--dk-text-muted, #9ca3af); font-size: 0.8rem; line-height: 1.5; margin: 0; }
.empty-hint kbd {
  background: var(--dk-surface-3, #22222f); border: 1px solid var(--dk-border, #2a2a38);
  padding: 0.1rem 0.35rem; border-radius: 4px; font-family: var(--dk-font, inherit); font-size: 0.7rem;
}
.empty-examples { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-top: 0.25rem; }
.example-chip {
  background: var(--dk-surface-2, #1a1a26);
  border: 1px solid var(--dk-border-soft, rgba(42, 42, 56, 0.55));
  color: var(--dk-text-muted, #9ca3af); font-size: 0.7rem;
  padding: 0.3rem 0.6rem; border-radius: 999px; cursor: pointer;
  transition: color 140ms ease, border-color 140ms ease, background 140ms ease;
  font-family: inherit;
}
.example-chip:hover {
  color: var(--dk-brand-light, #1fa88a);
  border-color: var(--dk-brand, #148770);
  background: rgba(20, 135, 112, 0.08);
}
.input-area {
  flex-shrink: 0;
  border-top: 1px solid var(--dk-border-soft, rgba(42, 42, 56, 0.55));
  padding: 0.5rem;
  background: var(--dk-glass, rgba(18, 18, 26, 0.72));
}

</style>
