<script lang="ts">
  // Generated by VEIL

  import CollectionView from './CollectionView.svelte';
  import StatusPill from './StatusPill.svelte';

  let change_requests: Record<string, unknown>[] = $state([]);
  let loading: boolean = $state(false);
  let error: string = $state('');
  let active_filter: string = $state('');
  let cr_href_tpl: string = $state("/changes/{id}");

   $effect(() => { // load_on_mount
  void (async () => {
        loading = true;
        error = "";
        active_filter = "All";
        change_requests = await (async () => { const __u = new URL("/api/change_requests", typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
        loading = false;
  })();
    });

  async function set_filter(filter: string) {
    active_filter = filter;
    loading = true;
    error = "";
    if (filter === "All") {
      change_requests = await (async () => { const __u = new URL("/api/change_requests", typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
    } else {
      change_requests = await (async () => { const __u = new URL(`/api/change_requests?status=${filter}`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
    };
    loading = false;
  }
</script>

<div class="changes">
  <CollectionView
    title="Changes"
    description="Change requests — branch-based review workflow"
    items={change_requests}
    loading={loading}
    error={error}
    view_mode="list"
    default_layout="list"
    layout_storage_key="veil_runtime.changes.layout"
    item_href_template={cr_href_tpl}
    show_avatar={false}
    primary_href="/changes/new"
    primary_label="Create"
    empty_title="No change requests"
    empty_description="Create a change request to start a branch-based review workflow."
    empty_action_href="/changes/new"
    empty_action_label="Create change request"
    columns={[
      { key: 'title', label: 'Title', cell: 'identity', showAvatar: false, subtitleKey: 'source_branch' },
      { key: 'status', label: 'Status' },
      { key: 'author', label: 'Author' },
      { key: 'jira_ticket', label: 'Ticket' },
      { key: 'updated_at', label: 'Updated' },
    ]}
    agent={{
      intent: 'list-change-requests',
      entity: 'ChangeRequest',
      entityLabel: 'Change Request',
      actions: [
        { id: 'create', label: 'Create', href: '/changes/new', via: 'primary', method: 'navigate' },
        { id: 'view', label: 'View', hrefTemplate: '/changes/{id}', via: 'item-click', method: 'navigate' },
      ],
      api: { list: 'GET /api/change_requests', get: 'GET /api/change_requests/{id}' },
    }}
  >
    {#snippet header_below()}
      <div class="cr-filters">
        {#each ['All', 'ReadyForReview', 'Approved', 'Draft', 'Merged'] as f}
          <button
            type="button"
            class="cr-filter-tab"
            class:cr-filter-tab--active={active_filter === f}
            onclick={() => { set_filter(f); }}
          >
            {f === 'ReadyForReview' ? 'Ready for Review' : f}
          </button>
        {/each}
      </div>
    {/snippet}
    {#snippet row(item)}
      {@const cr = /** @type {Record<string, unknown>} */ (item)}
      {@const crid = cr?.id != null && typeof cr.id === 'object' && cr.id.value != null ? String(cr.id.value) : String(cr?.id ?? '')}
      {@const status = String(cr?.status ?? 'Draft')}
      {@const statusVariant = status === 'Draft' ? 'neutral' : status === 'ReadyForReview' ? 'info' : status === 'Approved' ? 'success' : status === 'ChangesRequested' ? 'warning' : status === 'Merged' ? 'success' : status === 'Rejected' ? 'error' : 'neutral'}
      <td>
        <div class="cr-title-cell">
          <span class="cr-title">{cr?.title ? String(cr.title) : '—'}</span>
          <span class="cr-branch">{cr?.source_branch ? String(cr.source_branch) : ''}</span>
        </div>
      </td>
      <td>
        <StatusPill label={status === 'ReadyForReview' ? 'Ready for Review' : status} variant={statusVariant} />
      </td>
      <td><span class="dk-tile__meta">{cr?.author ? String(cr.author) : '—'}</span></td>
      <td><span class="dk-tile__meta">{cr?.jira_ticket ? String(cr.jira_ticket) : '—'}</span></td>
      <td><span class="dk-tile__meta">{cr?.updated_at ? String(cr.updated_at).slice(0, 10) : '—'}</span></td>
    {/snippet}
  </CollectionView>
</div>


<style>
.changes { max-width: 1120px; animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both; }
.cr-filters {
  display: flex;
  gap: 0.25rem;
  padding: 0.5rem 0 0.75rem;
  border-bottom: 1px solid var(--dk-border-soft, var(--border));
  margin-bottom: 0.5rem;
  flex-wrap: wrap;
}
.cr-filter-tab {
  font-size: 0.8rem;
  font-weight: 550;
  padding: 0.35rem 0.75rem;
  border-radius: 999px;
  border: 1px solid transparent;
  background: transparent;
  color: var(--text-dim);
  cursor: pointer;
  transition:
    color var(--dk-dur-fast, 140ms) ease,
    background var(--dk-dur-fast, 140ms) ease,
    border-color var(--dk-dur-fast, 140ms) ease;
}
.cr-filter-tab:hover {
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 8%, transparent);
}
.cr-filter-tab--active {
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 12%, transparent);
  border-color: color-mix(in srgb, var(--accent) 30%, transparent);
}
.cr-title-cell { display: flex; flex-direction: column; gap: 0.15rem; }
.cr-title { font-weight: 550; font-size: 0.88rem; }
.cr-branch { font-size: 0.75rem; color: var(--dk-text-muted); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }

</style>
