<script lang="ts">
  // Generated by VEIL

  import DetailShell from './DetailShell.svelte';
  import FormField from './FormField.svelte';

  let title: string = $state('');
  let description: string = $state('');
  let jira_ticket: string = $state('');
  let source_branch: string = $state('');
  let loading: boolean = $state(false);
  let error: string = $state('');

  async function handle_submit() {
    loading = true;
    error = "";
    await (async () => { const __r = await fetch("/api/change_requests", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, jira_ticket, source_branch, author: "jd" }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    "/changes";
  }
</script>

<DetailShell title="Create Change Request" back_href="/changes">
  <form class="form-body" on:submit|preventDefault={handle_submit}>
    {#if error}
      <div class="error-msg">{error}</div>
    {/if}
    <FormField label="Title" bind:value={title} placeholder="e.g. Add authorization to relay handlers" />
    <FormField label="Description" bind:value={description} placeholder="What does this change do?" />
    <FormField label="Jira Ticket" bind:value={jira_ticket} placeholder="e.g. VEIL-123" />
    <FormField label="Source Branch" bind:value={source_branch} placeholder="Auto-generated from title if empty" />
    <div class="actions">
      <a href="/changes" class="btn-ghost">Cancel</a>
      <button type="submit" class="btn-primary" disabled={loading || !title.trim()}>
        {#if loading}Creating…{:else}Create Change Request{/if}
      </button>
    </div>
  </form>
</DetailShell>


<style>
.form-body { display: flex; flex-direction: column; gap: 1.25rem; max-width: 600px; }
.error-msg {
  padding: 0.5rem 0.75rem;
  background: rgba(239, 68, 68, 0.12);
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: var(--dk-radius-sm, 0.55rem);
  color: #fecaca; font-size: 0.8rem;
}
.actions { display: flex; align-items: center; gap: 0.75rem; margin-top: 0.5rem; }

</style>
