<script lang="ts">
  // Generated by VEIL

  interface Props {
    items?: Record<string, unknown>[];
    align?: string;
    aria_label?: string;
    children?: Snippet | null;
    agent?: Record<string, unknown>;
  }
  let { items = [], align = "right", aria_label = "Actions", children, agent = {  } }: Props = $props();

  let open: boolean = $state(false);
  let root_el: Any = $state(undefined as any);
  let menu_el: Any = $state(undefined as any);

  let veil_agent = $derived({ version: 1, role: "context-menu", product: agent, runtime: { open } });

  function close() {
    open = false;
  }
  function open_menu() {
    open = true;
  }
  function toggle() {
    open = !open;
  }
</script>

{#if true}
{@const _portal = (() => {
  if (!open || !root_el || !menu_el || typeof document === 'undefined') return;
  const r = root_el.getBoundingClientRect();
  document.body.appendChild(menu_el);
  menu_el.style.position = 'fixed';
  menu_el.style.top = `${Math.round(r.bottom + 4)}px`;
  menu_el.style.zIndex = '10000';
  if (align === 'right') {
    menu_el.style.right = `${Math.round(window.innerWidth - r.right)}px`;
    menu_el.style.left = 'auto';
  } else {
    menu_el.style.left = `${Math.round(r.left)}px`;
    menu_el.style.right = 'auto';
  }
})()}
{/if}
<svelte:window
  onclick={(e) => {
    if (!open) return;
    const t = e.target;
    if (root_el?.contains?.(t) || menu_el?.contains?.(t)) return;
    open = false;
  }}
  onkeydown={(e) => { if (e.key === 'Escape' && open) open = false; }}
/>
<div
  class="dk-ctx"
  class:dk-ctx--open={open}
  bind:this={root_el}
  data-veil-role="context-menu"
  data-veil-agent={JSON.stringify(veil_agent)}
>
  <button
    type="button"
    class="dk-ctx__trigger"
    aria-label={aria_label}
    aria-haspopup="menu"
    aria-expanded={open}
    onclick={(e) => { e.stopPropagation(); e.preventDefault(); open = !open; }}
  >
    <span class="dk-ctx__dots" aria-hidden="true">⋮</span>
  </button>
  {#if open}
    <div
      bind:this={menu_el}
      class="dk-ctx__menu"
      class:dk-ctx__menu--left={align === 'left'}
      class:dk-ctx__menu--right={align === 'right'}
      role="menu"
    >
      {#if children}
        {@render children()}
      {:else}
        {#each (items || []) as item}
          {#if item.href && !item.disabled}
            <a
              href={item.href}
              class="dk-ctx__item"
              class:dk-ctx__item--danger={item.danger}
              role="menuitem"
              onclick={(e) => { e.preventDefault(); open = false; if (item.onSelect) item.onSelect(); else if (item.href) window.location.href = item.href; }}
            >{item.label}</a>
          {:else}
            <button
              type="button"
              class="dk-ctx__item"
              class:dk-ctx__item--danger={item.danger}
              role="menuitem"
              disabled={item.disabled}
              onclick={() => { if (!item.disabled) { open = false; if (item.onSelect) item.onSelect(); } }}
            >{item.label}</button>
          {/if}
        {/each}
      {/if}
    </div>
  {/if}
</div>


<style>
  /* TODO: Add component styles */
</style>
