<script lang="ts">
  // Generated by VEIL

  interface Props {
    open?: boolean;
    title?: string;
    size?: string;
    close_on_backdrop?: boolean;
    children?: Snippet | null;
    footer?: Snippet | null;
    on_close?: () => void | null;
    agent?: Record<string, unknown>;
  }
  let { open = $bindable(false), title = "", size = "md", close_on_backdrop = true, children, footer, on_close, agent = {  } }: Props = $props();

  let dialog_el: Any = $state(undefined as any);

  let veil_agent = $derived({ version: 1, role: "modal", product: agent, runtime: { open, title, size } });

  function request_close() {
    if (open === true) {
      open = false;
      if (on_close !== null) {
        on_close();
      };
    };
  }
</script>

{#if true}
{@const _sync = (() => {
  const d = dialog_el;
  if (!d || typeof document === 'undefined') return;
  if (d.parentElement !== document.body) document.body.appendChild(d);
  if (open) {
    if (!d.open) { try { d.showModal(); } catch { d.setAttribute('open', ''); } }
  } else if (d.open) {
    d.close();
  }
})()}
<dialog
  bind:this={dialog_el}
  class="dk-modal-dialog"
  class:dk-modal-dialog--open={open}
  data-veil-role="modal"
  data-veil-agent={JSON.stringify(veil_agent)}
  oncancel={(e) => { e.preventDefault(); request_close(); }}
  onclick={(e) => { if (close_on_backdrop && e.target === dialog_el) request_close(); }}
>
  <div class="dk-modal__panel dk-modal__panel--{size}" role="document">
    {#if title}
      <div class="dk-modal__header">
        <h3 id="dk-modal-title" class="dk-modal__title">{title}</h3>
        <button type="button" class="btn-ghost dk-modal__close" aria-label="Close" onclick={request_close} data-veil-action="close">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
    {/if}
    <div class="dk-modal__body">
      {#if children}
        {@render children()}
      {/if}
    </div>
    {#if footer}
      <div class="dk-modal__footer">
        {@render footer()}
      </div>
    {/if}
  </div>
</dialog>
{/if}


<style>
  /* TODO: Add component styles */
</style>
