<script lang="ts">
  // Generated by VEIL

  interface Props {
    title: string;
    description?: string;
    actions?: Snippet | null;
    children?: Snippet | null;
    agent?: Record<string, unknown>;
  }
  let { title, description = "", actions, children, agent = {  } }: Props = $props();

  let veil_agent = $derived({ version: 1, role: "page-header", product: agent, runtime: { title, description } });
</script>

<div
  class="dk-page-header"
  data-veil-role="page-header"
  data-veil-agent={JSON.stringify(veil_agent)}
>
  <div class="dk-page-header__text">
    <h1 class="dk-page-header__title">{title}</h1>
    {#if description}
      <p class="dk-page-header__desc">{description}</p>
    {/if}
    {#if children}
      {@render children()}
    {/if}
  </div>
  {#if actions}
    <div class="dk-page-header__actions">
      {@render actions()}
    </div>
  {/if}
</div>


<style>
  /* TODO: Add component styles */
</style>
