<script lang="ts">
  // Generated by VEIL

  let open_cr_count: number = $state(0);

   $effect(() => { // load_open_count
  void (async () => {
        open_cr_count = 0;
        let resp = await (async () => { const __u = new URL("/api/change_requests?status=ReadyForReview", typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
        open_cr_count = resp.length;
  })();
    });
</script>

<aside class="sidebar">
  <div class="logo"><span>◆</span> veil-runtime</div>
  <nav>
    <a href="/dashboard">Dashboard</a>
    <a href="/projects">Projects</a>
    <a href="/changes" class="nav-badge-link">
      Changes
      {#if open_cr_count > 0}
        <span class="nav-badge">{open_cr_count}</span>
      {/if}
    </a>
    <a href="/deploy">Deploy</a>
    <a href="/registry">Registry</a>
    <a href="/bus">Bus</a>
    <a href="/agents">Agents</a>
    <a href="/config">Config</a>
  </nav>
</aside>


<style>
.sidebar {
  width: 240px;
  flex-shrink: 0;
  height: 100%;
  background: var(--dk-glass, var(--surface));
  backdrop-filter: blur(16px) saturate(1.15);
  -webkit-backdrop-filter: blur(16px) saturate(1.15);
  border-right: 1px solid var(--dk-border-soft, var(--border));
  display: flex;
  flex-direction: column;
  padding: 20px 0;
  overflow-y: auto;
  animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both;
}
.sidebar .logo {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 20px 28px;
  font-weight: 700;
  font-size: 1.05rem;
  color: var(--text);
  letter-spacing: -0.02em;
}
.sidebar .logo span { color: var(--accent); }
.sidebar nav { display: flex; flex-direction: column; gap: 2px; }
.sidebar nav a {
  display: block;
  padding: 10px 20px;
  text-decoration: none;
  color: var(--text-dim);
  font-size: 14px;
  border-left: 2px solid transparent;
  transition:
    color var(--dk-dur-fast, 140ms) var(--dk-ease, ease),
    background var(--dk-dur-fast, 140ms) var(--dk-ease, ease),
    border-color var(--dk-dur-fast, 140ms) ease;
}
.sidebar nav a:hover {
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 10%, transparent);
}
.sidebar nav a:global([aria-current="page"]) {
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 12%, transparent);
  border-left-color: var(--accent);
  font-weight: 600;
}
.nav-badge-link {
  display: flex !important;
  align-items: center;
  justify-content: space-between;
}
.nav-badge {
  font-size: 0.65rem;
  font-weight: 700;
  min-width: 1.15rem;
  height: 1.15rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 999px;
  background: var(--accent);
  color: #fff;
  padding: 0 0.3rem;
  line-height: 1;
  animation: dk-fade-in 0.3s var(--dk-ease-out, ease) both;
}

</style>
