<script lang="ts">
  // Generated by VEIL

  let messages = $state<Record<string, unknown>[]>([]);
  let userInput = $state<string>('');

  function sendMessage() {
    messages = messages.push({ role: "user", content: userInput });
    resp = apiClient.mutate("/api/agent", { message: userInput });
    messages = messages.push({ role: "assistant", content: resp.message });
    userInput = "";
  }
</script>

<div class="agents"><h1>Agents</h1><div class="msgs">{#each messages as m}<div class={m.role}>{m.content}</div>{/each}</div><div class="row"><input bind:value={user_input} /><button onclick={sendMessage}>Send</button></div></div>


<style>
.agents { max-width: 900px; }
.msgs { min-height: 300px; overflow-y: auto; }
.user { text-align: right; background: rgba(99,102,241,0.1); padding: 8px; margin: 4px 0; border-radius: 6px; }
.assistant { background: var(--vr-surface); border: 1px solid var(--vr-border); padding: 8px; margin: 4px 0; border-radius: 6px; }
.row { display: flex; gap: 8px; }
.row input { flex: 1; padding: 8px; }

</style>
