<script lang="ts">
  // Generated by VEIL

  import Sidebar from './Sidebar.svelte';
  import StatusBar from './StatusBar.svelte';
</script>

<div class="shell"><Sidebar /><main>{@render children()}</main><StatusBar status="connected" /></div>


<style>
.shell { display: grid; grid-template-columns: 240px 1fr; grid-template-rows: 1fr auto; height: 100vh; }
main { overflow-y: auto; padding: 24px; }

</style>
