<script lang="ts">
  // Generated by VEIL

  let testMessage = $state<string>('');
  let result = $state<string | null>(null);

  function sendTest() {
    resp = apiClient.mutate("/api/bus/invoke", { message: testMessage });
    result = resp.result;
  }
</script>

<div class="bus"><h1>Bus</h1><input bind:value={testMessage} placeholder="Message..." /><button onclick={sendTest}>Send</button>{#if result}<pre>{result}</pre>{/if}</div>


<style>
.bus { max-width: 600px; }
input { width: 100%; padding: 8px; font-family: monospace; }
pre { background: var(--vr-surface); padding: 12px; }

</style>
