<script lang="ts">
  // Generated by VEIL

  let awsRegion = $state<string>('');
  let s3Bucket = $state<string>('');
  let ddbTable = $state<string>('');
  let llmModel = $state<string>('');
  let saving = $state<boolean>(false);

  function save() {
    saving = true;
    apiClient.mutate("/api/config", { awsRegion, s3Bucket, ddbTable, llmModel });
    saving = false;
  }
</script>

<div class="config"><h1>Config</h1><label>Region<input bind:value={aws_region} /></label><label>Bucket<input bind:value={s3_bucket} /></label><label>Table<input bind:value={ddb_table} /></label><label>Model<input bind:value={llm_model} /></label><button onclick={save} disabled={saving}>{saving ? "Saving..." : "Save"}</button></div>


<style>
.config { max-width: 600px; }
label { display: block; margin-bottom: 12px; font-size: 13px; }
input { width: 100%; padding: 8px; border: 1px solid var(--vr-border); border-radius: 4px; margin-top: 4px; }

</style>
