<script lang="ts">
  // Generated by VEIL

  import StatCard from './StatCard.svelte';
  import ProjectCard from './ProjectCard.svelte';

  let repos = $state<Record<string, unknown>[]>([]);
  let loading = $state<boolean>(false);

  function load() {
    repos = [];
    loading = false;
  }
</script>

<div class="dashboard">
  <h1>Dashboard</h1>
  <div class="stats">{#each [{v: repos.length, l: "Projects"}, {v: "—", l: "Deploys"}, {v: "—", l: "Layers"}, {v: "—", l: "Artifacts"}] as s}<StatCard value={s.v} label={s.l} />{/each}</div>
  {#if loading}<p>Loading...</p>{/if}
  {#each repos as repo}<ProjectCard name={repo.name} branch={repo.default_branch} updatedAt={repo.updated_at} id={repo.id} />{/each}
</div>


<style>
.dashboard { max-width: 1200px; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }

</style>
