<script lang="ts">
  // Generated by VEIL

  let artifactId = $state<string>('');
  let targetType = $state<string>('');
  let deploying = $state<boolean>(false);

  function triggerDeploy() {
    deploying = true;
    apiClient.mutate("/api/deploy", { artifactId, target: targetType });
    deploying = false;
  }
</script>

<div class="deploy"><h1>Deploy</h1><input bind:value={artifactId} placeholder="Artifact ID" /><select bind:value={targetType}><option value="lambda">Lambda</option><option value="container">Container</option></select><button onclick={triggerDeploy} disabled={deploying}>{deploying ? "Deploying..." : "Deploy"}</button></div>


<style>
.deploy { max-width: 600px; }
input, select { width: 100%; padding: 8px; margin-bottom: 12px; border: 1px solid var(--vr-border); border-radius: 4px; }

</style>
