<script lang="ts">
  // Generated by VEIL

  import ProjectCard from './ProjectCard.svelte';

  let repos = $state<Record<string, unknown>[]>([]);
  let newName = $state<string>('');

  function createProject() {
    apiClient.mutate("/api/projects", { name: newName });
    newName = "";
  }
</script>

<div class="projects"><h1>Projects</h1><input bind:value={newName} /><button onclick={createProject}>Create</button>{#each repos as r}<ProjectCard name={r.name} branch={r.default_branch} updatedAt={r.updated_at} id={r.id} />{/each}</div>


<style>
.projects { max-width: 1200px; }

</style>
