<script lang="ts">
  // Generated by VEIL

  let layers = $state<Record<string, unknown>[]>([]);
  let stubs = $state<Record<string, unknown>[]>([]);
</script>

<div class="registry"><h1>Registry</h1><h2>Layers</h2>{#each layers as l}<div class="item">{l.name}</div>{/each}<h2>Stubs</h2>{#each stubs as s}<div class="item">{s.crate_name} {s.version}</div>{/each}</div>


<style>
.registry { max-width: 900px; }
.item { padding: 8px 12px; border: 1px solid var(--vr-border); margin-bottom: 6px; border-radius: 4px; }

</style>
