<script lang="ts">
  // Generated by VEIL

  let navItems = $state<Record<string, unknown>[]>([]);
</script>

<aside class="sidebar">
  <div class="logo"><span>◆</span><span>veil-runtime</span></div>
  <nav>{#each navItems as item}<a href={item.href}>{item.label}</a>{/each}</nav>
</aside>


<style>
.sidebar { background: var(--vr-surface); border-right: 1px solid var(--vr-border); display: flex; flex-direction: column; padding: 16px 0; }
.logo { display: flex; align-items: center; gap: 10px; padding: 0 20px 24px; }
.nav-item { display: flex; align-items: center; gap: 10px; padding: 10px 12px; text-decoration: none; color: var(--vr-text-dim); }
.nav-item:hover { background: var(--vr-surface-hover); }
.nav-item.active { color: var(--vr-accent); }

</style>
