<script lang="ts">
  // Generated by VEIL

  interface Props {
    status: string;
  }
  let { status }: Props = $props();
</script>

<footer class="status-bar"><span class="dot"></span><span>{status}</span><span>veil-runtime v0.1.0</span></footer>


<style>
.status-bar { display: flex; justify-content: space-between; padding: 6px 16px; border-top: 1px solid var(--vr-border); font-size: 11px; }

</style>
