<script lang="ts">
  // Generated by VEIL

  interface Props {
    value: string;
    label: string;
  }
  let { value, label }: Props = $props();
</script>

<div class="stat-card"><span class="value">{value}</span><span class="label">{label}</span></div>


<style>
.stat-card { background: var(--vr-surface); border: 1px solid var(--vr-border); padding: 20px; border-radius: 8px; }
.value { font-size: 28px; font-weight: 700; color: var(--vr-accent); }
.label { font-size: 12px; color: var(--vr-text-dim); text-transform: uppercase; }

</style>
