<script lang="ts">
  // Generated by VEIL

  import PageHeader from './PageHeader.svelte';
  import EmptyState from './EmptyState.svelte';

  let messages = $state<Record<string, unknown>[]>([]);
  let user_input = $state<string>('');
  let sending = $state<boolean>(false);
  let error = $state<string>('');

  async function sendMessage() {
    sending = true;
    error = "";
    messages = messages.concat([{ role: "user", content: user_input }]);
    resp = await (async () => { const __r = await fetch("/api/agent", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: user_input }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    messages = messages.concat([{ role: "assistant", content: resp.message }]);
    user_input = "";
    sending = false;
  }
</script>

<div class="agents">
  <PageHeader title="Agents" description="Chat with the runtime agent over HTTPS." />
  <div class="panel card">
    <div class="msgs">
      {#if messages.length === 0}
        <EmptyState title="No messages yet" description="Send a prompt to start a conversation." />
      {:else}
        {#each messages as m, i}
          <div class="bubble {m.role}" style="--dk-i: {i}">{m.content}</div>
        {/each}
      {/if}
    </div>
    {#if error}
      <p class="dk-error">{error}</p>
    {/if}
    <div class="row">
      <input bind:value={user_input} placeholder="Message…" aria-label="Agent message" />
      <button type="button" class="btn-primary" onclick={sendMessage} disabled={sending || !user_input}>
        {sending ? "…" : "Send"}
      </button>
    </div>
  </div>
</div>


<style>
.agents { max-width: 52rem; animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both; }
.panel { padding: 1rem; display: flex; flex-direction: column; gap: 0.85rem; min-height: 22rem; }
.msgs { flex: 1; min-height: 16rem; max-height: 28rem; overflow-y: auto; display: flex; flex-direction: column; gap: 0.5rem; }
.bubble {
  padding: 0.65rem 0.85rem;
  border-radius: var(--dk-radius-sm, 0.55rem);
  animation: dk-fade-up 0.32s var(--dk-ease-out, ease) both;
  animation-delay: calc(var(--dk-i, 0) * 30ms);
  max-width: 90%;
}
.bubble.user {
  align-self: flex-end;
  background: color-mix(in srgb, var(--accent) 14%, transparent);
  border: 1px solid color-mix(in srgb, var(--accent) 28%, transparent);
}
.bubble.assistant {
  align-self: flex-start;
  background: var(--dk-surface-2, var(--surface));
  border: 1px solid var(--dk-border-soft, var(--border));
}
.row { display: flex; gap: 0.55rem; }
.row input { flex: 1; }

</style>
