<script lang="ts">
  // Generated by VEIL

  import PageHeader from './PageHeader.svelte';
  import FormSection from './FormSection.svelte';
  import FormField from './FormField.svelte';

  let testMessage = $state<string>('');
  let result = $state<string | null>(null);
  let sending = $state<boolean>(false);
  let error = $state<string>('');

  async function sendTest() {
    sending = true;
    error = "";
    resp = await (async () => { const __r = await fetch("/api/bus/invoke", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: testMessage }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    result = resp.result;
    sending = false;
  }
</script>

<div class="bus">
  <PageHeader title="Bus" description="Invoke a test message on the runtime bus." />
  <form class="dk-form card" onsubmit={(e) => { e.preventDefault(); sendTest(); }}>
    <FormSection title="Message" columns={1}>
      <FormField label="Payload" bind:value={testMessage} input_type="textarea" placeholder="Message…" />
    </FormSection>
    {#if error}
      <p class="dk-error">{error}</p>
    {/if}
    <div class="actions">
      <button type="submit" class="btn-primary" disabled={sending || !testMessage}>
        {sending ? "Sending…" : "Send"}
      </button>
    </div>
    {#if result}
      <pre class="result card">{result}</pre>
    {/if}
  </form>
</div>


<style>
.bus { max-width: 42rem; animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both; }
.dk-form { padding: 1.25rem 1.35rem 1.5rem; display: flex; flex-direction: column; gap: 1.25rem; }
.actions { display: flex; justify-content: flex-end; }
.result {
  margin: 0;
  padding: 0.85rem 1rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.82rem;
  white-space: pre-wrap;
  word-break: break-word;
}

</style>
