<script lang="ts">
  // Generated by VEIL

  import DetailShell from './DetailShell.svelte';
  import EntityIdentity from './EntityIdentity.svelte';
  import StatusPill from './StatusPill.svelte';
  import FormSection from './FormSection.svelte';
  import DetailField from './DetailField.svelte';
  import ConfirmDialog from './ConfirmDialog.svelte';

  let id = $state<string>('');
  let name = $state<string>('');
  let slug = $state<string>('');
  let description = $state<string>('');
  let default_branch = $state<string>('');
  let created_at = $state<string>('');
  let updated_at = $state<string>('');
  let loading = $state<boolean>(false);
  let error = $state<string>('');
  let loaded = $state<boolean>(false);
  let delete_open = $state<boolean>(false);
  let delete_busy = $state<boolean>(false);
  let environment = $state<string>('');
  let env_options = $state<string[]>([]);
  let env_role_hint = $state<string>('');
  let infra = $state<Record<string, unknown>>(undefined as any);
  let units = $state<Record<string, unknown>[]>([]);
  let has_deploy = $state<boolean>(false);
  let has_toml = $state<boolean>(false);
  let region = $state<string>('');
  let project_prefix = $state<string>('');
  let network_vpc = $state<string>('');
  let toml_path = $state<string>('');
  let provision_busy = $state<boolean>(false);
  let provision_msg = $state<string>('');
  let provision_job_id = $state<string>('');
  let provision_percent = $state<number>(0);
  let provision_status = $state<string>('');
  let provision_steps = $state<Record<string, unknown>[]>([]);
  let plan_open = $state<boolean>(false);
  let plan_loading = $state<boolean>(false);
  let plan_summary = $state<string>('');
  let plan_mock = $state<boolean>(false);
  let plan_resources = $state<Record<string, unknown>[]>([]);
  let plan_steps = $state<Record<string, unknown>[]>([]);
  let plan_notes = $state<string[]>([]);
  let plan_diff = $state<Record<string, unknown>>(undefined as any);
  let plan_cta = $state<string>('');
  let aws_inventory = $state<Record<string, unknown>[]>([]);
  let stack_base = $state<string>('');
  let provision_cta = $state<string>('');
  let any_provisioned = $state<boolean>(false);
  let infra_status = $state<string>('');
  let infra_status_variant = $state<string>('');

    $effect(() => { // init
      error = "";
      loading = true;
      loaded = false;
      environment = "dev";
      env_options = ["dev", "staging", "prod"];
      env_role_hint = "";
      name = "";
      slug = "";
      description = "";
      default_branch = "";
      created_at = "";
      updated_at = "";
      has_deploy = false;
      has_toml = false;
      region = "";
      project_prefix = "";
      network_vpc = "";
      toml_path = "";
      provision_msg = "";
      provision_job_id = "";
      provision_percent = 0;
      provision_status = "";
      provision_steps = [];
      plan_open = false;
      plan_loading = false;
      plan_summary = "";
      plan_mock = false;
      plan_resources = [];
      plan_steps = [];
      plan_notes = [];
      plan_diff = {  };
      plan_cta = "Confirm & provision";
      aws_inventory = [];
      stack_base = "";
      provision_cta = "Provision";
      any_provisioned = false;
      infra_status = "not provisioned";
      infra_status_variant = "warning";
      units = [];
      infra = {  };
      id = project_id_from_path();
    });
   $effect(() => { // load_existing
  void (async () => {
        if (id !== "") {
          if (loaded === false) {
            error = "";
            loading = true;
            let repo = await (async () => { const __u = new URL(`KEEPid}`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {  } as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            name = field_str(repo, "name");
            slug = field_str(repo, "slug");
            description = field_str(repo, "description");
            default_branch = field_str(repo, "default_branch");
            if (default_branch === "") {
              default_branch = "main";
            };
            created_at = field_str(repo, "created_at");
            updated_at = field_str(repo, "updated_at");
            let catalog = await (async () => { const __u = new URL("/api/deploy_environments", typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {  } as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            apply_env_catalog(catalog);
            let wrap = await (async () => { const __u = new URL(`/api/project_infras/${id}`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = { environment } as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            await hydrate_from_infra(wrap);
            loading = false;
            loaded = true;
          };
        };
  })();
    });
   $effect(() => { // do_delete
  void (async () => {
        if (delete_busy === true) {
          if (id !== "") {
            await (async () => { const __r = await fetch(`KEEPid}`, { method: 'DELETE' }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
            delete_busy = false;
            delete_open = false;
            (window.location.href = "/projects");
          };
        };
  })();
    });
    $effect(() => { // do_provision
      if (provision_busy === true) {
        if (slug !== "") {
          run_provision();
        };
      };
    });

  function select_environment(next: string) {
    if (next !== "") {
      if (next !== environment) {
        environment = next;
        provision_msg = "";
        loaded = false;
      };
    };
  }
  async function load_provision_plan() {
    plan_loading = true;
    plan_open = true;
    plan_summary = "";
    plan_resources = [];
    plan_steps = [];
    plan_notes = [];
    plan_diff = {  };
    plan_mock = false;
    error = "";
    let plan = await (async () => { const __r = await fetch("/api/plan-provision", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_slug: slug, environment, repo_id: id, branch: default_branch }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    apply_plan(plan);
    plan_loading = false;
  }

  // raw script block (escape hatch — prefer VEIL fn/effect)
  function project_id_from_path(): string {
  if (typeof window === 'undefined') return '';
  const p = window.location.pathname;
  const t = p.endsWith('/') ? p.slice(0, -1) : p;
  const parts = t.split('/').filter(Boolean);
  const i = parts.indexOf('projects');
  if (i >= 0 && parts[i + 1] && parts[i + 1] !== 'new') return parts[i + 1];
  return '';
  }
  function field_str(obj: any, key: string): string {
  const v = obj?.[key];
  return v == null ? '' : String(v);
  }
  function classify_unit_state(state: any): { provisioned: boolean; label: string; kind: string } {
  if (!state) return { provisioned: false, label: 'not provisioned', kind: 'none' };
  const arn = state?.aws_resources?.lambda_arn != null ? String(state.aws_resources.lambda_arn) : '';
  if (!arn) return { provisioned: false, label: 'incomplete', kind: 'partial' };
  if (arn.includes(':mock:') || arn.includes('lambda:mock') || arn.startsWith('arn:aws:lambda:mock')) {
  return { provisioned: false, label: 'mock only', kind: 'mock' };
  }
  const st = state?.status != null ? String(state.status) : 'Active';
  return { provisioned: true, label: st, kind: 'ok' };
  }
  function overall_infra_status(rows: any[]): { label: string; variant: string } {
  if (!rows.length) return { label: `${environment}: no units`, variant: 'warning' };
  const kinds = rows.map((r) => r.kind || 'none');
  if (kinds.every((k) => k === 'ok')) return { label: `${environment}: infra provisioned`, variant: 'success' };
  if (kinds.every((k) => k === 'none')) return { label: `${environment}: not provisioned`, variant: 'warning' };
  if (kinds.some((k) => k === 'mock')) return { label: `${environment}: mock state only`, variant: 'warning' };
  return { label: `${environment}: partial / incomplete`, variant: 'warning' };
  }
  function build_aws_inventory(snap: any, unitRows: any[]): any[] {
  const names = snap?.stack?.names || {};
  const rows: any[] = [];
  const seen = new Set<string>();
  const add = (kind: string, name: string, detail: string, status: string, ref: string) => {
  if (!name || seen.has(`${kind}:${name}`)) return;
  seen.add(`${kind}:${name}`);
  rows.push({ kind, name, detail: detail || '', status: status || 'declared', ref: ref || '' });
  };
  add('DynamoDB', names.dynamodb || '', 'Shared table (PK/SK)', 'stack', '');
  add('SNS', names.sns || '', 'Event topic', 'stack', '');
  add('SQS', names.sqs || '', 'Main queue', 'stack', '');
  add('SQS DLQ', names.sqs_dlq || '', 'Dead-letter queue', 'stack', '');
  for (const u of unitRows) {
  const aws = u.aws || {};
  const ty = String(u.type || '');
  let fn = '';
  if (ty === 'lambda-api') fn = names.lambda_api || '';
  else if (ty === 'lambda-consumer') fn = names.lambda_consumer || '';
  if (!fn && aws.lambda_arn) {
  const m = String(aws.lambda_arn).match(/function:([^:]+)/);
  if (m) fn = m[1];
  }
  if (!fn) fn = `veil-${snap?.service || 'app'}-${u.name}`;
  const st = u.provisioned ? (u.status || 'Active') : 'not provisioned';
  add('Lambda', fn, `${u.name} · ${ty}`, st, aws.lambda_arn || '');
  if (aws.log_group) add('CloudWatch', aws.log_group, `Logs · ${u.name}`, u.provisioned ? 'Active' : 'pending', '');
  if (aws.role_arn) {
  const role = String(aws.role_arn).split('/').pop() || aws.role_arn;
  add('IAM Role', role, `Execution role · ${u.name}`, u.provisioned ? 'attached' : 'pending', aws.role_arn);
  }
  if (ty === 'lambda-api') {
  const gw = u.gateway && u.gateway !== '—' ? String(u.gateway) : 'dashlx-services';
  const path = u.path_prefix && u.path_prefix !== '—' ? String(u.path_prefix) : '/';
  add('API Gateway', gw, `HTTP API attach · path ${path}`, aws.api_gw_id ? `id ${aws.api_gw_id}` : 'fuzzy match on provision', aws.api_gw_id || '');
  }
  if (ty === 'lambda-consumer' && (aws.sqs_queue_url || names.sqs)) {
  add('Event source', fn + ' ← ' + (names.sqs || 'queue'), 'SQS → Lambda mapping', u.provisioned ? 'Active' : 'pending', aws.sqs_queue_arn || '');
  }
  if (aws.sqs_queue_url) {
  const qn = String(aws.sqs_queue_url).split('/').pop() || '';
  if (qn) add('SQS', qn, `Queue (from ${u.name} state)`, 'Active', aws.sqs_queue_url);
  }
  }
  return rows;
  }
  function provision_button_label(): string {
  if (provision_busy) return `Provisioning… ${provision_percent}%`;
  if (plan_loading) return 'Loading plan…';
  if (plan_open) return plan_cta || `Confirm (${environment})`;
  if (any_provisioned) return `Reconcile (${environment})`;
  return `Provision (${environment})`;
  }
  function apply_env_catalog(catalog: any) {
  const list = Array.isArray(catalog?.environments) ? catalog.environments : [];
  if (!list.length) return;
  env_options = list.map((e: any) => String(e.name));
  if (!environment || !env_options.includes(environment)) {
  environment = catalog?.default != null ? String(catalog.default) : env_options[0];
  }
  const cur = list.find((e: any) => e.name === environment);
  if (cur?.has_assume_role) {
  env_role_hint = cur.assume_role_arn != null ? String(cur.assume_role_arn) : 'cross-account role configured';
  } else {
  env_role_hint = 'same-account credentials (no assume_role_arn)';
  }
  }
  /** Load per-unit deploy state + build inventory (uses GET deployment_status). */
  async function hydrate_from_infra(wrap: any) {
  const snap = wrap?.infra ?? wrap ?? {};
  infra = snap;
  has_toml = !!snap.has_toml;
  has_deploy = !!snap.has_deploy;
  region = field_str(snap, 'region');
  project_prefix = field_str(snap, 'project_prefix');
  toml_path = field_str(snap, 'toml_path');
  network_vpc = snap?.network?.vpc != null ? String(snap.network.vpc) : '';
  stack_base = snap?.stack?.base != null
  ? String(snap.stack.base)
  : (snap?.stack?.names?.base != null ? String(snap.stack.names.base) : '');
  const rawUnits = Array.isArray(snap.units) ? snap.units : [];
  const unit_rows = [];
  for (const u of rawUnits) {
  const uname = u?.name != null ? String(u.name) : '';
  let st: any = null;
  if (uname) {
  try {
  const stRes = await fetch(
  `/api/deployment_status?environment=${encodeURIComponent(environment)}&unit_name=${encodeURIComponent(uname)}`
  );
  if (stRes.ok) {
  const body = await stRes.json();
  st = body?.state ?? null;
  }
  } catch (_) { /* not provisioned */ }
  }
  const classified = classify_unit_state(st);
  const aws = st?.aws_resources || {};
  unit_rows.push({
  name: uname,
  type: u?.type != null ? String(u.type) : '—',
  context: u?.context != null ? String(u.context) : '—',
  description: u?.description != null ? String(u.description) : '',
  memory_mb:
  u?.lambda?.memory_mb != null
  ? String(u.lambda.memory_mb)
  : u?.ecs?.memory_mb != null
  ? String(u.ecs.memory_mb)
  : '—',
  timeout: u?.lambda?.timeout_seconds != null ? String(u.lambda.timeout_seconds) : '—',
  arch: u?.lambda?.architecture != null ? String(u.lambda.architecture) : '—',
  path_prefix: u?.api_gateway?.path_prefix != null ? String(u.api_gateway.path_prefix) : '—',
  gateway: u?.api_gateway?.gateway != null ? String(u.api_gateway.gateway) : '—',
  provisioned: classified.provisioned,
  status: classified.label,
  kind: classified.kind,
  version: st?.version != null ? String(st.version) : '',
  aws,
  lambda_arn: aws?.lambda_arn != null ? String(aws.lambda_arn) : '',
  });
  }
  units = unit_rows;
  any_provisioned = unit_rows.some((r) => r.provisioned);
  provision_cta = any_provisioned ? 'Reconcile' : 'Provision';
  aws_inventory = build_aws_inventory(snap, unit_rows);
  const overall = overall_infra_status(unit_rows);
  infra_status = overall.label;
  infra_status_variant = overall.variant;
  }
  function apply_job_snapshot(job: any) {
  provision_job_id = job?.job_id != null ? String(job.job_id) : provision_job_id;
  provision_status = job?.status != null ? String(job.status) : '';
  provision_percent = job?.percent != null ? Number(job.percent) : 0;
  provision_msg = job?.summary != null ? String(job.summary) : '';
  provision_steps = Array.isArray(job?.steps) ? job.steps : [];
  if (job?.error) error = String(job.error);
  }
  function apply_plan(plan: any) {
  plan_summary = plan?.summary != null ? String(plan.summary) : 'Review plan below.';
  plan_mock = !!plan?.mock_mode;
  plan_resources = Array.isArray(plan?.resources) ? plan.resources : [];
  plan_steps = Array.isArray(plan?.steps) ? plan.steps : [];
  plan_notes = Array.isArray(plan?.notes) ? plan.notes.map((n: any) => String(n)) : [];
  plan_diff = plan?.diff && typeof plan.diff === 'object' ? plan.diff : {};
  const c = Number(plan_diff?.create || 0);
  const u = Number(plan_diff?.update || 0);
  if (c === 0 && u === 0) plan_cta = 'All synced ✓';
  else if (c > 0) plan_cta = 'Confirm & provision';
  else if (u > 0) plan_cta = 'Confirm & reconcile';
  else plan_cta = any_provisioned ? 'Confirm redeploy code' : 'Confirm & provision';
  }
  async function poll_provision_job(jobId: string) {
  if (!jobId) throw new Error('No job_id from provision-project');
  const deadline = Date.now() + 30 * 60 * 1000;
  while (Date.now() < deadline) {
  await new Promise((r) => setTimeout(r, 800));
  const r = await fetch(`/api/provision_jobs?job_id=${encodeURIComponent(jobId)}`);
  if (!r.ok) throw new Error(await r.text());
  const job = await r.json();
  apply_job_snapshot(job);
  const st = String(job?.status || '');
  if (st === 'succeeded' || st === 'failed') return job;
  }
  throw new Error('Provision timed out after 30 minutes');
  }
  /** Async provision runner — poll needs setTimeout; kept here so the effect can fire-and-forget. */
  async function run_provision() {
  plan_open = false;
  provision_msg = '';
  error = '';
  provision_percent = 0;
  provision_status = 'starting';
  provision_steps = [];
  try {
  const r = await fetch('/api/provision-project', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ project_slug: slug, environment, repo_id: id, branch: default_branch || 'main' }),
  });
  if (!r.ok) throw new Error(await r.text());
  const started = await r.json();
  apply_job_snapshot(started);
  const jobId = started?.job_id != null ? String(started.job_id) : '';
  const finalJob = await poll_provision_job(jobId);
  if (String(finalJob?.status) === 'failed') {
  throw new Error(finalJob?.error != null ? String(finalJob.error) : 'Provision failed');
  }
  provision_msg = finalJob?.summary != null ? String(finalJob.summary) : 'Provision complete.';
  loaded = false;
  } catch (e: any) {
  error = e?.message != null ? String(e.message) : String(e);
  provision_status = 'failed';
  } finally {
  provision_busy = false;
  }
  }

</script>

<DetailShell
  title={name || 'Project'}
  subtitle={slug ? `/${slug}` : ''}
  back_href="/projects"
  loading={loading}
  error={error}
  agent={{ intent: 'view-project', entity: 'Repo', entityLabel: 'Project', itemId: id }}
>
  {#snippet header_actions()}
    {#if has_deploy}
      <label class="env-select-wrap">
        <span class="env-select-label">Environment</span>
        <select
          class="env-select"
          value={environment}
          disabled={provision_busy || loading}
          onchange={(e) => { select_environment((e.currentTarget as HTMLSelectElement).value); }}
        >
          {#each env_options as opt}
            <option value={opt} selected={opt === environment}>{opt}</option>
          {/each}
        </select>
      </label>
      <button
        type="button"
        class="btn-outline"
        disabled={provision_busy || plan_loading || loading}
        onclick={() => { load_provision_plan(); }}
      >
        {plan_loading ? "Loading plan…" : "Preview plan"}
      </button>
      <button
        type="button"
        class="btn-primary"
        class:btn-primary--reconcile={any_provisioned && !provision_busy}
        disabled={provision_busy || plan_loading}
        onclick={() => { if (plan_open) { provision_busy = true; } else { load_provision_plan(); } }}
      >
        {provision_button_label()}
      </button>
    {/if}
    <button type="button" class="btn-outline" onclick={() => { delete_open = true; }}>Delete</button>
  {/snippet}
  {#snippet summary()}
    <div class="summary card">
      <EntityIdentity name={name || '—'} subtitle={default_branch} show_avatar={true} />
      {#if has_deploy}
        <div class="summary-meta">
          <StatusPill label={infra_status} variant={infra_status_variant} />
          {#if region}<span class="chip">{region}</span>{/if}
          {#if project_prefix}<span class="chip">prefix: {project_prefix}</span>{/if}
        </div>
        {#if env_role_hint}
          <p class="hint">Provision identity: <code>{env_role_hint}</code></p>
        {/if}
      {:else if has_toml}
        <p class="hint">No <code>[deploy]</code> section in veil.toml — infrastructure is not configured for this project.</p>
      {:else}
        <p class="hint">No veil.toml found on the projects hub for slug <code>{slug}</code>.</p>
      {/if}

      {#if plan_open && !provision_busy}
        <div class="prov-plan" aria-busy={plan_loading}>
          <div class="prov-progress__head">
            <span class="prov-progress__title">Apply plan ({environment})</span>
            {#if plan_loading}
              <span class="chip">Checking AWS…</span>
            {:else if plan_mock}
              <span class="chip chip--warn">MOCK MODE</span>
            {/if}
          </div>
          {#if plan_loading}
            <div class="plan-loading" role="status" aria-live="polite">
              <span class="dk-spinner" aria-hidden="true"></span>
              <div class="plan-loading__text">
                <strong>Building plan…</strong>
                <span>Checking which stack resources exist in {environment} (describe/get). This can take a few seconds.</span>
              </div>
            </div>
            <div class="plan-actions">
              <button type="button" class="btn-outline" disabled={true}>Cancel</button>
              <button type="button" class="btn-primary" disabled={true}>Loading…</button>
            </div>
          {:else}
            <p class="prov-progress__summary">{plan_summary}</p>
            {#if plan_diff && (plan_diff.create != null || plan_diff.update != null)}
              <div class="plan-diff">
                <span class="plan-diff__chip plan-diff__chip--create">{plan_diff.create || 0} create</span>
                <span class="plan-diff__chip plan-diff__chip--update">{plan_diff.update || 0} update</span>
                <span class="plan-diff__chip plan-diff__chip--noop">{plan_diff.noop || 0} noop</span>
                <span class="plan-diff__chip plan-diff__chip--destroy">{plan_diff.destroy || 0} destroy</span>
              </div>
            {/if}
            {#if plan_notes.length}
              <ul class="plan-notes">
                {#each plan_notes as n}
                  <li>{n}</li>
                {/each}
              </ul>
            {/if}
            {#if plan_resources.length}
              <h3 class="plan-h">Resource actions</h3>
              <ul class="plan-resources">
                {#each plan_resources as r}
                  <li>
                    <span class="plan-kind">{r.kind}</span>
                    <code class="plan-name">{r.name}</code>
                    <span class={`plan-action plan-action--${r.action || 'ensure'}`}>{r.action || 'ensure'}</span>
                    {#if r.detail}<span class="plan-detail">{r.detail}</span>{/if}
                  </li>
                {/each}
              </ul>
            {/if}
            {#if plan_steps.length}
              <h3 class="plan-h">Steps</h3>
              <ol class="prov-steps">
                {#each plan_steps as step, i}
                  <li class="prov-step prov-step--pending" style={`--dk-i: ${i}`}>
                    <span class="prov-step__dot" aria-hidden="true"></span>
                    <div class="prov-step__body">
                      <div class="prov-step__label">{step.label || step.id}</div>
                      {#if step.phase || step.action}
                        <div class="prov-step__detail">
                          {#if step.phase}phase: {step.phase}{/if}
                          {#if step.action}
                            <span class={`plan-action plan-action--${step.action}`}>{step.action}</span>
                          {/if}
                        </div>
                      {/if}
                    </div>
                  </li>
                {/each}
              </ol>
            {/if}
            <div class="plan-actions">
              <button type="button" class="btn-outline" onclick={() => { plan_open = false; }}>Cancel</button>
              <button type="button" class="btn-primary" onclick={() => { provision_busy = true; }}>
                {plan_cta}
              </button>
            </div>
          {/if}
        </div>
      {/if}

      {#if provision_busy || provision_steps.length > 0}
        <div class="prov-progress card-inner">
          <div class="prov-progress__head">
            <span class="prov-progress__title">
              {provision_status === 'succeeded' ? 'Provision complete' : provision_status === 'failed' ? 'Provision failed' : 'Provisioning…'}
            </span>
            <span class="prov-progress__pct">{provision_percent}%</span>
          </div>
          <div class="prov-progress__track" aria-hidden="true">
            <div
              class="prov-progress__fill"
              class:prov-progress__fill--ok={provision_status === 'succeeded'}
              class:prov-progress__fill--err={provision_status === 'failed'}
              style={`width: ${Math.min(100, Math.max(0, provision_percent))}%`}
            ></div>
          </div>
          {#if provision_msg}
            <p class="prov-progress__summary">{provision_msg}</p>
          {/if}
          <ol class="prov-steps">
            {#each provision_steps as step, i}
              <li class={`prov-step prov-step--${step.status || 'pending'}`} style={`--dk-i: ${i}`}>
                <span class="prov-step__dot" aria-hidden="true"></span>
                <div class="prov-step__body">
                  <div class="prov-step__label">{step.label || step.id}</div>
                  {#if step.detail}
                    <div class="prov-step__detail">{step.detail}</div>
                  {/if}
                </div>
                <span class="prov-step__status">{step.status}</span>
              </li>
            {/each}
          </ol>
        </div>
      {:else if provision_msg}
        <p class="ok-msg">{provision_msg}</p>
      {/if}
    </div>
  {/snippet}

  <FormSection title="Repository" columns={2}>
    <DetailField label="Name" value={name} />
    <DetailField label="Slug" value={slug} mono={true} />
    <DetailField label="Default branch" value={default_branch} />
    <DetailField label="Id" value={id} mono={true} />
    <DetailField label="Created" value={created_at} />
    <DetailField label="Updated" value={updated_at} />
  </FormSection>
  <FormSection title="Description" columns={1}>
    <DetailField label="Description" value={description || '—'} />
  </FormSection>

  {#if has_deploy}
    <FormSection title="Infrastructure (veil.toml [deploy])" columns={2}>
      <DetailField label="Region" value={region || '—'} />
      <DetailField label="Project prefix" value={project_prefix || '—'} />
      <DetailField label="Stack base" value={stack_base || '—'} mono={true} />
      <DetailField label="VPC" value={network_vpc || '—'} />
      <DetailField label="Environment" value={environment} />
      <DetailField label="veil.toml" value={toml_path || '—'} mono={true} />
    </FormSection>

    <div class="units-block">
      <h2 class="units-title">AWS services ({environment})</h2>
      <p class="hint inv-hint">
        Full inventory from the resolved stack + last provision state. Click <strong>Reconcile</strong> to plan create/update/noop against live AWS (removals are never destroyed automatically).
      </p>
      {#if aws_inventory.length === 0}
        <p class="hint">No stack resources resolved yet.</p>
      {:else}
        <div class="dk-table-wrap card">
          <table class="dk-table">
            <thead>
              <tr>
                <th>Service</th>
                <th>Name / id</th>
                <th>Detail</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {#each aws_inventory as r, i}
                <tr class="dk-table__row" style="--dk-i: {i}">
                  <td><span class="inv-kind">{r.kind}</span></td>
                  <td>
                    <code class="inv-name">{r.name}</code>
                    {#if r.ref}<div class="dk-tile__meta inv-ref">{r.ref}</div>{/if}
                  </td>
                  <td><span class="dk-tile__meta">{r.detail}</span></td>
                  <td>
                    <StatusPill
                      label={String(r.status)}
                      variant={String(r.status).includes('not ') || r.status === 'pending' || r.status === 'stack' ? 'warning' : 'success'}
                    />
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </div>

    <div class="units-block">
      <h2 class="units-title">Deploy units</h2>
      {#if units.length === 0}
        <p class="hint">No [[deploy.units]] declared.</p>
      {:else}
        <div class="dk-table-wrap card">
          <table class="dk-table">
            <thead>
              <tr>
                <th>Unit</th>
                <th>Type</th>
                <th>Context</th>
                <th>Gateway</th>
                <th>Memory</th>
                <th>Status ({environment})</th>
              </tr>
            </thead>
            <tbody>
              {#each units as u, i}
                <tr class="dk-table__row" style="--dk-i: {i}">
                  <td>
                    <div class="unit-name">{u.name}</div>
                    {#if u.description}<div class="dk-tile__meta">{u.description}</div>{/if}
                    {#if u.lambda_arn}<div class="dk-tile__meta inv-ref">{u.lambda_arn}</div>{/if}
                  </td>
                  <td><span class="dk-tile__meta">{u.type}</span></td>
                  <td><span class="dk-tile__meta">{u.context}</span></td>
                  <td><span class="dk-tile__meta">{u.gateway}{u.path_prefix && u.path_prefix !== '—' ? ` ${u.path_prefix}` : ''}</span></td>
                  <td><span class="dk-tile__meta">{u.memory_mb}{u.memory_mb !== '—' ? ' MB' : ''}</span></td>
                  <td>
                    <StatusPill
                      label={u.provisioned ? (u.version ? `${u.status} · v${u.version}` : String(u.status)) : 'not provisioned'}
                      variant={u.provisioned ? 'success' : 'warning'}
                    />
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </div>
  {/if}
</DetailShell>

<ConfirmDialog
  bind:open={delete_open}
  title="Delete project"
  message={`Are you sure you want to delete “${name}”? This cannot be undone.`}
  confirm_label="Delete"
  cancel_label="Cancel"
  variant="danger"
  on_confirm={() => { delete_busy = true; }}
/>


<style>
.summary { padding: 1rem 1.15rem; margin-bottom: 0.5rem; display: flex; flex-direction: column; gap: 0.75rem; }
.summary-meta { display: flex; flex-wrap: wrap; align-items: center; gap: 0.5rem; }
.chip {
  font-size: 0.75rem;
  color: var(--dk-text-muted);
  border: 1px solid var(--dk-border-soft);
  border-radius: 999px;
  padding: 0.15rem 0.55rem;
}
.hint { color: var(--dk-text-muted); font-size: 0.9rem; margin: 0; }
.ok-msg { color: var(--dk-green, #22c55e); font-size: 0.9rem; margin: 0; }
.units-block { margin-top: 0.5rem; }
.units-title {
  font-size: 0.72rem; font-weight: 650; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--dk-text-muted); margin: 0 0 0.75rem;
}
.unit-name { font-weight: 600; }
.env-select-wrap {
  display: inline-flex; align-items: center; gap: 0.4rem;
  margin-right: 0.35rem;
}
.env-select-label {
  font-size: 0.72rem; font-weight: 650; text-transform: uppercase;
  letter-spacing: 0.06em; color: var(--dk-text-muted);
}
.env-select {
  font: inherit; font-size: 0.9rem;
  border: 1px solid var(--dk-border-soft);
  border-radius: 0.45rem;
  padding: 0.35rem 0.55rem;
  background: var(--dk-surface, #fff);
  color: inherit;
}
.prov-progress {
  margin-top: 0.75rem;
  padding: 0.85rem 1rem;
  border: 1px solid var(--dk-border-soft);
  border-radius: 0.65rem;
  background: var(--dk-surface-2, rgba(0,0,0,0.03));
  display: flex; flex-direction: column; gap: 0.55rem;
  animation: prov-panel-in 0.35s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
}
.prov-progress__head { display: flex; justify-content: space-between; align-items: baseline; gap: 0.5rem; }
.prov-progress__title { font-weight: 650; font-size: 0.92rem; }
.prov-progress__pct { font-size: 0.8rem; color: var(--dk-text-muted); font-variant-numeric: tabular-nums; }
.prov-progress__track {
  height: 0.45rem; border-radius: 999px;
  background: var(--dk-border-soft, #e5e7eb); overflow: hidden;
  animation: track-reveal 0.4s 0.15s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
}
@keyframes track-reveal {
  from { opacity: 0; transform: scaleX(0.3); }
  to { opacity: 1; transform: scaleX(1); }
}
.prov-progress__fill {
  height: 100%; width: 0; border-radius: 999px;
  background: var(--dk-accent, #6366f1);
  transition: width 0.4s cubic-bezier(0.16, 1, 0.3, 1);
  position: relative; overflow: hidden;
}
.prov-progress__fill::after {
  content: '';
  position: absolute; inset: 0;
  background: linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.25) 50%, transparent 100%);
  animation: prov-shimmer 1.8s ease-in-out infinite;
}
@keyframes prov-shimmer {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(100%); }
}
.prov-progress__fill--ok { background: var(--dk-green, #22c55e); }
.prov-progress__fill--ok::after { animation: none; }
.prov-progress__fill--err { background: var(--dk-red, #ef4444); }
.prov-progress__fill--err::after { animation: none; }
.prov-progress__summary { margin: 0; font-size: 0.85rem; color: var(--dk-text-muted); }
.prov-steps { list-style: none; margin: 0.25rem 0 0; padding: 0; display: flex; flex-direction: column; gap: 0.35rem; }
.prov-step {
  display: grid; grid-template-columns: 0.65rem 1fr auto; gap: 0.55rem;
  align-items: start; font-size: 0.82rem;
  animation: prov-step-in 0.3s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
  animation-delay: calc(var(--dk-i, 0) * 60ms + 80ms);
}
@keyframes prov-step-in {
  from { opacity: 0; transform: translateX(-6px); }
  to { opacity: 1; transform: translateX(0); }
}
.prov-step__dot {
  width: 0.55rem; height: 0.55rem; border-radius: 999px; margin-top: 0.3rem;
  background: var(--dk-border-soft, #cbd5e1);
  transition: background 0.25s ease, box-shadow 0.25s ease, transform 0.2s ease;
}
.prov-step--running .prov-step__dot { background: var(--dk-accent, #6366f1); box-shadow: 0 0 0 3px color-mix(in srgb, var(--dk-accent, #6366f1) 25%, transparent); animation: prov-dot-pulse 1.2s ease-in-out infinite; }
.prov-step--done .prov-step__dot { background: var(--dk-green, #22c55e); transform: scale(1.15); box-shadow: 0 0 0 2px color-mix(in srgb, var(--dk-green, #22c55e) 20%, transparent); }
.prov-step--skipped .prov-step__dot { background: var(--dk-text-muted, #94a3b8); }
.prov-step--error .prov-step__dot { background: var(--dk-red, #ef4444); box-shadow: 0 0 0 2px color-mix(in srgb, var(--dk-red, #ef4444) 20%, transparent); }
@keyframes prov-dot-pulse {
  0%, 100% { box-shadow: 0 0 0 3px color-mix(in srgb, var(--dk-accent, #6366f1) 25%, transparent); transform: scale(1); }
  50% { box-shadow: 0 0 0 5px color-mix(in srgb, var(--dk-accent, #6366f1) 12%, transparent); transform: scale(1.1); }
}
.prov-step__label { font-weight: 550; }
.prov-step__detail { color: var(--dk-text-muted); font-size: 0.78rem; word-break: break-word; margin-top: 0.1rem; }
.prov-step__status { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--dk-text-muted); }
.prov-plan {
  margin-top: 0.75rem; padding: 0.85rem 1rem;
  border: 1px solid var(--dk-border-soft); border-radius: 0.65rem;
  background: var(--dk-surface-2, rgba(0,0,0,0.03));
  display: flex; flex-direction: column; gap: 0.55rem;
  animation: prov-panel-in 0.35s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
}
@keyframes prov-panel-in {
  from { opacity: 0; transform: translateY(-8px) scale(0.98); }
  to { opacity: 1; transform: translateY(0) scale(1); }
}
.plan-notes { margin: 0; padding-left: 1.1rem; color: var(--dk-text-muted); font-size: 0.82rem; }
.plan-h {
  margin: 0.35rem 0 0; font-size: 0.72rem; font-weight: 650;
  text-transform: uppercase; letter-spacing: 0.06em; color: var(--dk-text-muted);
}
.plan-resources { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.35rem; }
.plan-resources li {
  display: grid; grid-template-columns: 6.5rem 1fr auto; gap: 0.4rem 0.65rem;
  font-size: 0.82rem; align-items: baseline;
  animation: prov-step-in 0.25s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
  animation-delay: calc(var(--dk-i, 0) * 45ms + 50ms);
}
.plan-kind { color: var(--dk-text-muted); text-transform: uppercase; font-size: 0.7rem; letter-spacing: 0.04em; }
.plan-name { font-size: 0.8rem; }
.plan-action {
  font-size: 0.68rem; font-weight: 650; text-transform: uppercase; letter-spacing: 0.04em;
  border-radius: 999px; padding: 0.1rem 0.45rem;
  border: 1px solid var(--dk-border-soft); color: var(--dk-text-muted);
}
.plan-action--create { color: #15803d; border-color: color-mix(in srgb, #22c55e 45%, var(--dk-border-soft)); background: color-mix(in srgb, #22c55e 12%, transparent); }
.plan-action--update { color: #1d4ed8; border-color: color-mix(in srgb, #3b82f6 45%, var(--dk-border-soft)); background: color-mix(in srgb, #3b82f6 12%, transparent); }
.plan-action--noop { color: var(--dk-text-muted); }
.plan-action--skip, .plan-action--ensure { color: #a16207; border-color: color-mix(in srgb, #f59e0b 40%, var(--dk-border-soft)); }
.plan-detail { grid-column: 1 / -1; color: var(--dk-text-muted); font-size: 0.78rem; }
.plan-actions { display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 0.35rem; animation: prov-panel-in 0.3s 0.2s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both; }
.plan-loading {
  display: flex; align-items: flex-start; gap: 0.85rem;
  padding: 0.85rem 0.15rem 0.35rem;
  min-height: 4.5rem;
}
.plan-loading .dk-spinner {
  flex-shrink: 0; margin-top: 0.15rem;
  width: 1.35rem; height: 1.35rem;
  border: 2px solid color-mix(in srgb, var(--dk-accent, #6366f1) 20%, transparent);
  border-top-color: var(--dk-accent, #6366f1);
  border-radius: 50%;
  animation: plan-spin 0.65s linear infinite;
}
@keyframes plan-spin { to { transform: rotate(360deg); } }
.plan-loading__text {
  display: flex; flex-direction: column; gap: 0.2rem;
  font-size: 0.85rem; color: var(--dk-text-muted);
}
.plan-loading__text strong {
  color: inherit; font-weight: 650; font-size: 0.9rem;
}
.plan-diff { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.plan-diff__chip {
  font-size: 0.72rem; font-weight: 650; border-radius: 999px;
  padding: 0.15rem 0.55rem; border: 1px solid var(--dk-border-soft);
  animation: chip-pop 0.3s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
}
.plan-diff__chip:nth-child(1) { animation-delay: 0.05s; }
.plan-diff__chip:nth-child(2) { animation-delay: 0.1s; }
.plan-diff__chip:nth-child(3) { animation-delay: 0.15s; }
.plan-diff__chip:nth-child(4) { animation-delay: 0.2s; }
@keyframes chip-pop {
  from { opacity: 0; transform: scale(0.8); }
  to { opacity: 1; transform: scale(1); }
}
.plan-diff__chip--create { color: #15803d; border-color: color-mix(in srgb, #22c55e 45%, var(--dk-border-soft)); }
.plan-diff__chip--update { color: #1d4ed8; border-color: color-mix(in srgb, #3b82f6 45%, var(--dk-border-soft)); }
.plan-diff__chip--noop { color: var(--dk-text-muted); }
.plan-diff__chip--destroy { color: #b91c1c; border-color: color-mix(in srgb, #ef4444 45%, var(--dk-border-soft)); opacity: 0.85; }
.chip--warn {
  border-color: color-mix(in srgb, #f59e0b 50%, var(--dk-border-soft));
  color: #b45309;
}
.inv-hint { margin: 0 0 0.65rem; }
.inv-kind {
  font-size: 0.72rem; font-weight: 650; text-transform: uppercase;
  letter-spacing: 0.04em; color: var(--dk-text-muted);
}
.inv-name { font-size: 0.82rem; }
.inv-ref { font-size: 0.72rem; word-break: break-all; opacity: 0.85; }
:global(.btn-primary--reconcile) {
  /* still primary when reconciling existing infra */
}

</style>
