<script lang="ts">
  // Generated by VEIL

  interface Props {
    value: string;
    label: string;
  }
  let { value, label }: Props = $props();
</script>

<div class="stat-card card"><span class="value">{value}</span><span class="label">{label}</span></div>


<style>
.stat-card {
  padding: 1.15rem 1.2rem;
  display: flex;
  flex-direction: column;
  gap: 4px;
  animation: dk-fade-up 0.45s var(--dk-ease-out, ease) both;
}
.value { font-size: 1.75rem; font-weight: 700; color: var(--accent); letter-spacing: -0.02em; }
.label { font-size: 0.72rem; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.06em; }

</style>
