<script lang="ts">
  // Generated by VEIL

  import PageHeader from './PageHeader.svelte';
  import ViewModeToggle from './ViewModeToggle.svelte';
  import EmptyState from './EmptyState.svelte';
  import EntityIdentity from './EntityIdentity.svelte';
  import StatusPill from './StatusPill.svelte';

  interface Props {
    title?: string;
    description?: string;
    items?: Record<string, unknown>[];
    loading?: boolean;
    error?: string;
    view_mode?: string;
    default_layout?: string;
    show_avatar?: boolean;
    empty_title?: string;
    empty_description?: string;
    empty_action_href?: string;
    empty_action_label?: string;
    primary_href?: string;
    primary_label?: string;
    item_href_template?: string;
    layout_storage_key?: string;
    columns?: Record<string, unknown>[];
    tile?: Snippet | null;
    row?: Snippet | null;
    header_actions?: Snippet | null;
    agent?: Record<string, unknown>;
  }
  let { title = "", description = "", items = [], loading = false, error = "", view_mode = "both", default_layout = "tiles", show_avatar = true, empty_title = "Nothing here yet", empty_description = "", empty_action_href = "", empty_action_label = "", primary_href = "", primary_label = "", item_href_template = "", layout_storage_key = "", columns = [], tile, row, header_actions, agent = {  } }: Props = $props();

  let layout: string = $state("tiles");

  let show_toggle = $derived(view_mode === "both");
  let veil_agent = $derived({ version: 1, role: "collection", product: agent, runtime: { loading, error, layout, view_mode, primary_href, primary_label, item_href_template, layout_storage_key } });

    $effect(() => { // init_layout
      if (view_mode === "tiles") {
        layout = "tiles";
      } else {
        if (view_mode === "list") {
          layout = "list";
        } else {
          if (layout_storage_key !== "") {
            let saved = (localStorage.getItem(layout_storage_key) ?? default_layout);
            if (saved === "list") {
              layout = "list";
            } else {
              if (saved === "tiles") {
                layout = "tiles";
              } else {
                layout = default_layout;
              };
            };
          } else {
            layout = default_layout;
          };
        };
      };
    });
    $effect(() => { // sync_layout
      if (view_mode === "tiles") {
        layout = "tiles";
      };
      if (view_mode === "list") {
        layout = "list";
      };
    });
    $effect(() => { // persist_layout
      if (layout_storage_key !== "") {
        if (view_mode === "both") {
          if (layout === "tiles") {
            localStorage.setItem(layout_storage_key, "tiles");
          };
          if (layout === "list") {
            localStorage.setItem(layout_storage_key, "list");
          };
        };
      };
    });
</script>

{#if true}
{@const list = Array.isArray(items) ? items : []}
{@const colDefs = (Array.isArray(columns) ? columns : []).map((c) => typeof c === 'string' ? { label: c } : c)}
{@const headerLabels = colDefs.map((c) => c.label)}
{@const autoCells = colDefs.length > 0 && colDefs.every((c) => !!c.key)}
{@const displayValue = (item, key) => {
  if (!key || item == null || typeof item !== 'object') return '';
  const v = item[key];
  if (v == null) return '';
  const raw = typeof v === 'object' ? JSON.stringify(v) : String(v);
  if (/^\d{4}-\d{2}-\d{2}T/.test(raw)) return raw.slice(0, 10);
  return raw;
}}
{@const identitySubtitle = (item, col) => {
  if (!col) return '';
  const start = col.subtitleKey ? displayValue(item, col.subtitleKey) : '';
  const end = col.subtitleEndKey ? displayValue(item, col.subtitleEndKey) : '';
  if (start && end) return `${start} → ${end}`;
  return start || end || '';
}}
{@const tileExtra = (cols, first) => {
  const used = new Set([first?.key, first?.subtitleKey, first?.subtitleEndKey].filter(Boolean));
  return cols.filter((col) => col.key && !used.has(col.key) && (col.cell === 'pill' || col.showOnTile === true));
}}
{@const itemHref = (item) => {
  if (!item_href_template) return '';
  const fieldStr = (v) => {
    if (v == null) return '';
    if (typeof v === 'object' && v.value != null) return String(v.value);
    if (typeof v === 'object') return '';
    return String(v);
  };
  // Prefer explicit id, then nested id.value, then slug (common for repos).
  const id =
    fieldStr(item?.id) ||
    fieldStr(item?.slug) ||
    '';
  return String(item_href_template).replace(/\{([a-zA-Z_][a-zA-Z0-9_]*)\}/g, (_, key) => {
    if (key === 'id') return id;
    return fieldStr(item?.[key]);
  });
}}
{@const goItem = (item, e) => {
  const href = itemHref(item);
  if (!href) return;
  const t = e?.target;
  if (t?.closest?.('a, button, input, select, textarea, [role="menu"], [role="menuitem"], .dk-tile__actions, .dk-table__actions, .dk-ctx')) return;
  window.location.href = href;
}}
<div
  class="dk-collection"
  data-veil-role="collection"
  data-veil-agent={JSON.stringify({
    ...veil_agent,
    runtime: {
      ...veil_agent.runtime,
      itemCount: list.length,
      emptyActionHref: empty_action_href || primary_href || undefined,
      state: loading ? 'loading' : error ? 'error' : list.length === 0 ? 'empty' : 'ready',
    },
  })}
>
  {#if title || primary_label || show_toggle || header_actions}
    <PageHeader {title} description={description}>
      {#snippet actions()}
        {#if show_toggle}
          <ViewModeToggle bind:mode={layout} />
        {/if}
        {#if header_actions}
          {@render header_actions()}
        {/if}
        {#if primary_href && primary_label}
          <a href={primary_href} class="btn-primary">
            <span aria-hidden="true">+</span>
            {primary_label}
          </a>
        {/if}
      {/snippet}
    </PageHeader>
  {/if}

  {#if error}
    <p class="dk-error">{error}</p>
  {:else if loading}
    <div class="card dk-loading">
      <div class="dk-spinner" aria-hidden="true"></div>
      <span>Loading…</span>
    </div>
  {:else if list.length === 0}
    <EmptyState
      title={empty_title}
      description={empty_description}
      action_href={empty_action_href || primary_href}
      action_label={empty_action_label || primary_label}
    />
  {:else if layout === 'tiles'}
    <div class="dk-tile-grid">
      {#each list as item, i (i)}
        {@const href = itemHref(item)}
        <div
          class="card dk-tile"
          class:dk-tile--clickable={!!href}
          style="--dk-i: {i}"
          role={href ? 'link' : undefined}
          tabindex={href ? 0 : undefined}
          data-href={href || undefined}
          onclick={(e) => goItem(item, e)}
          onkeydown={(e) => {
            if (!href) return;
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              goItem(item, e);
            }
          }}
        >
          {#if tile}
            {@render tile(item)}
          {:else if autoCells}
            {@const first = colDefs[0]}
            {@const tileCols = tileExtra(colDefs.slice(1), first)}
            <div class="dk-tile__row">
              {#if first?.cell === 'identity' || first?.key === 'name'}
                <EntityIdentity
                  name={displayValue(item, first.key)}
                  subtitle={identitySubtitle(item, first)}
                  show_avatar={first.showAvatar ?? show_avatar}
                />
              {:else}
                <p class="dk-tile__name">{displayValue(item, first?.key)}</p>
              {/if}
            </div>
            {#if tileCols.length > 0}
              <div class="dk-tile__badges">
                {#each tileCols as col}
                  {#if col.cell === 'pill'}
                    <StatusPill label={displayValue(item, col.key)} pill_map={col.pillMap ?? {}} />
                  {:else}
                    <span class="dk-tile__meta">{displayValue(item, col.key) || '—'}</span>
                  {/if}
                {/each}
              </div>
            {/if}
          {:else}
            <pre class="dk-fallback">{JSON.stringify(item, null, 2)}</pre>
          {/if}
        </div>
      {/each}
    </div>
  {:else}
    <div class="card dk-table-wrap">
      <table class="dk-table">
        {#if headerLabels.length > 0}
          <thead>
            <tr>
              {#each headerLabels as col}
                <th>{col}</th>
              {/each}
            </tr>
          </thead>
        {/if}
        <tbody>
          {#each list as item, i (i)}
            {@const href = itemHref(item)}
            <tr
              class="dk-table__row"
              class:dk-table__row--clickable={!!href}
              style="--dk-i: {i}"
              role={href ? 'link' : undefined}
              tabindex={href ? 0 : undefined}
              data-href={href || undefined}
              onclick={(e) => goItem(item, e)}
              onkeydown={(e) => {
                if (!href) return;
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  goItem(item, e);
                }
              }}
            >
              {#if row}
                {@render row(item)}
              {:else if autoCells}
                {#each colDefs as col}
                  <td>
                    {#if col.cell === 'pill'}
                      <StatusPill label={displayValue(item, col.key)} pill_map={col.pillMap ?? {}} />
                    {:else if col.cell === 'identity' || (col.key === 'name' && col.cell !== 'text')}
                      <EntityIdentity name={displayValue(item, col.key)} show_avatar={col.showAvatar ?? show_avatar} size="sm" />
                    {:else}
                      <span class="dk-tile__meta">{displayValue(item, col.key) || '—'}</span>
                    {/if}
                  </td>
                {/each}
              {:else}
                <td colspan={headerLabels.length || 1}>
                  <pre class="dk-fallback">{JSON.stringify(item, null, 2)}</pre>
                </td>
              {/if}
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>
{/if}


<style>
  /* TODO: Add component styles */
</style>
