<script lang="ts">
  // Generated by VEIL

  import FormProgress from './FormProgress.svelte';

  interface Props {
    title: string;
    subtitle?: string;
    back_href?: string;
    back_behavior?: string;
    mode?: string;
    submit_label?: string;
    saving_label?: string;
    saving?: boolean;
    show_submit?: boolean;
    required_values?: string[];
    on_submit?: () => void | null;
    loading?: boolean;
    loading_label?: string;
    error?: string;
    children?: Snippet | null;
    header_actions?: Snippet | null;
    footer?: Snippet | null;
    agent?: Record<string, unknown>;
    form_id?: string;
  }
  let { title, subtitle = "", back_href = "..", back_behavior = "href", mode = "create", submit_label = "Create", saving_label = "Creating…", saving = false, show_submit = true, required_values = [], on_submit, loading = false, loading_label = "Loading…", error = "", children, header_actions, footer, agent = {  }, form_id = "create-project" }: Props = $props();

  let veil_agent = $derived({ version: 1, role: "create-form", product: agent, runtime: { saving, loading, error, submit_label, back_href, back_behavior, mode, show_submit } });

  function handle_submit() {
    if (saving === false) {
      if (on_submit !== null) {
        on_submit();
      };
    };
  }
</script>

<div
  id={form_id}
  class="dk-page-shell dk-create-shell"
  data-veil-role={mode === "edit" ? "edit-form" : "create-form"}
  data-veil-agent={JSON.stringify(veil_agent)}
>
  <header class="dk-page-shell__header dk-create-shell__header">
    <div class="dk-page-shell__left dk-create-shell__left">
      <a
        href={back_href}
        class="btn-ghost dk-page-shell__back dk-create-shell__back"
        aria-label="Back"
        data-veil-action="back"
        data-back-behavior={back_behavior}
        onclick={(e) => {
          if (back_behavior !== 'history') return;
          if (typeof window === 'undefined') return;
          // Prefer prior page in this tab (list vs detail). Fall back to href.
          if (window.history.length > 1) {
            e.preventDefault();
            window.history.back();
          }
        }}
      >
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
          <path d="M19 12H5M12 19l-7-7 7-7" />
        </svg>
      </a>
      <div>
        <h1 class="dk-page-shell__title dk-create-shell__title">{title}</h1>
        {#if subtitle}
          <p class="dk-page-shell__subtitle dk-create-shell__subtitle">{subtitle}</p>
        {/if}
      </div>
    </div>
    <div class="dk-page-shell__header-actions">
      {#if header_actions}
        {@render header_actions()}
      {/if}
      {#if show_submit}
        <FormProgress
          required_values={required_values}
          submit_label={submit_label}
          saving_label={saving_label}
          saving={saving}
          on_submit={on_submit}
        />
      {/if}
    </div>
  </header>
  <div class="dk-page-shell__body dk-create-shell__body">
    {#if loading}
      <div class="card dk-loading">
        <div class="dk-spinner" aria-hidden="true"></div>
        <span>{loading_label}</span>
      </div>
    {:else}
      {#if error}
        <p class="dk-error">{error}</p>
      {/if}
      {#if children}
        {@render children()}
      {/if}
      {#if footer}
        <div class="dk-page-shell__footer" data-veil-slot="footer">
          {@render footer()}
        </div>
      {/if}
    {/if}
  </div>
</div>


<style>
  /* TODO: Add component styles */
</style>
