<script lang="ts">
  // Generated by VEIL

  import PageHeader from './PageHeader.svelte';
  import FormSection from './FormSection.svelte';
  import FormField from './FormField.svelte';

  let artifactId: string = $state('');
  let targetType: string = $state('');
  let deploying: boolean = $state(false);
  let error: string = $state('');

  async function triggerDeploy() {
    deploying = true;
    error = "";
    await (async () => { const __r = await fetch("/api/deploy", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ artifact_id: artifactId, target: targetType }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    deploying = false;
  }
</script>

<div class="deploy">
  <PageHeader title="Deploy" description="Publish an artifact to a target runtime." />
  <form class="dk-form card" onsubmit={(e) => { e.preventDefault(); triggerDeploy(); }}>
    <FormSection title="Artifact" columns={1}>
      <FormField label="Artifact ID" bind:value={artifactId} required={true} placeholder="art_…" />
      <div class="dk-field">
        <label class="dk-field__label" for="deploy-target">Target</label>
        <div class="dk-field__control">
          <select id="deploy-target" bind:value={targetType}>
            <option value="lambda">Lambda</option>
            <option value="container">Container</option>
          </select>
        </div>
      </div>
    </FormSection>
    {#if error}
      <p class="dk-error">{error}</p>
    {/if}
    <div class="actions">
      <button type="submit" class="btn-primary" disabled={deploying || !artifactId}>
        {deploying ? "Deploying…" : "Deploy"}
      </button>
    </div>
  </form>
</div>


<style>
.deploy { max-width: 42rem; animation: dk-fade-in var(--dk-dur-slow, 420ms) var(--dk-ease-out, ease) both; }
.dk-form { padding: 1.25rem 1.35rem 1.5rem; display: flex; flex-direction: column; gap: 1.5rem; }
.actions { display: flex; justify-content: flex-end; }

</style>
