<script lang="ts">
  // Generated by VEIL

  interface Props {
    title?: string;
    columns?: number;
    children?: Snippet | null;
  }
  let { title = "", columns = 1, children }: Props = $props();
</script>

<section class="dk-form-section">
  {#if title}
    <h2 class="dk-form-section__title">{title}</h2>
  {/if}
  <div
    class="dk-form-section__grid"
    class:dk-form-section__grid--1={columns === 1}
    class:dk-form-section__grid--2={columns === 2}
    class:dk-form-section__grid--3={columns === 3}
  >
    {#if children}
      {@render children()}
    {/if}
  </div>
</section>


<style>
  /* TODO: Add component styles */
</style>
