<script lang="ts">
  // Generated by VEIL

  import { goto } from '$app/navigation';
  import CreateFormShell from './CreateFormShell.svelte';
  import FormSection from './FormSection.svelte';
  import FormField from './FormField.svelte';

  let name: string = $state('');
  let description: string = $state('');
  let submitting: boolean = $state(false);
  let error: string = $state('');

  async function submit() {
    if (submitting) return;
    submitting = true;
    error = '';
    try {
      const r = await fetch('/api/ux/create_project', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: name.trim(),
          description: description.trim() || undefined,
          open: true,
          open_ide: true,
        }),
      });
      const text = await r.text();
      const data = text ? JSON.parse(text) : {};
      if (!r.ok) throw new Error(data.error || data.summary || text || `HTTP ${r.status}`);
      const slug = String(data.slug || data.id || name.trim().toLowerCase().replace(/\s+/g, '-'));
      const path = String(data.path || `/projects/${encodeURIComponent(slug)}/ide`);
      await goto(path);
    } catch (e: unknown) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      submitting = false;
    }
  }
</script>

<CreateFormShell
  title="Create project"
  subtitle="New repository on this runtime"
  back_href="/projects"
  mode="create"
  form_id="create-project"
  submit_label="Create"
  saving_label="Creating…"
  saving={submitting}
  required_values={[name]}
  on_submit={() => { void submit(); }}
  error={error}
  agent={{
    intent: 'create-project',
    entity: 'Repo',
    entityLabel: 'Project',
    notes: [
      'Required: name. Optional: description.',
      'On submit: POST /api/ux/create_project then open the IDE.',
      'Agent Present fills these fields and clicks Create.',
    ],
    api: { create: 'POST /api/ux/create_project' },
  }}
>
  <FormSection title="Basics" columns={1}>
    <FormField id="name" label="Name" bind:value={name} required={true} placeholder="My project" />
    <FormField id="description" label="Description" bind:value={description} input_type="textarea" placeholder="Optional" />
  </FormSection>
</CreateFormShell>


<style>
  /* TODO: Add component styles */
</style>
