<script lang="ts">
  // Generated by VEIL

  import CreateFormShell from './CreateFormShell.svelte';
  import FormSection from './FormSection.svelte';
  import FormField from './FormField.svelte';

  let name: string = $state('');
  let description: string = $state('');
  let submitting: boolean = $state(false);
  let error: string = $state('');

   $effect(() => { // submit
  void (async () => {
        if (submitting === true) {
          error = "";
          await (async () => { const __r = await fetch("/api/repos", { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, description }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
          submitting = false;
          (window.location.href = "/projects");
        };
  })();
    });
</script>

<CreateFormShell
  title="Create project"
  subtitle="New repository on this runtime"
  back_href="/projects"
  mode="create"
  submit_label="Create"
  saving_label="Creating…"
  saving={submitting}
  required_values={[name]}
  on_submit={() => { submitting = true; }}
  error={error}
  agent={{
    intent: 'create-project',
    entity: 'Repo',
    entityLabel: 'Project',
    notes: [
      'Required: name. Optional: description.',
      'On submit: POST /api/repos then navigate to /projects.',
    ],
    api: { create: 'POST /api/repos' },
  }}
>
  <FormSection title="Basics" columns={1}>
    <FormField label="Name" bind:value={name} required={true} placeholder="My project" />
    <FormField label="Description" bind:value={description} input_type="textarea" placeholder="Optional" />
  </FormSection>
</CreateFormShell>


<style>
  /* TODO: Add component styles */
</style>
