<script lang="ts">
  // Generated by VEIL

  import PullRequestDetailView from './PullRequestDetailView.svelte';
</script>

<PullRequestDetailView />


<style>
  /* TODO: Add component styles */
</style>
