<script lang="ts">
  // Generated by VEIL

  import PullRequestCreateView from './PullRequestCreateView.svelte';
</script>

<PullRequestCreateView />


<style>
  /* TODO: Add component styles */
</style>
