<script lang="ts">
  // Generated by VEIL

  interface Props {
    title: string;
    subtitle?: string;
    steps?: string[];
    current_step?: number;
    children?: Snippet | null;
    footer?: Snippet | null;
    on_close?: () => void | null;
    agent?: Record<string, unknown>;
  }
  let { title, subtitle = "", steps = [], current_step = 1, children, footer, on_close, agent = {  } }: Props = $props();

  let veil_agent = $derived({ version: 1, role: "wizard", product: agent, runtime: { title, current_step } });

  function request_close() {
    if (on_close !== null) {
      on_close();
    };
  }
</script>

<section
  class="dk-wizard"
  data-veil-role="wizard"
  data-veil-agent={JSON.stringify(veil_agent)}
>
  <header class="dk-wizard__head">
    <div class="dk-wizard__titles">
      <h2 class="dk-wizard__title">{title}</h2>
      {#if subtitle}
        <p class="dk-wizard__subtitle">{subtitle}</p>
      {/if}
    </div>
    {#if on_close}
      <button type="button" class="btn-ghost dk-wizard__close" aria-label="Close" onclick={request_close} data-veil-action="close">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
          <path d="M18 6 6 18M6 6l12 12" />
        </svg>
      </button>
    {/if}
  </header>
  {#if steps && steps.length > 0}
    <ol class="dk-wizard__steps" aria-label="Wizard progress">
      {#each steps as label, i}
        <li
          class="dk-wizard__step"
          class:dk-wizard__step--done={i + 1 < current_step}
          class:dk-wizard__step--current={i + 1 === current_step}
        >
          <span class="dk-wizard__step-num">{i + 1}</span>
          <span class="dk-wizard__step-label">{label}</span>
        </li>
      {/each}
    </ol>
  {/if}
  <div class="dk-wizard__body">
    {#if children}
      {@render children()}
    {/if}
  </div>
  {#if footer}
    <footer class="dk-wizard__footer">
      {@render footer()}
    </footer>
  {/if}
</section>


<style>
.dk-wizard {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 1.25rem 1.35rem 1.35rem;
  border-radius: var(--dk-radius, 0.85rem);
  border: 1px solid rgba(115, 115, 115, 0.35);
  background:
    linear-gradient(155deg, rgba(255, 255, 255, 0.03) 0%, transparent 42%),
    linear-gradient(165deg, var(--dk-surface, #1a1a1a) 0%, var(--dk-bg, #0f0f0f) 100%);
  box-shadow: var(--dk-shadow-sm, 0 2px 8px rgba(0, 0, 0, 0.28));
}
.dk-wizard__head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1rem;
}
.dk-wizard__title {
  margin: 0;
  font-size: 1.1rem;
  font-weight: 700;
  letter-spacing: -0.02em;
  color: var(--dk-text, #e5e5e5);
}
.dk-wizard__subtitle {
  margin: 0.3rem 0 0;
  font-size: 0.84rem;
  color: var(--dk-text-muted, #9ca3af);
  line-height: 1.45;
}
.dk-wizard__close { padding: 0.4rem !important; flex-shrink: 0; }
.dk-wizard__steps {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem 0.5rem;
}
.dk-wizard__step {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.28rem 0.65rem 0.28rem 0.35rem;
  border-radius: 999px;
  font-size: 0.75rem;
  color: var(--dk-text-muted, #9ca3af);
  border: 1px solid transparent;
  background: rgba(255, 255, 255, 0.03);
}
.dk-wizard__step-num {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1.25rem;
  height: 1.25rem;
  border-radius: 999px;
  font-size: 0.68rem;
  font-weight: 700;
  background: rgba(255, 255, 255, 0.08);
  color: var(--dk-text-muted, #9ca3af);
}
.dk-wizard__step--done {
  color: var(--dk-brand-light, #a3a3a3);
}
.dk-wizard__step--done .dk-wizard__step-num {
  background: rgba(115, 115, 115, 0.25);
  color: var(--dk-brand-light, #a3a3a3);
}
.dk-wizard__step--current {
  color: var(--dk-text, #e5e5e5);
  border-color: rgba(115, 115, 115, 0.45);
  background: rgba(115, 115, 115, 0.12);
  font-weight: 600;
}
.dk-wizard__step--current .dk-wizard__step-num {
  background: var(--dk-brand, #737373);
  color: #fff;
}
.dk-wizard__body {
  display: flex;
  flex-direction: column;
  gap: 0.9rem;
  padding: 1.05rem 1.1rem;
  border-radius: var(--dk-radius-sm, 0.55rem);
  border: 1px solid rgba(115, 115, 115, 0.22);
  background: rgba(115, 115, 115, 0.05);
}
.dk-wizard__footer {
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
  flex-wrap: wrap;
  padding-top: 0.15rem;
}

</style>
