<script lang="ts">
  // Generated by VEIL

  interface Props {
    value?: string;
    options?: Record<string, unknown>[];
    columns?: number;
    layout?: string;
    agent?: Record<string, unknown>;
  }
  let { value = $bindable(""), options = [], columns = 2, layout = "row", agent = {  } }: Props = $props();

  let veil_agent = $derived({ version: 1, role: "choice-cards", product: agent, runtime: { value } });
</script>

<div
  class="dk-choice-cards"
  class:dk-choice-cards--1={columns === 1}
  class:dk-choice-cards--2={columns === 2}
  class:dk-choice-cards--3={columns === 3}
  class:dk-choice-cards--4={columns === 4}
  class:dk-choice-cards--tile={layout === 'tile'}
  role="radiogroup"
  data-veil-role="choice-cards"
  data-veil-agent={JSON.stringify(veil_agent)}
>
  {#each (options || []) as opt}
    <button
      type="button"
      role="radio"
      class="dk-choice-card"
      class:dk-choice-card--on={value === opt.value}
      class:dk-choice-card--tile={layout === 'tile'}
      aria-checked={value === opt.value}
      onclick={() => { value = opt.value; }}
      data-veil-action="choose"
      data-value={opt.value}
    >
      <span class="dk-choice-card__icon" data-icon={opt.icon || 'hand'} aria-hidden="true">
        {#if opt.icon === 'calendar'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <rect x="3" y="5" width="18" height="16" rx="2.5" />
            <path d="M3 10h18" />
            <path d="M8 3v4M16 3v4" />
            <circle cx="8.5" cy="15" r="1" fill="currentColor" stroke="none" />
            <circle cx="12" cy="15" r="1" fill="currentColor" stroke="none" />
            <circle cx="15.5" cy="15" r="1" fill="currentColor" stroke="none" />
          </svg>
        {:else if opt.icon === 'clock'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="9" />
            <path d="M12 7v5.2l3.2 1.8" />
          </svg>
        {:else if opt.icon === 'bolt'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M13 2 4 14h7l-1 8 9-12h-7l1-8z" />
          </svg>
        {:else if opt.icon === 'spark'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 2.5 13.6 8.2 19 9.5l-4.2 3.8 1.2 5.7L12 16.2 7.9 19l1.2-5.7L4.9 9.5l5.4-1.3L12 2.5z" />
          </svg>
        {:else if opt.icon === 'list'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9 6h12M9 12h12M9 18h12" />
            <circle cx="4.5" cy="6" r="1.25" fill="currentColor" stroke="none" />
            <circle cx="4.5" cy="12" r="1.25" fill="currentColor" stroke="none" />
            <circle cx="4.5" cy="18" r="1.25" fill="currentColor" stroke="none" />
          </svg>
        {:else if opt.icon === 'repeat'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M17 2.5 20.5 6 17 9.5" />
            <path d="M4 12V9a5 5 0 0 1 5-5h11.5" />
            <path d="M7 21.5 3.5 18 7 14.5" />
            <path d="M20 12v3a5 5 0 0 1-5 5H3.5" />
          </svg>
        {:else if opt.icon === 'play'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="9" />
            <path d="M10 9.2v5.6L15.2 12 10 9.2z" fill="currentColor" stroke="none" />
          </svg>
        {:else if opt.icon === 'sun'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="4" />
            <path d="M12 2.5v2.2M12 19.3v2.2M2.5 12h2.2M19.3 12h2.2M5.2 5.2l1.6 1.6M17.2 17.2l1.6 1.6M18.8 5.2l-1.6 1.6M6.8 17.2l-1.6 1.6" />
          </svg>
        {:else if opt.icon === 'moon'}
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M20 14.2A8.2 8.2 0 0 1 9.8 4 7.4 7.4 0 1 0 20 14.2z" />
          </svg>
        {:else}
          <!-- hand / manual default -->
          <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round">
            <path d="M8 13.2V6.2a1.6 1.6 0 0 1 3.2 0v5.4" />
            <path d="M11.2 11.4V4.3a1.6 1.6 0 0 1 3.2 0v7.1" />
            <path d="M14.4 10.8V5.8a1.6 1.6 0 0 1 3.2 0V14" />
            <path d="M17.6 13v-1.2a1.6 1.6 0 0 1 3.2 0V16a6.2 6.2 0 0 1-6.2 6.2h-1.4a7.2 7.2 0 0 1-5.8-2.9L5 15.7a1.85 1.85 0 0 1 2.8-2.4l1.4 1.2" />
          </svg>
        {/if}
      </span>
      <span class="dk-choice-card__text">
        <strong class="dk-choice-card__label">{opt.label}</strong>
        {#if opt.description}
          <span class="dk-choice-card__desc">{opt.description}</span>
        {/if}
      </span>
      <span class="dk-choice-card__check" aria-hidden="true">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="M5 13l4 4L19 7" />
        </svg>
      </span>
    </button>
  {/each}
</div>


<style>
.dk-choice-cards {
  display: grid;
  gap: 0.85rem;
  grid-template-columns: 1fr;
}
@media (min-width: 560px) {
  .dk-choice-cards--2 { grid-template-columns: 1fr 1fr; }
  .dk-choice-cards--3 { grid-template-columns: 1fr 1fr 1fr; }
  .dk-choice-cards--4 { grid-template-columns: 1fr 1fr 1fr 1fr; }
}
.dk-choice-card {
  position: relative;
  display: flex;
  align-items: flex-start;
  gap: 0.95rem;
  text-align: left;
  padding: 1.05rem 1.15rem;
  border-radius: 0.85rem;
  border: 1px solid var(--dk-border, #2a2a38);
  background:
    linear-gradient(160deg, rgba(255, 255, 255, 0.035) 0%, transparent 50%),
    rgba(18, 18, 26, 0.78);
  color: var(--dk-text, #f4f5f7);
  cursor: pointer;
  font-family: inherit;
  overflow: hidden;
  transition:
    border-color 0.16s ease,
    background 0.16s ease,
    box-shadow 0.2s ease,
    transform 0.16s ease;
}
.dk-choice-card:hover {
  border-color: rgba(255, 255, 255, 0.16);
  background:
    linear-gradient(160deg, rgba(255, 255, 255, 0.05) 0%, transparent 50%),
    rgba(26, 26, 38, 0.95);
  transform: translateY(-2px);
  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.28);
}
.dk-choice-card:focus-visible {
  outline: 2px solid rgba(20, 135, 112, 0.55);
  outline-offset: 2px;
}
.dk-choice-card--on {
  border-color: rgba(20, 135, 112, 0.65);
  background:
    linear-gradient(145deg, rgba(20, 135, 112, 0.2) 0%, rgba(20, 135, 112, 0.06) 55%, transparent 100%),
    rgba(14, 22, 20, 0.9);
  box-shadow:
    0 0 0 1px rgba(20, 135, 112, 0.28),
    0 12px 30px rgba(20, 135, 112, 0.12);
}
.dk-choice-card--tile {
  flex-direction: column;
  align-items: stretch;
  gap: 0.85rem;
  min-height: 9.5rem;
  padding: 1.2rem 1.15rem 1.15rem;
}
.dk-choice-card__icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 3rem;
  height: 3rem;
  flex-shrink: 0;
  border-radius: 0.9rem;
  background:
    radial-gradient(circle at 30% 25%, rgba(255, 255, 255, 0.12), transparent 55%),
    rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: var(--dk-text-muted, #9ca3af);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.06);
}
.dk-choice-card--tile .dk-choice-card__icon {
  width: 3.35rem;
  height: 3.35rem;
  border-radius: 1rem;
}
.dk-choice-card--on .dk-choice-card__icon {
  background:
    radial-gradient(circle at 30% 25%, rgba(255, 255, 255, 0.18), transparent 55%),
    linear-gradient(145deg, rgba(31, 168, 138, 0.35), rgba(20, 135, 112, 0.18));
  border-color: rgba(20, 135, 112, 0.45);
  color: #5eead4;
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.12),
    0 6px 16px rgba(20, 135, 112, 0.18);
}
.dk-choice-card__text {
  display: flex;
  flex-direction: column;
  gap: 0.32rem;
  min-width: 0;
  padding-top: 0.15rem;
  flex: 1;
}
.dk-choice-card--tile .dk-choice-card__text {
  padding-top: 0;
}
.dk-choice-card__label {
  font-size: 1.02rem;
  font-weight: 700;
  letter-spacing: -0.02em;
  line-height: 1.25;
}
.dk-choice-card__desc {
  font-size: 0.8rem;
  line-height: 1.45;
  color: var(--dk-text-muted, #9ca3af);
  font-weight: 400;
}
.dk-choice-card__check {
  position: absolute;
  top: 0.7rem;
  right: 0.7rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1.35rem;
  height: 1.35rem;
  border-radius: 999px;
  background: var(--dk-brand, #148770);
  color: #fff;
  opacity: 0;
  transform: scale(0.7);
  transition: opacity 0.15s ease, transform 0.15s ease;
}
.dk-choice-card--on .dk-choice-card__check {
  opacity: 1;
  transform: scale(1);
}

</style>
