<script lang="ts">
  // Generated by VEIL

  interface Props {
    id?: string;
    label: string;
    value?: string;
    empty_label?: string;
    mono?: boolean;
    pre?: boolean;
    children?: Snippet | null;
    agent?: Record<string, unknown>;
  }
  let { id = "", label, value = "", empty_label = "—", mono = false, pre = false, children, agent = {  } }: Props = $props();

  let is_empty = $derived(value === "");
  let veil_agent = $derived({ version: 1, role: "detail-field", product: agent, runtime: { id, label, empty: is_empty, mono, pre } });
</script>

{#if true}
{@const display = (value === undefined || value === null || String(value).trim() === '') ? empty_label : String(value)}
{@const empty = (value === undefined || value === null || String(value).trim() === '')}
<div
  class="dk-field dk-detail-field"
  data-veil-role="detail-field"
  data-veil-field={id || undefined}
  data-veil-agent={JSON.stringify(veil_agent)}
>
  <span class="dk-field__label">{label}</span>
  {#if children}
    <div class="dk-detail__value" class:dk-detail__value--muted={empty} class:dk-detail__mono={mono}>
      {@render children()}
    </div>
  {:else if pre && !empty}
    <pre class="dk-detail__pre" class:dk-detail__mono={mono}>{value}</pre>
  {:else}
    <p
      class="dk-detail__value"
      class:dk-detail__value--muted={empty}
      class:dk-detail__mono={mono}
    >{display}</p>
  {/if}
</div>
{/if}


<style>
  /* TODO: Add component styles */
</style>
