<script lang="ts">
  // Generated by VEIL

  interface Props {
    required_values?: string[];
    submit_label?: string;
    saving_label?: string;
    saving?: boolean;
    on_submit?: () => void | null;
  }
  let { required_values = [], submit_label = "Create", saving_label = "Saving…", saving = false, on_submit }: Props = $props();

  function handle_submit() {
    if (saving === false) {
      if (on_submit !== null) {
        on_submit();
      };
    };
  }
</script>

{#if true}
{@const total = Array.isArray(required_values) ? required_values.length : 0}
{@const filled = Array.isArray(required_values) ? required_values.filter((v) => v != null && String(v).trim() !== '').length : 0}
{@const isComplete = total === 0 || filled >= total}
{@const pct = total === 0 ? 100 : Math.round((filled / total) * 100)}
<div class="dk-form-progress">
  <div class="dk-form-progress__meter">
    <div class="dk-form-progress__track" aria-hidden="true">
      <div
        class="dk-form-progress__fill"
        class:dk-form-progress__fill--ready={isComplete}
        style="width: {pct}%"
      ></div>
    </div>
    <span class:dk-form-progress__ready={isComplete}>
      {isComplete ? 'Ready' : `${filled}/${total}`}
    </span>
  </div>
  <button
    type="button"
    class="btn-primary"
    class:dk-form-progress__submit--ready={isComplete}
    disabled={saving || !isComplete}
    onclick={() => { if (!saving && isComplete && on_submit) on_submit(); }}
  >
    {saving ? saving_label : submit_label}
  </button>
</div>
{/if}


<style>
  /* TODO: Add component styles */
</style>
