<script lang="ts">
  // Generated by VEIL

  interface Props {
    name: string;
    branch: string;
    updatedAt: string;
    id: string;
  }
  let { name, branch, updatedAt, id }: Props = $props();
</script>

<a href="/projects/{id}" class="project-card"><div class="name">{name}</div><div class="meta">{branch} · {updatedAt}</div></a>


<style>
.project-card { padding: 14px 18px; border: 1px solid var(--vr-border); border-radius: 6px; text-decoration: none; color: var(--vr-text); }
.project-card:hover { border-color: var(--vr-accent); }

</style>
