<script lang="ts">
  // Generated by VEIL

  import DetailShell from './DetailShell.svelte';
  import StatusPill from './StatusPill.svelte';
  import FormField from './FormField.svelte';

  let id = $state<string>('');
  let pr = $state<Record<string, unknown>>(undefined as any);
  let diff = $state<Record<string, unknown>>(undefined as any);
  let comments = $state<Record<string, unknown>[]>([]);
  let approvals = $state<Record<string, unknown>[]>([]);
  let ci = $state<Record<string, unknown>>(undefined as any);
  let loading = $state<boolean>(false);
  let error = $state<string>('');
  let loaded = $state<boolean>(false);
  let action_busy = $state<boolean>(false);
  let new_comment = $state<string>('');
  let new_comment_path = $state<string>('');
  let comment_submitting = $state<boolean>(false);

    $effect(() => { // init
      loading = true;
      error = "";
      loaded = false;
      action_busy = false;
      new_comment = "";
      new_comment_path = "";
      comment_submitting = false;
      pr = {  };
      diff = {  };
      comments = [];
      approvals = [];
      ci = {  };
      id = pr_id_from_path();
    });
   $effect(() => { // load_detail
  void (async () => {
        if (id !== "") {
          if (loaded === false) {
            loading = true;
            error = "";
            let detail = await (async () => { const __u = new URL(`/api/pull_requests/${id}`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            pr = detail;
            let diff_resp = await (async () => { const __u = new URL(`/api/pull_requests/${id}/diff`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            diff = diff_resp;
            let comments_resp = await (async () => { const __u = new URL(`/api/pull_requests/${id}/comments`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            comments = comments_resp;
            let approvals_resp = await (async () => { const __u = new URL(`/api/pull_requests/${id}/approvals`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            approvals = approvals_resp;
            let ci_resp = await (async () => { const __u = new URL(`/api/pull_requests/${id}/ci`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost'); const __p = {} as Record<string, unknown>; for (const [k, v] of Object.entries(__p)) { if (v != null && v !== '') __u.searchParams.set(k, String(v)); } const __r = await fetch(__u.toString()); if (!__r.ok) throw new Error(await __r.text()); return await __r.json(); })();
            ci = ci_resp;
            loading = false;
            loaded = true;
          };
        };
  })();
    });
    $effect(() => { // do_action
      if (action_busy === true) {
        loaded = false;
        action_busy = false;
      };
    });
   $effect(() => { // submit_comment
  void (async () => {
        if (comment_submitting === true) {
          error = "";
          await (async () => { const __r = await fetch(`/api/pull_requests/${id}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body: new_comment, construct_path: new_comment_path || null }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
          new_comment = "";
          new_comment_path = "";
          comment_submitting = false;
          loaded = false;
        };
  })();
    });

  async function submit_for_review() {
    error = "";
    await (async () => { const __r = await fetch(`/api/pull_requests/${id}/submit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({  }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    loaded = false;
  }
  async function approve() {
    error = "";
    await (async () => { const __r = await fetch(`/api/pull_requests/${id}/approve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({  }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    loaded = false;
  }
  async function request_pr_changes() {
    error = "";
    await (async () => { const __r = await fetch(`/api/pull_requests/${id}/request-changes`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ comment: "Changes requested" }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    loaded = false;
  }
  async function merge() {
    error = "";
    await (async () => { const __r = await fetch(`/api/pull_requests/${id}/merge`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({  }) }); if (!__r.ok) throw new Error(await __r.text()); const __t = await __r.text(); return __t ? JSON.parse(__t) : null; })();
    loaded = false;
  }

  // raw script block (escape hatch — prefer VEIL fn/effect)
  function pr_id_from_path(): string {
  if (typeof window === 'undefined') return '';
  const p = window.location.pathname;
  const t = p.endsWith('/') ? p.slice(0, -1) : p;
  const parts = t.split('/').filter(Boolean);
  const i = parts.indexOf('changes');
  if (i >= 0 && parts[i + 1]) return parts[i + 1];
  return '';
  }
  function diff_kind_class(kind: string): string {
  if (kind === 'Added') return 'dk-diff-added';
  if (kind === 'Modified') return 'dk-diff-modified';
  if (kind === 'Removed') return 'dk-diff-removed';
  if (kind === 'Moved') return 'dk-diff-modified';
  return '';
  }
  function diff_kind_icon(kind: string): string {
  if (kind === 'Added') return '+';
  if (kind === 'Modified') return '~';
  if (kind === 'Removed') return '−';
  if (kind === 'Moved') return '→';
  return '•';
  }
  function status_variant(status: string): string {
  if (status === 'Draft') return 'neutral';
  if (status === 'ReadyForReview') return 'info';
  if (status === 'Approved') return 'success';
  if (status === 'ChangesRequested') return 'warning';
  if (status === 'Merged') return 'success';
  if (status === 'Rejected') return 'error';
  return 'neutral';
  }
  function status_label(status: string): string {
  if (status === 'ReadyForReview') return 'Ready for Review';
  if (status === 'ChangesRequested') return 'Changes Requested';
  return status;
  }
  function ci_variant(status: string): string {
  if (status === 'Passed') return 'success';
  if (status === 'Failed') return 'error';
  if (status === 'Running') return 'info';
  return 'warning';
  }

</script>

<DetailShell
  title={pr?.title ? String(pr.title) : 'Pull Request'}
  subtitle={pr?.source_branch ? String(pr.source_branch) : ''}
  back_href="/pulls"
  loading={loading}
  error={error}
  agent={{ intent: 'view-pull-request', entity: 'PullRequest', entityLabel: 'Pull Request', itemId: id }}
>
  {#snippet header_actions()}
    {#if pr?.status === 'Draft'}
      <button type="button" class="btn-primary" onclick={() => { submit_for_review(); }}>
        Submit for Review
      </button>
    {/if}
    {#if pr?.status === 'ReadyForReview'}
      <button type="button" class="btn-outline" onclick={() => { request_pr_changes(); }}>
        Request Changes
      </button>
      <button type="button" class="btn-primary" onclick={() => { approve(); }}>
        Approve
      </button>
    {/if}
    {#if pr?.status === 'Approved'}
      <button type="button" class="btn-primary" onclick={() => { merge(); }}>
        Merge
      </button>
    {/if}
  {/snippet}
  {#snippet summary()}
    <div class="pr-detail-header card">
      <div class="pr-detail-meta">
        <StatusPill label={status_label(String(pr?.status ?? 'Draft'))} variant={status_variant(String(pr?.status ?? 'Draft'))} />
        <span class="pr-detail-author">by <strong>{pr?.author ? String(pr.author) : '—'}</strong></span>
        <span class="pr-detail-branch"><code>{pr?.source_branch ? String(pr.source_branch) : '—'}</code> → <code>{pr?.target_branch ? String(pr.target_branch) : 'main'}</code></span>
      </div>
      {#if pr?.description}
        <p class="pr-detail-desc">{String(pr.description)}</p>
      {/if}
    </div>
  {/snippet}

  <!-- Structural Diff Section -->
  <div class="pr-section">
    <h2 class="pr-section-title">Structural Diff</h2>
    {#if diff?.description}
      <p class="pr-diff-summary">{String(diff.description)}</p>
    {/if}
    {#if diff?.changes && diff.changes.length > 0}
      <div class="pr-diff-stats">
        <span class="plan-diff__chip plan-diff__chip--create">{diff.additions ?? 0} additions</span>
        <span class="plan-diff__chip plan-diff__chip--destroy">{diff.removals ?? 0} removals</span>
        <span class="plan-diff__chip">{diff.files_changed ?? 0} files</span>
      </div>
      <ul class="pr-diff-list">
        {#each diff.changes as change, i}
          <li class={`pr-diff-item ${diff_kind_class(String(change.kind))}`} style="--dk-i: {i}">
            <span class="pr-diff-icon" aria-hidden="true">{diff_kind_icon(String(change.kind))}</span>
            <div class="pr-diff-body">
              <span class="pr-diff-detail">{change.detail ? String(change.detail) : String(change.path)}</span>
              {#if change.construct_type}
                <span class="pr-diff-construct">{String(change.construct_type)}</span>
              {/if}
              <span class="pr-diff-path">{String(change.path)}</span>
            </div>
          </li>
        {/each}
      </ul>
    {:else if !loading}
      <p class="hint">No structural changes detected.</p>
    {/if}
  </div>

  <!-- Sidebar metadata -->
  <div class="pr-meta-grid">
    <div class="pr-meta-card card">
      <h3 class="pr-meta-title">Metadata</h3>
      <dl class="pr-meta-dl">
        <dt>Jira Ticket</dt>
        <dd>{pr?.jira_ticket ? String(pr.jira_ticket) : '—'}</dd>
        <dt>Created</dt>
        <dd>{pr?.created_at ? String(pr.created_at).slice(0, 10) : '—'}</dd>
        <dt>Updated</dt>
        <dd>{pr?.updated_at ? String(pr.updated_at).slice(0, 10) : '—'}</dd>
        {#if pr?.merged_at}
          <dt>Merged</dt>
          <dd>{String(pr.merged_at).slice(0, 10)} by {pr?.merged_by ? String(pr.merged_by) : '—'}</dd>
        {/if}
      </dl>
    </div>
    <div class="pr-meta-card card">
      <h3 class="pr-meta-title">CI Status</h3>
      {#if ci?.status}
        <StatusPill label={String(ci.status)} variant={ci_variant(String(ci.status))} />
        {#if ci?.duration_ms}
          <span class="pr-ci-duration">{Math.round(Number(ci.duration_ms) / 1000)}s</span>
        {/if}
        {#if ci?.error_summary}
          <p class="pr-ci-error">{String(ci.error_summary)}</p>
        {/if}
      {:else}
        <span class="hint">No CI run yet</span>
      {/if}
    </div>
    <div class="pr-meta-card card">
      <h3 class="pr-meta-title">Approvals</h3>
      {#if approvals.length > 0}
        <ul class="pr-approvals-list">
          {#each approvals as a}
            <li>
              <strong>{a.reviewer ? String(a.reviewer) : '—'}</strong>
              <span class="pr-approval-date">{a.approved_at ? String(a.approved_at).slice(0, 10) : ''}</span>
            </li>
          {/each}
        </ul>
      {:else}
        <span class="hint">No approvals yet</span>
      {/if}
    </div>
  </div>

  <!-- Comments Section -->
  <div class="pr-section">
    <h2 class="pr-section-title">Comments</h2>
    {#if comments.length > 0}
      <div class="pr-comments">
        {#each comments as comment, i}
          <div class="pr-comment" style="--dk-i: {i}">
            {#if comment.construct_path}
              <span class="pr-comment-anchor">{String(comment.construct_path)}</span>
            {/if}
            <div class="pr-comment-header">
              <strong>{comment.author ? String(comment.author) : '—'}</strong>
              <span class="pr-comment-time">{comment.created_at ? String(comment.created_at).slice(0, 16).replace('T', ' ') : ''}</span>
              {#if comment.resolved}
                <span class="pr-comment-resolved">✓ Resolved</span>
              {/if}
            </div>
            <p class="pr-comment-body">{comment.body ? String(comment.body) : ''}</p>
          </div>
        {/each}
      </div>
    {:else if !loading}
      <p class="hint">No comments yet.</p>
    {/if}

    <!-- Add comment form -->
    {#if pr?.status && pr.status !== 'Merged' && pr.status !== 'Rejected' && pr.status !== 'Closed'}
      <div class="pr-comment-form card">
        <FormField label="Construct path (optional)" bind:value={new_comment_path} placeholder="e.g. HandleListProviders.authorize" />
        <FormField label="Comment" bind:value={new_comment} input_type="textarea" placeholder="Add a comment…" />
        <div class="pr-comment-form-actions">
          <button
            type="button"
            class="btn-primary"
            disabled={comment_submitting || !new_comment}
            onclick={() => { comment_submitting = true; }}
          >
            {comment_submitting ? 'Posting…' : 'Post Comment'}
          </button>
        </div>
      </div>
    {/if}
  </div>
</DetailShell>


<style>
.pr-detail-header { padding: 1rem 1.15rem; display: flex; flex-direction: column; gap: 0.65rem; margin-bottom: 0.5rem; }
.pr-detail-meta { display: flex; flex-wrap: wrap; align-items: center; gap: 0.65rem; }
.pr-detail-author { font-size: 0.85rem; color: var(--dk-text-muted); }
.pr-detail-branch { font-size: 0.82rem; color: var(--dk-text-muted); }
.pr-detail-branch code { font-size: 0.78rem; padding: 0.1rem 0.4rem; background: var(--dk-surface-2, rgba(0,0,0,0.05)); border-radius: 0.3rem; }
.pr-detail-desc { margin: 0; font-size: 0.9rem; color: var(--text-dim); }
.pr-section { margin-top: 1.5rem; }
.pr-section-title {
  font-size: 0.72rem; font-weight: 650; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--dk-text-muted); margin: 0 0 0.75rem;
}
.pr-diff-summary {
  font-size: 0.95rem; font-weight: 600; color: var(--text);
  margin: 0 0 0.75rem; padding: 0.65rem 0.85rem;
  background: color-mix(in srgb, var(--accent) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--accent) 20%, transparent);
  border-radius: 0.5rem;
}
.pr-diff-stats { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-bottom: 0.75rem; }
.pr-diff-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.25rem; }
.pr-diff-item {
  display: flex; align-items: flex-start; gap: 0.65rem;
  padding: 0.55rem 0.85rem; border-radius: 0.45rem;
  border-left: 3px solid var(--dk-border-soft);
  background: var(--dk-surface-2, rgba(0,0,0,0.02));
  animation: prov-step-in 0.25s var(--dk-ease-out, cubic-bezier(0.16, 1, 0.3, 1)) both;
  animation-delay: calc(var(--dk-i, 0) * 40ms + 50ms);
}
.pr-diff-item.dk-diff-added { border-left-color: var(--dk-green, #22c55e); background: color-mix(in srgb, var(--dk-green, #22c55e) 6%, transparent); }
.pr-diff-item.dk-diff-modified { border-left-color: var(--dk-amber, #f59e0b); background: color-mix(in srgb, var(--dk-amber, #f59e0b) 6%, transparent); }
.pr-diff-item.dk-diff-removed { border-left-color: var(--dk-red, #ef4444); background: color-mix(in srgb, var(--dk-red, #ef4444) 6%, transparent); }
.pr-diff-icon {
  font-weight: 700; font-size: 0.9rem; min-width: 1.1rem; text-align: center;
  color: var(--dk-text-muted); line-height: 1.4;
}
.dk-diff-added .pr-diff-icon { color: var(--dk-green, #22c55e); }
.dk-diff-modified .pr-diff-icon { color: var(--dk-amber, #f59e0b); }
.dk-diff-removed .pr-diff-icon { color: var(--dk-red, #ef4444); }
.pr-diff-body { display: flex; flex-direction: column; gap: 0.1rem; }
.pr-diff-detail { font-size: 0.85rem; font-weight: 550; }
.pr-diff-construct { font-size: 0.72rem; color: var(--dk-text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
.pr-diff-path { font-size: 0.75rem; color: var(--dk-text-muted); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
.pr-meta-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-top: 1.5rem; }
@media (max-width: 900px) { .pr-meta-grid { grid-template-columns: 1fr; } }
.pr-meta-card { padding: 0.85rem 1rem; display: flex; flex-direction: column; gap: 0.5rem; }
.pr-meta-title {
  font-size: 0.72rem; font-weight: 650; text-transform: uppercase;
  letter-spacing: 0.06em; color: var(--dk-text-muted); margin: 0;
}
.pr-meta-dl { margin: 0; display: grid; grid-template-columns: auto 1fr; gap: 0.25rem 0.75rem; font-size: 0.82rem; }
.pr-meta-dl dt { color: var(--dk-text-muted); font-weight: 550; }
.pr-meta-dl dd { margin: 0; }
.pr-ci-duration { font-size: 0.8rem; color: var(--dk-text-muted); }
.pr-ci-error { font-size: 0.82rem; color: var(--dk-red, #ef4444); margin: 0.25rem 0 0; }
.pr-approvals-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.35rem; font-size: 0.85rem; }
.pr-approval-date { font-size: 0.75rem; color: var(--dk-text-muted); margin-left: 0.5rem; }
.pr-comments { display: flex; flex-direction: column; gap: 0.5rem; margin-bottom: 1rem; }
.pr-comment {
  padding: 0.75rem 1rem; border-radius: 0.5rem;
  background: var(--dk-surface-2, rgba(0,0,0,0.03));
  border: 1px solid var(--dk-border-soft, var(--border));
  animation: dk-fade-up 0.3s var(--dk-ease-out, ease) both;
  animation-delay: calc(var(--dk-i, 0) * 40ms);
}
.pr-comment-anchor {
  display: inline-block; font-size: 0.68rem; font-weight: 650;
  padding: 0.1rem 0.45rem; border-radius: 999px; margin-bottom: 0.35rem;
  background: color-mix(in srgb, var(--accent) 12%, transparent);
  border: 1px solid color-mix(in srgb, var(--accent) 25%, transparent);
  color: var(--accent);
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}
.pr-comment-header { display: flex; align-items: center; gap: 0.5rem; font-size: 0.82rem; }
.pr-comment-time { font-size: 0.75rem; color: var(--dk-text-muted); }
.pr-comment-resolved { font-size: 0.72rem; color: var(--dk-green, #22c55e); font-weight: 600; }
.pr-comment-body { margin: 0.35rem 0 0; font-size: 0.88rem; line-height: 1.5; }
.pr-comment-form { padding: 0.85rem 1rem; display: flex; flex-direction: column; gap: 0.65rem; }
.pr-comment-form-actions { display: flex; justify-content: flex-end; }
.hint { color: var(--dk-text-muted); font-size: 0.9rem; margin: 0; }

</style>
