<script lang="ts">
  // Generated by VEIL

  interface Props {
    label?: string;
    status?: string;
    variant?: string;
    pill_map?: Record<string, unknown>;
  }
  let { label = "", status = "", variant = "", pill_map = {  } }: Props = $props();

  let text = $derived(label);
</script>

{#if true}
{@const text = (label || status || '').toString()}
{@const key = text.trim().toLowerCase()}
{@const defaults = { draft: 'info', active: 'success', completed: 'success', archived: 'neutral', enabled: 'success', disabled: 'warning' }}
{@const resolved = variant || (pill_map && (pill_map[text] || pill_map[key])) || defaults[key] || 'info'}
{@const cls = resolved === 'success' ? 'badge-success' : resolved === 'warning' ? 'badge-warning' : resolved === 'error' ? 'badge-error' : resolved === 'neutral' ? 'badge-neutral' : 'badge-info'}
{#if text}
  <span class="badge {cls}">{text}</span>
{/if}
{/if}


<style>
  /* TODO: Add component styles */
</style>
