<script lang="ts">
  // Generated by VEIL

  interface Props {
    mode?: string;
    class_name?: string;
  }
  let { mode = $bindable("tiles"), class_name = "" }: Props = $props();

  function set_tiles() {
    mode = "tiles";
  }
  function set_list() {
    mode = "list";
  }
</script>

<div class="dk-view-toggle {class_name}" role="group" aria-label="View mode">
  <button
    type="button"
    class="dk-view-toggle__btn"
    class:dk-view-toggle__btn--active={mode === 'tiles'}
    title="Tile view"
    aria-pressed={mode === 'tiles'}
    onclick={set_tiles}
  >
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
      <rect x="3" y="3" width="7" height="7" rx="1" />
      <rect x="14" y="3" width="7" height="7" rx="1" />
      <rect x="3" y="14" width="7" height="7" rx="1" />
      <rect x="14" y="14" width="7" height="7" rx="1" />
    </svg>
  </button>
  <button
    type="button"
    class="dk-view-toggle__btn"
    class:dk-view-toggle__btn--active={mode === 'list'}
    title="List view"
    aria-pressed={mode === 'list'}
    onclick={set_list}
  >
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
      <line x1="8" y1="6" x2="21" y2="6" />
      <line x1="8" y1="12" x2="21" y2="12" />
      <line x1="8" y1="18" x2="21" y2="18" />
      <line x1="3" y1="6" x2="3.01" y2="6" />
      <line x1="3" y1="12" x2="3.01" y2="12" />
      <line x1="3" y1="18" x2="3.01" y2="18" />
    </svg>
  </button>
</div>


<style>
  /* TODO: Add component styles */
</style>
