//! Kotlin backend (PAR-006 / PAR-012) — core-shape + basic body lowering.

use veil_ir::ast::*;
use veil_ir::layer::{LayerRegistry, Shape};

use crate::capabilities::Feature;

pub struct KotlinProject {
    pub files: Vec<KotlinFile>,
}

pub struct KotlinFile {
    pub path: String,
    pub content: String,
}

/// PAR-012: claim body lowering for core expr subset.
pub fn kotlin_supported_features() -> std::collections::HashSet<Feature> {
    use Feature::*;
    [FnBodyLowering, MatchExpr, TryOperator, AwaitExpr]
        .into_iter()
        .collect()
}

pub fn generate_kotlin(solution: &Solution, _registry: &LayerRegistry) -> KotlinProject {
    let mut body =
        String::from("// Generated by VEIL Kotlin (PAR-012) — experimental, not production\n\n");
    body.push_str(&format!(
        "package {}\n\n",
        to_snake(&solution.name).replace('_', ".")
    ));

    for item in &solution.items {
        let TopLevelItem::Construct(c) = item else {
            continue;
        };
        emit_construct(&mut body, c);
    }
    for item in &solution.items {
        if let TopLevelItem::Function(f) = item {
            emit_fn(&mut body, f);
        }
        if let TopLevelItem::Construct(c) = item {
            walk_fns(&mut body, c);
        }
    }

    KotlinProject {
        files: vec![KotlinFile {
            path: format!("src/main/kotlin/{}/Generated.kt", solution.name),
            content: body,
        }],
    }
}

fn walk_fns(out: &mut String, c: &Construct) {
    for f in &c.fns {
        emit_fn(out, f);
    }
    for child in &c.children {
        walk_fns(out, child);
    }
}

fn emit_construct(out: &mut String, c: &Construct) {
    match c.shape {
        Shape::Struct => {
            out.push_str(&format!("data class {}(\n", c.name));
            let mut fields = Vec::new();
            for f in &c.fields {
                fields.push(format!(
                    "    val {}: {}",
                    f.name,
                    type_to_kotlin(&f.type_expr)
                ));
            }
            for b in &c.blocks {
                for f in &b.fields {
                    fields.push(format!(
                        "    val {}: {}",
                        f.name,
                        type_to_kotlin(&f.type_expr)
                    ));
                }
            }
            out.push_str(&fields.join(",\n"));
            out.push_str("\n)\n\n");
        }
        Shape::Enum => {
            out.push_str(&format!("enum class {} {{\n", c.name));
            for v in &c.variants {
                out.push_str(&format!("    {},\n", v));
            }
            out.push_str("}\n\n");
        }
        Shape::Mod | Shape::Group => {
            for child in &c.children {
                emit_construct(out, child);
            }
        }
        _ => {}
    }
}

fn emit_fn(out: &mut String, f: &FnDef) {
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, type_to_kotlin(&p.type_expr)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = f
        .return_type
        .as_ref()
        .map(|t| format!(": {}", type_to_kotlin(t)))
        .unwrap_or_else(|| ": Unit".into());
    out.push_str(&format!("fun {}({}){} {{\n", f.name, params, ret));
    if f.body.is_empty() {
        out.push_str("    TODO(\"VEIL Kotlin: empty body\")\n");
    } else {
        for e in &f.body {
            out.push_str(&format!("    {}\n", stmt_to_kotlin(e)));
        }
    }
    out.push_str("}\n\n");
}

fn stmt_to_kotlin(e: &Expr) -> String {
    match e {
        Expr::Assign(name, val, _) => format!("val {} = {}", name, expr_to_kotlin(val)),
        Expr::MutAssign(name, val, _) => format!("var {} = {}", name, expr_to_kotlin(val)),
        Expr::Return(inner) => format!("return {}", expr_to_kotlin(inner)),
        other => expr_to_kotlin(other),
    }
}

fn expr_to_kotlin(e: &Expr) -> String {
    match e {
        Expr::Ident(n) => n.clone(),
        Expr::IntLit(n) => format!("{n}L"),
        Expr::FloatLit(f) => format!("{f}"),
        Expr::BoolLit(b) => b.to_string(),
        Expr::StringLit(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Expr::FieldAccess(base, field) => format!("{}.{}", expr_to_kotlin(base), field),
        Expr::BinaryOp(b) => format!(
            "({} {} {})",
            expr_to_kotlin(&b.left),
            bin_op_kt(&b.op),
            expr_to_kotlin(&b.right)
        ),
        Expr::UnaryOp(u) => format!(
            "({}{})",
            match u.op {
                UnaryOp::Not => "!",
                UnaryOp::Neg => "-",
            },
            expr_to_kotlin(&u.expr)
        ),
        Expr::Return(inner) => format!("return {}", expr_to_kotlin(inner)),
        Expr::StructLit(name, fields) => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{} = {}", k, expr_to_kotlin(v)))
                .collect();
            format!("{}({})", name, parts.join(", "))
        }
        Expr::IfExpr(i) => {
            let mut s = format!("if ({}) {{\n", expr_to_kotlin(&i.condition));
            for st in &i.then_body {
                s.push_str(&format!("        {}\n", stmt_to_kotlin(st)));
            }
            s.push_str("    }");
            if let Some(eb) = &i.else_body {
                s.push_str(" else {\n");
                for st in eb {
                    s.push_str(&format!("        {}\n", stmt_to_kotlin(st)));
                }
                s.push_str("    }");
            }
            s
        }
        Expr::Match(scrut, arms) => {
            let mut s = format!("when ({}) {{\n", expr_to_kotlin(scrut));
            for arm in arms {
                s.push_str(&format!("        {} -> {{\n", arm.pattern));
                for st in &arm.body {
                    s.push_str(&format!("            {}\n", stmt_to_kotlin(st)));
                }
                s.push_str("        }\n");
            }
            s.push_str("    }");
            s
        }
        Expr::Try(inner) => format!("{}.getOrThrow()", expr_to_kotlin(inner)),
        Expr::Await(inner) => expr_to_kotlin(inner),
        Expr::Call(c) => {
            let args: Vec<String> = c.args.iter().map(expr_to_kotlin).collect();
            let base = if let Some(recv) = &c.receiver {
                format!("{}.{}", expr_to_kotlin(recv), c.method)
            } else if c.target.is_empty() {
                c.method.clone()
            } else if c.method.is_empty() {
                c.target.clone()
            } else {
                format!("{}.{}", c.target, c.method)
            };
            format!("{}({})", base, args.join(", "))
        }
        Expr::ArrayLit(items) => {
            let parts: Vec<String> = items.iter().map(expr_to_kotlin).collect();
            format!("listOf({})", parts.join(", "))
        }
        _ => "TODO(\"VEIL Kotlin: expr not lowered\")".into(),
    }
}

fn bin_op_kt(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::LtEq => "<=",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

fn type_to_kotlin(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(n) => match n.as_str() {
            "Str" => "String".into(),
            "Int" => "Long".into(),
            "F64" => "Double".into(),
            "Bool" => "Boolean".into(),
            "UUID" | "Id" => "String".into(),
            other => other.to_string(),
        },
        TypeExpr::Optional(inner) => format!("{}?", type_to_kotlin(inner)),
        TypeExpr::List(inner) => format!("List<{}>", type_to_kotlin(inner)),
        TypeExpr::Result(Some(inner)) => format!("Result<{}>", type_to_kotlin(inner)),
        TypeExpr::Result(None) => "Result<Unit>".into(),
        _ => "Any".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_res_types() {
        assert_eq!(type_to_kotlin(&TypeExpr::Result(None)), "Result<Unit>");
        assert_eq!(type_to_kotlin(&TypeExpr::Named("Bool".into())), "Boolean");
    }

    #[test]
    fn lowers_return() {
        let e = Expr::Return(Box::new(Expr::IntLit(3)));
        assert_eq!(stmt_to_kotlin(&e), "return 3L");
    }
}

fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
