//! Kotlin backend spike (PAR-006) — minimal core-shape lowering.
//! Not production-ready; capability matrix keeps advanced features closed.

use veil_ir::ast::*;
use veil_ir::layer::{LayerRegistry, Shape};

use crate::capabilities::Feature;

pub struct KotlinProject {
    pub files: Vec<KotlinFile>,
}

pub struct KotlinFile {
    pub path: String,
    pub content: String,
}

pub fn kotlin_supported_features() -> std::collections::HashSet<Feature> {
    use Feature::*;
    [MatchExpr, TryOperator, AwaitExpr].into_iter().collect()
}

pub fn generate_kotlin(solution: &Solution, _registry: &LayerRegistry) -> KotlinProject {
    let mut body = String::from("// Generated by VEIL Kotlin spike (PAR-006) — not production-ready\n\n");
    body.push_str(&format!("package {}\n\n", to_snake(&solution.name).replace('_', ".")));

    for item in &solution.items {
        let TopLevelItem::Construct(c) = item else {
            continue;
        };
        emit_construct(&mut body, c);
    }
    for item in &solution.items {
        if let TopLevelItem::Function(f) = item {
            emit_fn(&mut body, f);
        }
        if let TopLevelItem::Construct(c) = item {
            walk_fns(&mut body, c);
        }
    }

    KotlinProject {
        files: vec![KotlinFile {
            path: format!("src/main/kotlin/{}/Generated.kt", solution.name),
            content: body,
        }],
    }
}

fn walk_fns(out: &mut String, c: &Construct) {
    for f in &c.fns {
        emit_fn(out, f);
    }
    for child in &c.children {
        walk_fns(out, child);
    }
}

fn emit_construct(out: &mut String, c: &Construct) {
    match c.shape {
        Shape::Struct => {
            out.push_str(&format!("data class {}(\n", c.name));
            let mut fields = Vec::new();
            for f in &c.fields {
                fields.push(format!(
                    "    val {}: {}",
                    f.name,
                    type_to_kotlin(&f.type_expr)
                ));
            }
            for b in &c.blocks {
                for f in &b.fields {
                    fields.push(format!(
                        "    val {}: {}",
                        f.name,
                        type_to_kotlin(&f.type_expr)
                    ));
                }
            }
            out.push_str(&fields.join(",\n"));
            out.push_str("\n)\n\n");
        }
        Shape::Enum => {
            out.push_str(&format!("enum class {} {{\n", c.name));
            for v in &c.variants {
                out.push_str(&format!("    {},\n", v));
            }
            out.push_str("}\n\n");
        }
        Shape::Mod | Shape::Group => {
            for child in &c.children {
                emit_construct(out, child);
            }
        }
        _ => {}
    }
}

fn emit_fn(out: &mut String, f: &FnDef) {
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, type_to_kotlin(&p.type_expr)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = f
        .return_type
        .as_ref()
        .map(|t| format!(": {}", type_to_kotlin(t)))
        .unwrap_or_else(|| ": Unit".into());
    out.push_str(&format!("fun {}({}){} {{\n", f.name, params, ret));
    out.push_str("    TODO(\"VEIL Kotlin spike: body not lowered\")\n");
    out.push_str("}\n\n");
}

fn type_to_kotlin(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(n) => match n.as_str() {
            "Str" => "String".into(),
            "Int" => "Long".into(),
            "F64" => "Double".into(),
            "Bool" => "Boolean".into(),
            "UUID" | "Id" => "String".into(),
            other => other.to_string(),
        },
        TypeExpr::Optional(inner) => format!("{}?", type_to_kotlin(inner)),
        TypeExpr::List(inner) => format!("List<{}>", type_to_kotlin(inner)),
        TypeExpr::Result(Some(inner)) => format!("Result<{}>", type_to_kotlin(inner)),
        TypeExpr::Result(None) => "Result<Unit>".into(),
        _ => "Any".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_res_types() {
        assert_eq!(type_to_kotlin(&TypeExpr::Result(None)), "Result<Unit>");
        assert_eq!(
            type_to_kotlin(&TypeExpr::Result(Some(Box::new(TypeExpr::Named(
                "Str".into()
            ))))),
            "Result<String>"
        );
        assert_eq!(type_to_kotlin(&TypeExpr::Named("Bool".into())), "Boolean");
    }
}

fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
