//! Swift backend (PAR-005 / PAR-011) — core-shape + basic body lowering.
//!
//! Not production-ready; advanced features still fail closed via capabilities.

use veil_ir::ast::*;
use veil_ir::layer::{LayerRegistry, Shape};

use crate::capabilities::Feature;

pub struct SwiftProject {
    pub files: Vec<SwiftFile>,
}

pub struct SwiftFile {
    pub path: String,
    pub content: String,
}

/// PAR-011: claim body lowering for core expr subset.
pub fn swift_supported_features() -> std::collections::HashSet<Feature> {
    use Feature::*;
    [FnBodyLowering, MatchExpr, TryOperator].into_iter().collect()
}

pub fn generate_swift(solution: &Solution, _registry: &LayerRegistry) -> SwiftProject {
    let mut body =
        String::from("// Generated by VEIL Swift (PAR-011) — experimental, not production\n\n");
    body.push_str("import Foundation\n\n");

    for item in &solution.items {
        let TopLevelItem::Construct(c) = item else {
            continue;
        };
        emit_construct(&mut body, c);
    }

    for item in &solution.items {
        if let TopLevelItem::Function(f) = item {
            emit_fn(&mut body, f);
        }
        if let TopLevelItem::Construct(c) = item {
            for f in &c.fns {
                emit_fn(&mut body, f);
            }
            for child in &c.children {
                walk_fns(&mut body, child);
            }
        }
    }

    SwiftProject {
        files: vec![SwiftFile {
            path: format!("Sources/{}/Generated.swift", solution.name),
            content: body,
        }],
    }
}

fn walk_fns(out: &mut String, c: &Construct) {
    for f in &c.fns {
        emit_fn(out, f);
    }
    for child in &c.children {
        walk_fns(out, child);
    }
}

fn emit_construct(out: &mut String, c: &Construct) {
    match c.shape {
        Shape::Struct => {
            out.push_str(&format!("struct {}: Codable {{\n", c.name));
            for f in &c.fields {
                out.push_str(&format!(
                    "    var {}: {}\n",
                    f.name,
                    type_to_swift(&f.type_expr)
                ));
            }
            for b in &c.blocks {
                for f in &b.fields {
                    out.push_str(&format!(
                        "    var {}: {}\n",
                        f.name,
                        type_to_swift(&f.type_expr)
                    ));
                }
            }
            out.push_str("}\n\n");
        }
        Shape::Enum => {
            out.push_str(&format!("enum {} {{\n", c.name));
            for v in &c.variants {
                out.push_str(&format!("    case {}\n", to_camel(v)));
            }
            out.push_str("}\n\n");
        }
        Shape::Mod | Shape::Group => {
            for child in &c.children {
                emit_construct(out, child);
            }
        }
        _ => {}
    }
}

fn emit_fn(out: &mut String, f: &FnDef) {
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, type_to_swift(&p.type_expr)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = f
        .return_type
        .as_ref()
        .map(|t| format!(" -> {}", type_to_swift(t)))
        .unwrap_or_default();
    out.push_str(&format!("func {}({}){} {{\n", f.name, params, ret));
    if f.body.is_empty() {
        out.push_str("    fatalError(\"VEIL Swift: empty body\")\n");
    } else {
        for e in &f.body {
            out.push_str(&format!("    {}\n", stmt_to_swift(e)));
        }
    }
    out.push_str("}\n\n");
}

fn stmt_to_swift(e: &Expr) -> String {
    match e {
        Expr::Assign(name, val, _) => format!("let {} = {}", name, expr_to_swift(val)),
        Expr::MutAssign(name, val, _) => format!("var {} = {}", name, expr_to_swift(val)),
        Expr::Return(inner) => format!("return {}", expr_to_swift(inner)),
        other => expr_to_swift(other),
    }
}

fn expr_to_swift(e: &Expr) -> String {
    match e {
        Expr::Ident(n) => n.clone(),
        Expr::IntLit(n) => n.to_string(),
        Expr::FloatLit(f) => format!("{f}"),
        Expr::BoolLit(b) => b.to_string(),
        Expr::StringLit(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Expr::FieldAccess(base, field) => format!("{}.{}", expr_to_swift(base), field),
        Expr::BinaryOp(b) => format!(
            "({} {} {})",
            expr_to_swift(&b.left),
            bin_op_swift(&b.op),
            expr_to_swift(&b.right)
        ),
        Expr::UnaryOp(u) => format!(
            "({}{})",
            match u.op {
                UnaryOp::Not => "!",
                UnaryOp::Neg => "-",
            },
            expr_to_swift(&u.expr)
        ),
        Expr::Return(inner) => format!("return {}", expr_to_swift(inner)),
        Expr::StructLit(name, fields) => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{}: {}", k, expr_to_swift(v)))
                .collect();
            format!("{}({})", name, parts.join(", "))
        }
        Expr::IfExpr(i) => {
            let mut s = format!("if {} {{\n", expr_to_swift(&i.condition));
            for st in &i.then_body {
                s.push_str(&format!("        {}\n", stmt_to_swift(st)));
            }
            s.push_str("    }");
            if let Some(eb) = &i.else_body {
                s.push_str(" else {\n");
                for st in eb {
                    s.push_str(&format!("        {}\n", stmt_to_swift(st)));
                }
                s.push_str("    }");
            }
            s
        }
        Expr::Match(scrut, arms) => {
            let mut s = format!("switch {} {{\n", expr_to_swift(scrut));
            for arm in arms {
                s.push_str(&format!("    case {}:\n", arm.pattern));
                for st in &arm.body {
                    s.push_str(&format!("        {}\n", stmt_to_swift(st)));
                }
            }
            s.push_str("    }");
            s
        }
        Expr::Try(inner) => format!("try {}", expr_to_swift(inner)),
        Expr::Await(inner) => expr_to_swift(inner), // sync subset
        Expr::Call(c) => {
            let args: Vec<String> = c.args.iter().map(expr_to_swift).collect();
            let base = if let Some(recv) = &c.receiver {
                format!("{}.{}", expr_to_swift(recv), c.method)
            } else if c.target.is_empty() {
                c.method.clone()
            } else if c.method.is_empty() {
                c.target.clone()
            } else {
                format!("{}.{}", c.target, c.method)
            };
            format!("{}({})", base, args.join(", "))
        }
        Expr::ArrayLit(items) => {
            let parts: Vec<String> = items.iter().map(expr_to_swift).collect();
            format!("[{}]", parts.join(", "))
        }
        _ => "/* unsupported expr */ fatalError(\"VEIL Swift: expr not lowered\")".into(),
    }
}

fn bin_op_swift(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::LtEq => "<=",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

fn type_to_swift(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(n) => match n.as_str() {
            "Str" => "String".into(),
            "Int" => "Int".into(),
            "F64" => "Double".into(),
            "Bool" => "Bool".into(),
            "UUID" | "Id" => "UUID".into(),
            other => other.to_string(),
        },
        TypeExpr::Optional(inner) => format!("{}?", type_to_swift(inner)),
        TypeExpr::List(inner) => format!("[{}]", type_to_swift(inner)),
        TypeExpr::Result(Some(inner)) => format!("Result<{}, Error>", type_to_swift(inner)),
        TypeExpr::Result(None) => "Result<Void, Error>".into(),
        _ => "Any".into(),
    }
}

fn to_camel(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_res_types() {
        assert_eq!(
            type_to_swift(&TypeExpr::Result(None)),
            "Result<Void, Error>"
        );
        assert_eq!(type_to_swift(&TypeExpr::Named("Int".into())), "Int");
    }

    #[test]
    fn lowers_binary_and_return() {
        let e = Expr::Return(Box::new(Expr::BinaryOp(BinaryOpExpr {
            left: Box::new(Expr::Ident("a".into())),
            op: BinOp::Add,
            right: Box::new(Expr::Ident("b".into())),
        })));
        assert!(stmt_to_swift(&e).contains("return"));
        assert!(stmt_to_swift(&e).contains("+"));
    }
}
