//! Swift backend spike (PAR-005) — minimal core-shape lowering.
//!
//! Most language features are **unsupported** (capability matrix). Only
//! structs/enums/simple fns lower. Not production-ready.

use veil_ir::ast::*;
use veil_ir::layer::{LayerRegistry, Shape};

use crate::capabilities::Feature;

pub struct SwiftProject {
    pub files: Vec<SwiftFile>,
}

pub struct SwiftFile {
    pub path: String,
    pub content: String,
}

/// Features Swift spike claims (everything else fails closed via check).
pub fn swift_supported_features() -> std::collections::HashSet<Feature> {
    use Feature::*;
    [MatchExpr, TryOperator].into_iter().collect()
}

pub fn generate_swift(solution: &Solution, _registry: &LayerRegistry) -> SwiftProject {
    let mut body = String::from("// Generated by VEIL Swift spike (PAR-005) — not production-ready\n\n");
    body.push_str("import Foundation\n\n");

    for item in &solution.items {
        let TopLevelItem::Construct(c) = item else {
            continue;
        };
        emit_construct(&mut body, c);
    }

    // Free functions
    for item in &solution.items {
        if let TopLevelItem::Function(f) = item {
            emit_fn(&mut body, f);
        }
        if let TopLevelItem::Construct(c) = item {
            for f in &c.fns {
                emit_fn(&mut body, f);
            }
            for child in &c.children {
                walk_fns(&mut body, child);
            }
        }
    }

    SwiftProject {
        files: vec![SwiftFile {
            path: format!("Sources/{}/Generated.swift", solution.name),
            content: body,
        }],
    }
}

fn walk_fns(out: &mut String, c: &Construct) {
    for f in &c.fns {
        emit_fn(out, f);
    }
    for child in &c.children {
        walk_fns(out, child);
    }
}

fn emit_construct(out: &mut String, c: &Construct) {
    match c.shape {
        Shape::Struct => {
            out.push_str(&format!("struct {}: Codable {{\n", c.name));
            for f in &c.fields {
                out.push_str(&format!(
                    "    var {}: {}\n",
                    f.name,
                    type_to_swift(&f.type_expr)
                ));
            }
            for b in &c.blocks {
                for f in &b.fields {
                    out.push_str(&format!(
                        "    var {}: {}\n",
                        f.name,
                        type_to_swift(&f.type_expr)
                    ));
                }
            }
            out.push_str("}\n\n");
        }
        Shape::Enum => {
            out.push_str(&format!("enum {} {{\n", c.name));
            for v in &c.variants {
                out.push_str(&format!("    case {}\n", to_camel(v)));
            }
            out.push_str("}\n\n");
        }
        Shape::Mod | Shape::Group => {
            for child in &c.children {
                emit_construct(out, child);
            }
        }
        _ => {}
    }
}

fn emit_fn(out: &mut String, f: &FnDef) {
    let params = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, type_to_swift(&p.type_expr)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = f
        .return_type
        .as_ref()
        .map(|t| format!(" -> {}", type_to_swift(t)))
        .unwrap_or_default();
    out.push_str(&format!("func {}({}){} {{\n", f.name, params, ret));
    out.push_str("    fatalError(\"VEIL Swift spike: body not lowered\")\n");
    out.push_str("}\n\n");
}

fn type_to_swift(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(n) => match n.as_str() {
            "Str" => "String".into(),
            "Int" => "Int".into(),
            "F64" => "Double".into(),
            "Bool" => "Bool".into(),
            "UUID" | "Id" => "UUID".into(),
            other => other.to_string(),
        },
        TypeExpr::Optional(inner) => format!("{}?", type_to_swift(inner)),
        TypeExpr::List(inner) => format!("[{}]", type_to_swift(inner)),
        TypeExpr::Result(Some(inner)) => format!("Result<{}, Error>", type_to_swift(inner)),
        TypeExpr::Result(None) => "Result<Void, Error>".into(),
        _ => "Any".into(),
    }
}

fn to_camel(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_res_types() {
        assert_eq!(
            type_to_swift(&TypeExpr::Result(None)),
            "Result<Void, Error>"
        );
        assert_eq!(
            type_to_swift(&TypeExpr::Result(Some(Box::new(TypeExpr::Named(
                "Str".into()
            ))))),
            "Result<String, Error>"
        );
        assert_eq!(type_to_swift(&TypeExpr::Named("Int".into())), "Int");
    }
}
