// Generated by VEIL — do not edit

export interface ApiClient {
  fetch(
    endpoint: string,
    params: Record<string, unknown>,
  ): Promise<Record<string, unknown>>;
  mutate(
    endpoint: string,
    body: Record<string, unknown>,
  ): Promise<Record<string, unknown>>;
}
