// Generated by VEIL — do not edit

export interface ViewModeToggle {
  mode: string;
  className: string;
}

export interface PageHeader {
  title: string;
  description: string;
  actions: Snippet | null;
  children: Snippet | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface EmptyState {
  title: string;
  description: string;
  actionHref: string;
  actionLabel: string;
  agent: Record<string, unknown>;
  hasAction: boolean;
  veilAgent: Record<string, unknown>;
}

export interface FormProgress {
  requiredValues: string[];
  submitLabel: string;
  savingLabel: string;
  saving: boolean;
  onSubmit: () => void | null;
}

export interface FormSection {
  title: string;
  columns: number;
  children: Snippet | null;
}

export interface FormField {
  id: string;
  label: string;
  inputType: string;
  required: boolean;
  placeholder: string;
  hint: string;
  error: string;
  value: string;
  options: Record<string, unknown>[];
  rows: number;
  children: Snippet | null;
  agent: Record<string, unknown>;
  onchange: Fn | null;
  oninput: Fn | null;
  veilAgent: Record<string, unknown>;
}

export interface CreateFormShell {
  title: string;
  subtitle: string;
  backHref: string;
  backBehavior: string;
  mode: string;
  submitLabel: string;
  savingLabel: string;
  saving: boolean;
  showSubmit: boolean;
  requiredValues: string[];
  onSubmit: () => void | null;
  loading: boolean;
  loadingLabel: string;
  error: string;
  children: Snippet | null;
  headerActions: Snippet | null;
  footer: Snippet | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface DetailShell {
  title: string;
  subtitle: string;
  backHref: string;
  backBehavior: string;
  loading: boolean;
  loadingLabel: string;
  error: string;
  children: Snippet | null;
  headerActions: Snippet | null;
  summary: Snippet | null;
  sidebar: Snippet | null;
  footer: Snippet | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface DetailField {
  id: string;
  label: string;
  value: string;
  emptyLabel: string;
  mono: boolean;
  pre: boolean;
  children: Snippet | null;
  agent: Record<string, unknown>;
  isEmpty: boolean;
  veilAgent: Record<string, unknown>;
}

export interface StatusPill {
  label: string;
  status: string;
  variant: string;
  pillMap: Record<string, unknown>;
  text: string;
}

export interface EntityIdentity {
  name: string;
  subtitle: string;
  showAvatar: boolean;
  size: string;
  letter: string;
}

export interface Modal {
  open: boolean;
  title: string;
  size: string;
  closeOnBackdrop: boolean;
  children: Snippet | null;
  footer: Snippet | null;
  onClose: () => void | null;
  agent: Record<string, unknown>;
  dialogEl: Any;
  veilAgent: Record<string, unknown>;
}

export interface ConfirmDialog {
  open: boolean;
  title: string;
  message: string;
  confirmLabel: string;
  cancelLabel: string;
  variant: string;
  busy: boolean;
  onConfirm: () => void | null;
  onCancel: () => void | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface AlertDialog {
  open: boolean;
  title: string;
  message: string;
  okLabel: string;
  onOk: () => void | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface PromptDialog {
  open: boolean;
  title: string;
  message: string;
  defaultValue: string;
  placeholder: string;
  confirmLabel: string;
  cancelLabel: string;
  onConfirm: (arg0: string) => void | null;
  onCancel: () => void | null;
  agent: Record<string, unknown>;
  value: string;
  veilAgent: Record<string, unknown>;
}

export interface ContextMenu {
  items: Record<string, unknown>[];
  align: string;
  ariaLabel: string;
  children: Snippet | null;
  agent: Record<string, unknown>;
  open: boolean;
  rootEl: Any;
  menuEl: Any;
  veilAgent: Record<string, unknown>;
}

export interface CollectionView {
  title: string;
  description: string;
  items: Record<string, unknown>[];
  loading: boolean;
  error: string;
  viewMode: string;
  defaultLayout: string;
  showAvatar: boolean;
  emptyTitle: string;
  emptyDescription: string;
  emptyActionHref: string;
  emptyActionLabel: string;
  primaryHref: string;
  primaryLabel: string;
  itemHrefTemplate: string;
  layoutStorageKey: string;
  columns: Record<string, unknown>[];
  tile: Snippet | null;
  row: Snippet | null;
  headerActions: Snippet | null;
  agent: Record<string, unknown>;
  layout: string;
  showToggle: boolean;
  veilAgent: Record<string, unknown>;
}

export interface WizardShell {
  title: string;
  subtitle: string;
  steps: string[];
  currentStep: number;
  children: Snippet | null;
  footer: Snippet | null;
  onClose: () => void | null;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface ChoiceCards {
  value: string;
  options: Record<string, unknown>[];
  columns: number;
  layout: string;
  agent: Record<string, unknown>;
  veilAgent: Record<string, unknown>;
}

export interface AgentSurface {
  pollMs: number;
}

export interface RepeatEditor {
  items: Record<string, unknown>[];
  label: string;
  addLabel: string;
  emptyLabel: string;
  collapsible: boolean;
  summaryKey: string;
  maxItems: number;
  itemTemplate: Snippet | null;
  onAdd: () => void | null;
  onRemove: (arg0: number) => void | null;
  agent: Record<string, unknown>;
  collapsed: boolean[];
  canAdd: boolean;
  veilAgent: Record<string, unknown>;
}

export interface ConnectionStore {
  status: string;
  url: string;
}

export interface Sidebar {
  openCrCount: number;
}

export interface StatusBar {
  status: string;
}

export interface StatCard {
  value: string;
  label: string;
}

export interface DashboardView {
  repos: Record<string, unknown>[];
  loading: boolean;
  error: string;
  projectHrefTpl: string;
}

export interface ProjectsView {
  repos: Record<string, unknown>[];
  loading: boolean;
  error: string;
  projectHrefTpl: string;
  deleteOpen: boolean;
  deletingId: string;
  deleteName: string;
  deleteBusy: boolean;
}

export interface ProjectCreateView {
  name: string;
  description: string;
  submitting: boolean;
  error: string;
}

export interface ProjectDetailView {
  id: string;
  name: string;
  slug: string;
  description: string;
  defaultBranch: string;
  createdAt: string;
  updatedAt: string;
  loading: boolean;
  error: string;
  loaded: boolean;
  deleteOpen: boolean;
  deleteBusy: boolean;
  environment: string;
  envOptions: string[];
  envRoleHint: string;
  infra: Record<string, unknown>;
  units: Record<string, unknown>[];
  hasDeploy: boolean;
  hasToml: boolean;
  region: string;
  projectPrefix: string;
  networkVpc: string;
  tomlPath: string;
  provisionBusy: boolean;
  provisionMsg: string;
  provisionJobId: string;
  provisionPercent: number;
  provisionStatus: string;
  provisionSteps: Record<string, unknown>[];
  planOpen: boolean;
  planLoading: boolean;
  planSummary: string;
  planMock: boolean;
  planResources: Record<string, unknown>[];
  planSteps: Record<string, unknown>[];
  planNotes: string[];
  planDiff: Record<string, unknown>;
  planCta: string;
  awsInventory: Record<string, unknown>[];
  stackBase: string;
  provisionCta: string;
  anyProvisioned: boolean;
  infraStatus: string;
  infraStatusVariant: string;
}

export interface DeployView {
  artifactId: string;
  targetType: string;
  deploying: boolean;
  error: string;
}

export interface RegistryView {
  layers: Record<string, unknown>[];
  stubs: Record<string, unknown>[];
  loading: boolean;
  error: string;
}

export interface BusView {
  testMessage: string;
  result: string | null;
  sending: boolean;
  error: string;
}

export interface AgentsView {
  messages: Record<string, unknown>[];
  userInput: string;
  sending: boolean;
  error: string;
}

export interface ConfigView {
  awsRegion: string;
  s3Bucket: string;
  ddbTable: string;
  llmModel: string;
  saving: boolean;
  error: string;
}

export interface PullRequestsView {
  changeRequests: Record<string, unknown>[];
  loading: boolean;
  error: string;
  activeFilter: string;
  crHrefTpl: string;
}

export interface PullRequestDetailView {
  id: string;
  cr: Record<string, unknown>;
  diff: Record<string, unknown>;
  comments: Record<string, unknown>[];
  approvals: Record<string, unknown>[];
  ci: Record<string, unknown>;
  loading: boolean;
  error: string;
  loaded: boolean;
  actionBusy: boolean;
  newComment: string;
  newCommentPath: string;
  commentSubmitting: boolean;
}

export interface AppLayout {
}

export interface Dashboard {
}

export interface Projects {
}

export interface ProjectCreate {
}

export interface ProjectDetail {
}

export interface Deploy {
}

export interface Registry {
}

export interface Bus {
}

export interface Agents {
}

export interface Config {
}

export interface Changes {
}

export interface ChangeDetail {
}

