// Generated by VEIL — do not edit

export interface ConnectionStore {
  status: string;
  url: string;
}

export interface Sidebar {
  navItems: Record<string, unknown>[];
}

export interface StatusBar {
  status: string;
}

export interface StatCard {
  value: string;
  label: string;
}

export interface ProjectCard {
  name: string;
  branch: string;
  updatedAt: string;
  id: string;
}

export interface DashboardView {
  repos: Record<string, unknown>[];
  loading: boolean;
}

export interface ProjectsView {
  repos: Record<string, unknown>[];
  newName: string;
}

export interface DeployView {
  artifactId: string;
  targetType: string;
  deploying: boolean;
}

export interface RegistryView {
  layers: Record<string, unknown>[];
  stubs: Record<string, unknown>[];
}

export interface BusView {
  testMessage: string;
  result: string | null;
}

export interface AgentsView {
  messages: Record<string, unknown>[];
  userInput: string;
}

export interface ConfigView {
  awsRegion: string;
  s3Bucket: string;
  ddbTable: string;
  llmModel: string;
  saving: boolean;
}

export interface AppLayout {}

export interface Dashboard {}

export interface Projects {}

export interface Deploy {}

export interface Registry {}

export interface Bus {}

export interface Agents {}

export interface Config {}
