// Agent module — public API
export {
	agentMessages,
	agentIsStreaming,
	agentIsThinking,
	agentError,
	agentStatusLine,
	agentComposerKey,
	agentPendingSeed,
	agentPanelOpen,
	agentPanelMinimized,
	openAgentPanel,
	agentUnreadCount,
	agentSend,
	agentAbort,
	agentClear,
	agentInsertToken,
	agentPendingAttachments,
	agentAddAttachments,
	agentRemovePendingAttachment,
	agentClearPendingAttachments,
	agentApproveToolCall,
	setAgentContext,
	getAgentContext,
	ideDiagnosticsSummary,
	onAgentNavigation,
	restoreSession,
	initIdeBridge,
	destroyIdeBridge,
	registerIdeFrame,
	unregisterIdeFrame,
	sendToIde,
	getCodingSessionId,
	setCodingSessionId,
	ensureCodingSession,
	hydrateFromServer,
	type AgentContext,
	type NavigationAction,
	type IdeBridgeMessage,
} from './runtimeAgentSession';

export {
	sessionFocus,
	patchFocus,
	getFocus,
	publishRouteFocus,
	formatFocusForAgent,
	focusPayload,
	onFocusChange,
	type SessionFocus,
	type FocusPane,
} from './focus';

export {
	executeIntent,
	intentFromToolResult,
	STAGED_PRESENT_TOOLS,
	presentFastForward,
	setPresentFastForward,
	recordIntent,
	recentIntents,
	formatIntentLogForAgent,
	installHumanIntentCapture,
	restoreIntentLog,
	mergeIntentLogFromServer,
	type Intent,
	type Present,
	type PresentStep,
	type IntentLogEntry,
} from './intent';

export { default as AgentDock } from './AgentDock.svelte';
