[package]
name = "veil_bin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "veil_bin"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
veil_shared = { path = "../veil_shared" }
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
design_kit = { path = "../design_kit" }
runtime_u_i = { path = "../runtime_u_i" }
